/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XIadd_nicknames[];
extern CL_INIT XFadd_nicknames[];
CL_INIT Kadd_nicknames[] =
{
	MAKE_STRING(35, "package with name ~S already exists"),	/* 0 */
};

void add_nicknames(CL_FORM *base)
{
	LOAD_NIL(ARG(2));
	COPY(ARG(0), ARG(3));
	M1_1:;
	if(CL_ATOMP(ARG(3)))
	{
		LOAD_NIL(ARG(2));
		COPY(ARG(2), ARG(0));
		goto RETURN1;
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CAR(ARG(4)), ARG(2));
	if(CL_SYMBOLP(ARG(2)) || CL_NILP(ARG(2)))
	{
		COPY(ARG(2), ARG(4));
		if(CL_SYMBOLP(ARG(4)))
		{
			GET_SYM_NAME(ARG(6), ARG(4), ARG(2));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(2));	/* NIL */
		}
	}
	COPY(ARG(2), ARG(4));
	Ffind_package(ARG(4));
	if(EQ(ARG(4), ARG(1)))
	{
	}
	else
	{
		if(CL_TRUEP(ARG(4)))
		{
			LOAD_SMSTR((CL_FORM *)&Kadd_nicknames[0], ARG(5));	/* package with name ~S already exists */
			Ferror(ARG(5), 1);
		}
		else
		{
			COPY(ARG(1), ARG(6));
			Ppackage_nicknames(ARG(6));
			ALLOC_CONS(ARG(7), ARG(2), ARG(6), ARG(5));
			COPY(ARG(1), ARG(6));
			set_Ppackage_nicknames(ARG(5));
		}
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CDR(ARG(4)), ARG(3));
	goto M1_1;
	RETURN1:;
}
