/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XIadjust_array1[];
extern CL_INIT XFadjust_array1[];
CL_INIT Kadjust_array1[] =
{
	MAKE_STRING(116, "The \'new-dimensions\' argument given to ADJUST-ARRAY, ~A, ~\n              is not the same rank as the argument array."),	/* 0 */
};

static void Z65_dim_to_skips(CL_FORM *base);
static void Z66_rmi_copy(CL_FORM *base, CL_FORM *display[]);

void adjust_array1(CL_FORM *base)
{
	CL_FORM *display[1];
	if(CL_SMVECP(ARG(0)))
	{
		COPY(ARG(0), ARG(10));
		rt_plain_vector_element_code(ARG(10));
	}
	else
	{
		COPY(ARG(0), ARG(10));
		M1_1:;
		COPY(ARG(10), ARG(11));
		COPY(ARG(11), ARG(12));
		LOAD_SMALLFIXNUM(0, ARG(13));
		COPY(ARG(12), ARG(14));
		LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(15));	/* COMPLEX-BASE-ARRAY */
		rt_struct_typep(ARG(14));
		if(CL_TRUEP(ARG(14)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(12))), GET_FIXNUM(ARG(13)) + 1), ARG(10));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(10));	/* NO_STRUCT */
			COPY(ARG(12), ARG(11));
			LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(12));	/* COMPLEX-BASE-ARRAY */
			Ferror(ARG(10), 3);
		}
		if(CL_SMVECP(ARG(10)))
		{
		}
		else
		{
			goto M1_1;
		}
		goto RETURN1;
		RETURN1:;
		rt_plain_vector_element_code(ARG(10));
	}
	to_element_type(ARG(10));
	if(CL_SMVECP(ARG(0)))
	{
		LOAD_FIXNUM(ARG(12), AR_SIZE(GET_FORM(ARG(0))), ARG(11));
		Flist(ARG(11), 1);
	}
	else
	{
		COPY(ARG(0), ARG(11));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(12));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(11));
		if(CL_TRUEP(ARG(11)))
		{
			COPY(ARG(0), ARG(11));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(12));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(11));
			if(CL_TRUEP(ARG(11)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), 2 + 1), ARG(11));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(11));	/* NO_STRUCT */
				COPY(ARG(0), ARG(12));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(13));	/* COMPLEX-VECTOR */
				Ferror(ARG(11), 3);
			}
			Flist(ARG(11), 1);
		}
		else
		{
			COPY(ARG(0), ARG(11));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(12));	/* COMPLEX-ARRAY */
			rt_struct_typep(ARG(11));
			if(CL_TRUEP(ARG(11)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), 2 + 1), ARG(11));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(11));	/* NO_STRUCT */
				COPY(ARG(0), ARG(12));
				LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(13));	/* COMPLEX-ARRAY */
				Ferror(ARG(11), 3);
			}
		}
	}
	LOAD_NIL(ARG(12));
	if(CL_ATOMP(ARG(1)))
	{
		COPY(ARG(1), ARG(13));
		Flist(ARG(13), 1);
		COPY(ARG(13), ARG(1));
	}
	COPY(ARG(1), ARG(13));
	Flength(ARG(13));
	COPY(ARG(0), ARG(14));
	Farray_rank(ARG(14));
	Fnumneql(ARG(13), 2);
	if(CL_TRUEP(ARG(13)))
	{
		LOAD_SMSTR((CL_FORM *)&Kadjust_array1[0], ARG(13));	/* The 'new-dimensions' argument given to ADJUST-ARRAY, ~A, ~
              is not the same rank as the argument array. */
		COPY(ARG(1), ARG(14));
		Ferror(ARG(13), 2);
	}
	COPY(ARG(0), ARG(13));
	LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(14));	/* COMPLEX-VECTOR */
	rt_struct_typep(ARG(13));
	if(CL_TRUEP(ARG(13)))
	{
		COPY(ARG(0), ARG(13));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(14));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(13));
		if(CL_TRUEP(ARG(13)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), 3 + 1), ARG(13));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(13));	/* NO_STRUCT */
			COPY(ARG(0), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(15));	/* COMPLEX-VECTOR */
			Ferror(ARG(13), 3);
		}
		Fminusp(ARG(13));
		if(CL_TRUEP(ARG(13)))
		{
			goto ELSE1;
		}
		else
		{
			goto THEN2;
		}
	}
	else
	{
		goto ELSE1;
	}
	{
		THEN2:;
		if(CL_TRUEP(ARG(5)))
		{
			goto ELSE3;
		}
		else
		{
			goto THEN4;
		}
	}
	goto ENDIF5;
	{
		ELSE1:;
		goto ELSE3;
	}
	ENDIF5:;
	{
		THEN4:;
		COPY(ARG(0), ARG(13));
		COPY(ARG(13), ARG(14));
		COPY(ARG(14), ARG(15));
		LOAD_SMALLFIXNUM(3, ARG(16));
		COPY(ARG(15), ARG(17));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(18));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(17));
		if(CL_TRUEP(ARG(17)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(15))), GET_FIXNUM(ARG(16)) + 1), ARG(5));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(17));	/* NO_STRUCT */
			COPY(ARG(15), ARG(18));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(19));	/* COMPLEX-VECTOR */
			Ferror(ARG(17), 3);
		}
	}
	ELSE3:;
	LOAD_GLOBFUN(&CFmake_array, ARG(12));
	COPY(ARG(1), ARG(13));
	LOAD_SYMBOL(SYMBOL(Slisp, 99), ARG(14));	/* ELEMENT-TYPE */
	COPY(ARG(10), ARG(15));
	LOAD_SYMBOL(SYMBOL(Slisp, 100), ARG(16));	/* ADJUSTABLE */
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(17));	/* T */
	LOAD_SYMBOL(SYMBOL(Slisp, 101), ARG(18));	/* FILL-POINTER */
	COPY(ARG(5), ARG(19));
	COPY(ARG(8), ARG(20));
	Fapply(ARG(12), 9);
	mv_count = 1;
	if(CL_TRUEP(ARG(4)))
	{
	}
	else
	{
		LOAD_GLOBFUN(&CFmin, ARG(13));
		COPY(ARG(1), ARG(14));
		COPY(ARG(11), ARG(15));
		Fmapcar(ARG(13), 3);
		COPY(ARG(1), ARG(14));
		Z65_dim_to_skips(ARG(14));
		if(CL_CONSP(ARG(14)))
		{
			COPY(GET_CDR(ARG(14)), ARG(14));
		}
		else
		{
			if(CL_TRUEP(ARG(14)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(15));	/* ~a is not a list */
				COPY(ARG(14), ARG(16));
				Ferror(ARG(15), 2);
			}
			else
			{
				LOAD_NIL(ARG(14));
			}
		}
		COPY(ARG(11), ARG(15));
		Z65_dim_to_skips(ARG(15));
		if(CL_CONSP(ARG(15)))
		{
			COPY(GET_CDR(ARG(15)), ARG(15));
		}
		else
		{
			if(CL_TRUEP(ARG(15)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(16));	/* ~a is not a list */
				COPY(ARG(15), ARG(17));
				Ferror(ARG(16), 2);
			}
			else
			{
				LOAD_NIL(ARG(15));
			}
		}
		LOAD_SMALLFIXNUM(0, ARG(16));
		LOAD_SMALLFIXNUM(0, ARG(17));
		display[0] = ARG(0);
		Z66_rmi_copy(ARG(13), display);
	}
	COPY(ARG(0), ARG(13));
	LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(14));	/* COMPLEX-ARRAY */
	rt_struct_typep(ARG(13));
	if(CL_TRUEP(ARG(13)))
	{
		COPY(ARG(12), ARG(13));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(14));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(13));
		if(CL_TRUEP(ARG(13)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(12))), 0 + 1), ARG(13));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(13));	/* NO_STRUCT */
			COPY(ARG(12), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(15));	/* COMPLEX-ARRAY */
			Ferror(ARG(13), 3);
		}
		LOAD_SMALLFIXNUM(0, ARG(14));
		COPY(ARG(0), ARG(15));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(16));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(15));
		if(CL_TRUEP(ARG(15)))
		{
			COPY(ARG(13), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(14)) + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(15));	/* NO_STRUCT */
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(17));	/* COMPLEX-ARRAY */
			Ferror(ARG(15), 3);
		}
		COPY(ARG(12), ARG(13));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(14));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(13));
		if(CL_TRUEP(ARG(13)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(12))), 1 + 1), ARG(13));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(13));	/* NO_STRUCT */
			COPY(ARG(12), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(15));	/* COMPLEX-ARRAY */
			Ferror(ARG(13), 3);
		}
		LOAD_SMALLFIXNUM(1, ARG(14));
		COPY(ARG(0), ARG(15));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(16));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(15));
		if(CL_TRUEP(ARG(15)))
		{
			COPY(ARG(13), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(14)) + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(15));	/* NO_STRUCT */
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(17));	/* COMPLEX-ARRAY */
			Ferror(ARG(15), 3);
		}
		COPY(ARG(12), ARG(13));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(14));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(13));
		if(CL_TRUEP(ARG(13)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(12))), 2 + 1), ARG(13));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(13));	/* NO_STRUCT */
			COPY(ARG(12), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(15));	/* COMPLEX-ARRAY */
			Ferror(ARG(13), 3);
		}
		LOAD_SMALLFIXNUM(2, ARG(14));
		COPY(ARG(0), ARG(15));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(16));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(15));
		if(CL_TRUEP(ARG(15)))
		{
			COPY(ARG(13), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(14)) + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(15));	/* NO_STRUCT */
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(17));	/* COMPLEX-ARRAY */
			Ferror(ARG(15), 3);
		}
	}
	else
	{
		COPY(ARG(12), ARG(13));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(14));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(13));
		if(CL_TRUEP(ARG(13)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(12))), 0 + 1), ARG(13));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(13));	/* NO_STRUCT */
			COPY(ARG(12), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(15));	/* COMPLEX-VECTOR */
			Ferror(ARG(13), 3);
		}
		LOAD_SMALLFIXNUM(0, ARG(14));
		COPY(ARG(0), ARG(15));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(16));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(15));
		if(CL_TRUEP(ARG(15)))
		{
			COPY(ARG(13), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(14)) + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(15));	/* NO_STRUCT */
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(17));	/* COMPLEX-VECTOR */
			Ferror(ARG(15), 3);
		}
		COPY(ARG(12), ARG(13));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(14));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(13));
		if(CL_TRUEP(ARG(13)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(12))), 1 + 1), ARG(13));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(13));	/* NO_STRUCT */
			COPY(ARG(12), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(15));	/* COMPLEX-VECTOR */
			Ferror(ARG(13), 3);
		}
		LOAD_SMALLFIXNUM(1, ARG(14));
		COPY(ARG(0), ARG(15));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(16));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(15));
		if(CL_TRUEP(ARG(15)))
		{
			COPY(ARG(13), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(14)) + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(15));	/* NO_STRUCT */
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(17));	/* COMPLEX-VECTOR */
			Ferror(ARG(15), 3);
		}
		COPY(ARG(12), ARG(13));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(14));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(13));
		if(CL_TRUEP(ARG(13)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(12))), 2 + 1), ARG(13));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(13));	/* NO_STRUCT */
			COPY(ARG(12), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(15));	/* COMPLEX-VECTOR */
			Ferror(ARG(13), 3);
		}
		LOAD_SMALLFIXNUM(2, ARG(14));
		COPY(ARG(0), ARG(15));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(16));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(15));
		if(CL_TRUEP(ARG(15)))
		{
			COPY(ARG(13), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(14)) + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(15));	/* NO_STRUCT */
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(17));	/* COMPLEX-VECTOR */
			Ferror(ARG(15), 3);
		}
		COPY(ARG(12), ARG(13));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(14));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(13));
		if(CL_TRUEP(ARG(13)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(12))), 3 + 1), ARG(13));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(13));	/* NO_STRUCT */
			COPY(ARG(12), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(15));	/* COMPLEX-VECTOR */
			Ferror(ARG(13), 3);
		}
		LOAD_SMALLFIXNUM(3, ARG(14));
		COPY(ARG(0), ARG(15));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(16));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(15));
		if(CL_TRUEP(ARG(15)))
		{
			COPY(ARG(13), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(14)) + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(15));	/* NO_STRUCT */
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(17));	/* COMPLEX-VECTOR */
			Ferror(ARG(15), 3);
		}
	}
}

static void Z65_dim_to_skips(CL_FORM *base)
{
	if(CL_CONSP(ARG(0)))
	{
		bool_result = CL_TRUEP(GET_CDR(ARG(0)));
	}
	else
	{
		if(CL_TRUEP(ARG(0)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(1));	/* ~a is not a list */
			COPY(ARG(0), ARG(2));
			Ferror(ARG(1), 2);
		}
		else
		{
			bool_result = CL_TRUEP(ARG(0));
		}
	}
	if(bool_result)
	{
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CDR(ARG(0)), ARG(1));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(1));	/* ~a is not a list */
				COPY(ARG(0), ARG(2));
				Ferror(ARG(1), 2);
			}
			else
			{
				COPY(ARG(0), ARG(1));
			}
		}
		Z65_dim_to_skips(ARG(1));
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CAR(ARG(0)), ARG(2));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(2));	/* ~a is not a list */
				COPY(ARG(0), ARG(3));
				Ferror(ARG(2), 2);
			}
			else
			{
				COPY(ARG(0), ARG(2));
			}
		}
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CAR(ARG(1)), ARG(3));
		}
		else
		{
			if(CL_TRUEP(ARG(1)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(3));	/* ~a is not a list */
				COPY(ARG(1), ARG(4));
				Ferror(ARG(3), 2);
			}
			else
			{
				COPY(ARG(1), ARG(3));
			}
		}
		Fmult(ARG(2), 2);
		ALLOC_CONS(ARG(4), ARG(2), ARG(1), ARG(0));
	}
	else
	{
	}
}

static void Z66_rmi_copy(CL_FORM *base, CL_FORM *display[])
{
	if(CL_CONSP(ARG(0)))
	{
		bool_result = CL_TRUEP(GET_CDR(ARG(0)));
	}
	else
	{
		if(CL_TRUEP(ARG(0)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(5));	/* ~a is not a list */
			COPY(ARG(0), ARG(6));
			Ferror(ARG(5), 2);
		}
		else
		{
			bool_result = CL_TRUEP(ARG(0));
		}
	}
	if(bool_result)
	{
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CAR(ARG(0)), ARG(5));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(5));	/* ~a is not a list */
				COPY(ARG(0), ARG(6));
				Ferror(ARG(5), 2);
			}
			else
			{
				COPY(ARG(0), ARG(5));
			}
		}
		LOAD_SMALLFIXNUM(0, ARG(6));
		M1_1:;
		COPY(ARG(6), ARG(7));
		COPY(ARG(5), ARG(8));
		Fge(ARG(7), 2);
		if(CL_TRUEP(ARG(7)))
		{
			LOAD_NIL(ARG(0));
			goto RETURN1;
		}
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CDR(ARG(0)), ARG(7));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(7));	/* ~a is not a list */
				COPY(ARG(0), ARG(8));
				Ferror(ARG(7), 2);
			}
			else
			{
				COPY(ARG(0), ARG(7));
			}
		}
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CDR(ARG(1)), ARG(8));
		}
		else
		{
			if(CL_TRUEP(ARG(1)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(8));	/* ~a is not a list */
				COPY(ARG(1), ARG(9));
				Ferror(ARG(8), 2);
			}
			else
			{
				COPY(ARG(1), ARG(8));
			}
		}
		if(CL_CONSP(ARG(2)))
		{
			COPY(GET_CDR(ARG(2)), ARG(9));
		}
		else
		{
			if(CL_TRUEP(ARG(2)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(9));	/* ~a is not a list */
				COPY(ARG(2), ARG(10));
				Ferror(ARG(9), 2);
			}
			else
			{
				COPY(ARG(2), ARG(9));
			}
		}
		COPY(ARG(3), ARG(10));
		COPY(ARG(6), ARG(11));
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CAR(ARG(1)), ARG(12));
		}
		else
		{
			if(CL_TRUEP(ARG(1)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(12));	/* ~a is not a list */
				COPY(ARG(1), ARG(13));
				Ferror(ARG(12), 2);
			}
			else
			{
				COPY(ARG(1), ARG(12));
			}
		}
		Fmult(ARG(11), 2);
		Fplus(ARG(10), 2);
		COPY(ARG(4), ARG(11));
		COPY(ARG(6), ARG(12));
		if(CL_CONSP(ARG(2)))
		{
			COPY(GET_CAR(ARG(2)), ARG(13));
		}
		else
		{
			if(CL_TRUEP(ARG(2)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(13));	/* ~a is not a list */
				COPY(ARG(2), ARG(14));
				Ferror(ARG(13), 2);
			}
			else
			{
				COPY(ARG(2), ARG(13));
			}
		}
		Fmult(ARG(12), 2);
		Fplus(ARG(11), 2);
		Z66_rmi_copy(ARG(7), display);
		F1plus(ARG(6));
		goto M1_1;
		RETURN1:;
	}
	else
	{
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CAR(ARG(0)), ARG(5));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(5));	/* ~a is not a list */
				COPY(ARG(0), ARG(6));
				Ferror(ARG(5), 2);
			}
			else
			{
				COPY(ARG(0), ARG(5));
			}
		}
		LOAD_SMALLFIXNUM(0, ARG(6));
		M2_1:;
		COPY(ARG(6), ARG(7));
		COPY(ARG(5), ARG(8));
		Fge(ARG(7), 2);
		if(CL_TRUEP(ARG(7)))
		{
			LOAD_NIL(ARG(0));
			goto RETURN2;
		}
		COPY(&display[0][0], ARG(7));
		COPY(ARG(4), ARG(8));
		Frow_major_aref(ARG(7));
		COPY(&display[0][12], ARG(8));
		COPY(ARG(3), ARG(9));
		Fset_row_major_aref(ARG(7));
		COPY(ARG(3), ARG(7));
		F1plus(ARG(7));
		COPY(ARG(7), ARG(3));
		COPY(ARG(4), ARG(7));
		F1plus(ARG(7));
		COPY(ARG(7), ARG(4));
		F1plus(ARG(6));
		goto M2_1;
		RETURN2:;
	}
}
