/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XIbit_op[];
extern CL_INIT XFbit_op[];
CL_INIT Kbit_op[] =
{
	MAKE_STRING(39, "~A and ~A must have the same dimensions"),	/* 0 */
	MAKE_STRING(98, "~A must have the same dimensions as the other ~\n                              bit-array parameters"),	/* 2 */
};

void bit_op(CL_FORM *base)
{
	COPY(ARG(1), ARG(4));
	Fbit_array_p(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(4));	/* WRONG_TYPE */
		COPY(ARG(1), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 155), ARG(6));	/* BIT-ARRAY */
		Ferror(ARG(4), 3);
	}
	COPY(ARG(2), ARG(4));
	Fbit_array_p(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(4));	/* WRONG_TYPE */
		COPY(ARG(2), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 155), ARG(6));	/* BIT-ARRAY */
		Ferror(ARG(4), 3);
	}
	if(CL_SMVECP(ARG(1)))
	{
		LOAD_FIXNUM(ARG(5), AR_SIZE(GET_FORM(ARG(1))), ARG(4));
		Flist(ARG(4), 1);
	}
	else
	{
		COPY(ARG(1), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(5));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(4));
		if(CL_TRUEP(ARG(4)))
		{
			COPY(ARG(1), ARG(4));
			complex_vector_length(ARG(4));
			Flist(ARG(4), 1);
		}
		else
		{
			COPY(ARG(1), ARG(4));
			complex_array_dims(ARG(4));
		}
	}
	if(CL_SMVECP(ARG(2)))
	{
		LOAD_FIXNUM(ARG(6), AR_SIZE(GET_FORM(ARG(2))), ARG(5));
		Flist(ARG(5), 1);
	}
	else
	{
		COPY(ARG(2), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(6));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(5));
		if(CL_TRUEP(ARG(5)))
		{
			COPY(ARG(2), ARG(5));
			complex_vector_length(ARG(5));
			Flist(ARG(5), 1);
		}
		else
		{
			COPY(ARG(2), ARG(5));
			complex_array_dims(ARG(5));
		}
	}
	Fequal(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kbit_op[0], ARG(4));	/* ~A and ~A must have the same dimensions */
		COPY(ARG(1), ARG(5));
		COPY(ARG(2), ARG(6));
		Ferror(ARG(4), 3);
	}
	COPY(ARG(0), ARG(4));
	COPY(ARG(1), ARG(5));
	COPY(ARG(2), ARG(6));
	if(CL_TRUEP(ARG(3)))
	{
		if(CL_SYMBOLP(ARG(3)) && GET_SYMBOL(ARG(3)) == SYMBOL(Slisp, 48))	/* T */
		{
			COPY(ARG(1), ARG(7));
		}
		else
		{
			COPY(ARG(3), ARG(7));
			Fbit_array_p(ARG(7));
			if(CL_TRUEP(ARG(7)))
			{
			}
			else
			{
				COPY(SYMVAL(Slisp, 58), ARG(7));	/* WRONG_TYPE */
				COPY(ARG(3), ARG(8));
				LOAD_SYMBOL(SYMBOL(Slisp, 155), ARG(9));	/* BIT-ARRAY */
				Ferror(ARG(7), 3);
			}
			if(CL_SMVECP(ARG(1)))
			{
				LOAD_FIXNUM(ARG(8), AR_SIZE(GET_FORM(ARG(1))), ARG(7));
				Flist(ARG(7), 1);
			}
			else
			{
				COPY(ARG(1), ARG(7));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(8));	/* COMPLEX-VECTOR */
				rt_struct_typep(ARG(7));
				if(CL_TRUEP(ARG(7)))
				{
					COPY(ARG(1), ARG(7));
					complex_vector_length(ARG(7));
					Flist(ARG(7), 1);
				}
				else
				{
					COPY(ARG(1), ARG(7));
					complex_array_dims(ARG(7));
				}
			}
			if(CL_SMVECP(ARG(3)))
			{
				LOAD_FIXNUM(ARG(9), AR_SIZE(GET_FORM(ARG(3))), ARG(8));
				Flist(ARG(8), 1);
			}
			else
			{
				COPY(ARG(3), ARG(8));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(9));	/* COMPLEX-VECTOR */
				rt_struct_typep(ARG(8));
				if(CL_TRUEP(ARG(8)))
				{
					COPY(ARG(3), ARG(8));
					complex_vector_length(ARG(8));
					Flist(ARG(8), 1);
				}
				else
				{
					COPY(ARG(3), ARG(8));
					complex_array_dims(ARG(8));
				}
			}
			Fequal(ARG(7));
			if(CL_TRUEP(ARG(7)))
			{
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&Kbit_op[2], ARG(7));	/* ~A must have the same dimensions as the other ~
                              bit-array parameters */
				COPY(ARG(3), ARG(8));
				Ferror(ARG(7), 2);
			}
			COPY(ARG(3), ARG(7));
		}
	}
	else
	{
		if(CL_SMVECP(ARG(1)))
		{
			LOAD_FIXNUM(ARG(8), AR_SIZE(GET_FORM(ARG(1))), ARG(7));
			Flist(ARG(7), 1);
		}
		else
		{
			COPY(ARG(1), ARG(7));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(8));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(7));
			if(CL_TRUEP(ARG(7)))
			{
				COPY(ARG(1), ARG(7));
				complex_vector_length(ARG(7));
				Flist(ARG(7), 1);
			}
			else
			{
				COPY(ARG(1), ARG(7));
				complex_array_dims(ARG(7));
			}
		}
		LOAD_SYMBOL(SYMBOL(Slisp, 16), ARG(8));	/* BIT */
		LOAD_NIL(ARG(9));
		LOAD_NIL(ARG(10));
		LOAD_NIL(ARG(11));
		LOAD_NIL(ARG(12));
		LOAD_NIL(ARG(13));
		LOAD_SMALLFIXNUM(0, ARG(14));
		LOAD_NIL(ARG(15));
		LOAD_NIL(ARG(16));
		make_array1(ARG(7));
	}
	rt_bitop(ARG(4));
	COPY(ARG(4), ARG(0));
}
