/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void bit_andc11(CL_FORM *base)
{
	LOAD_SMALLFIXNUM(6, ARG(3));
	COPY(ARG(0), ARG(4));
	COPY(ARG(1), ARG(5));
	COPY(ARG(2), ARG(6));
	bit_op(ARG(3));
	COPY(ARG(3), ARG(0));
}
