/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void butlast1(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	Flength(ARG(2));
	COPY(ARG(1), ARG(3));
	Fminus(ARG(2), 2);
	COPY(ARG(2), ARG(3));
	LOAD_SMALLFIXNUM(0, ARG(4));
	Fle(ARG(3), 2);
	if(CL_TRUEP(ARG(3)))
	{
		LOAD_NIL(ARG(0));
	}
	else
	{
		LOAD_SMALLFIXNUM(0, ARG(3));
		if(CL_LISTP(ARG(0)))
		{
			COPY(ARG(3), ARG(1));
			list_subseq(ARG(0));
		}
		else
		{
			COPY(ARG(3), ARG(1));
			vector_subseq(ARG(0));
		}
	}
}
