/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Cclose1, close1, 1);

extern CL_INIT XIclose1[];
extern CL_INIT XFclose1[];
CL_INIT Kclose1[] =
{
	MAKE_STRING(14, "already closed"),	/* 0 */
};

static void Z77_lambda(CL_FORM *base);
GEN_STATIC_GLOBAL_FUNARG(CZ77_lambda, Z77_lambda, 1);

void close1(CL_FORM *base)
{
	LOAD_GLOBFUN(&Cclose_err, ARG(1));
	LOAD_SMALLFIXNUM(2, ARG(2));
	COPY(ARG(0), ARG(3));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
	rt_struct_typep(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		LOAD_GLOBFUN(&Cclose_err, ARG(3));
		COPY(ARG(3), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(2)) + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(3));	/* NO_STRUCT */
		COPY(ARG(0), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
		Ferror(ARG(3), 3);
	}
	LOAD_GLOBFUN(&Cclose_err, ARG(1));
	LOAD_SMALLFIXNUM(3, ARG(2));
	COPY(ARG(0), ARG(3));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
	rt_struct_typep(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		LOAD_GLOBFUN(&Cclose_err, ARG(3));
		COPY(ARG(3), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(2)) + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(3));	/* NO_STRUCT */
		COPY(ARG(0), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
		Ferror(ARG(3), 3);
	}
	LOAD_GLOBFUN(&Cclose_err, ARG(1));
	LOAD_SMALLFIXNUM(4, ARG(2));
	COPY(ARG(0), ARG(3));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
	rt_struct_typep(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		LOAD_GLOBFUN(&Cclose_err, ARG(3));
		COPY(ARG(3), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(2)) + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(3));	/* NO_STRUCT */
		COPY(ARG(0), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
		Ferror(ARG(3), 3);
	}
	LOAD_GLOBFUN(&Cclose_err, ARG(1));
	LOAD_SMALLFIXNUM(6, ARG(2));
	COPY(ARG(0), ARG(3));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
	rt_struct_typep(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		LOAD_GLOBFUN(&Cclose_err, ARG(3));
		COPY(ARG(3), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(2)) + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(3));	/* NO_STRUCT */
		COPY(ARG(0), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
		Ferror(ARG(3), 3);
	}
	LOAD_GLOBFUN(&Cclose_err, ARG(1));
	LOAD_SMALLFIXNUM(7, ARG(2));
	COPY(ARG(0), ARG(3));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
	rt_struct_typep(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		LOAD_GLOBFUN(&Cclose_err, ARG(3));
		COPY(ARG(3), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(2)) + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(3));	/* NO_STRUCT */
		COPY(ARG(0), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
		Ferror(ARG(3), 3);
	}
	LOAD_GLOBFUN(&CZ77_lambda, ARG(1));
	LOAD_SMALLFIXNUM(9, ARG(2));
	COPY(ARG(0), ARG(3));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
	rt_struct_typep(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		COPY(ARG(1), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(2)) + 1));
		COPY(ARG(1), ARG(0));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(3));	/* NO_STRUCT */
		COPY(ARG(0), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
		Ferror(ARG(3), 3);
	}
}

static void Z77_lambda(CL_FORM *base)
{
	LOAD_SMSTR((CL_FORM *)&Kclose1[0], ARG(0));	/* already closed */
}
