/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

static void Z27_lambda(CL_FORM *base);

void count_if1(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(0), ARG(6));
	LOAD_NIL(ARG(6));
	COPY(ARG(1), ARG(7));
	COPY(ARG(2), ARG(8));
	{
		GEN_CLOSURE(array, ARG(9), 4, Z27_lambda, 2);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(9));
	}
	COPY(ARG(9), ARG(9));
	LOAD_NIL(ARG(10));
	COPY(ARG(3), ARG(11));
	COPY(ARG(4), ARG(12));
	COPY(ARG(5), ARG(13));
	count1(ARG(6));
	COPY(ARG(6), ARG(0));
}

static void Z27_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(3));
	COPY(ARG(2), ARG(4));
	Ffuncall(ARG(3), 2);
	COPY(ARG(3), ARG(0));
}
