/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XIdirectory1[];
extern CL_INIT XFdirectory1[];
CL_INIT Kdirectory1[] =
{
	MAKE_STRING(1, "/"),	/* 0 */
};

static void Z61_lambda(CL_FORM *base);
static void Z62_g647(CL_FORM *base);

void directory1(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(1), ARG(4));
	GEN_HEAPVAR(ARG(2), ARG(4));
	GEN_HEAPVAR(ARG(3), ARG(4));
	LOAD_NIL(ARG(4));
	GEN_HEAPVAR(ARG(4), ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 252), ARG(5));	/* NAME */
	LOAD_SYMBOL(SYMBOL(Slisp, 262), ARG(6));	/* WILD */
	LOAD_SYMBOL(SYMBOL(Slisp, 80), ARG(7));	/* TYPE */
	LOAD_SYMBOL(SYMBOL(Slisp, 262), ARG(8));	/* WILD */
	LOAD_SYMBOL(SYMBOL(Slisp, 253), ARG(9));	/* VERSION */
	LOAD_SYMBOL(SYMBOL(Slisp, 262), ARG(10));	/* WILD */
	Fmake_pathname(ARG(5), 6);
	COPY(ARG(0), ARG(6));
	COPY(ARG(5), ARG(7));
	LOAD_SYMBOL(SYMBOL(Slisp, 259), ARG(8));	/* NEWEST */
	merge_pathnames1(ARG(6));
	COPY(ARG(6), ARG(5));
	{
		GEN_CLOSURE(array, ARG(6), 5, Z62_g647, 1);
		COPY(ARG(4), &array[3]);
		COPY(ARG(1), &array[4]);
		LOAD_CLOSURE(array, ARG(6));
	}
	COPY(ARG(5), ARG(7));
	Fpathname(ARG(7));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(8));	/* T */
	COPY(ARG(6), ARG(9));
	Penumerate_matches(ARG(7));
	mv_count = 1;
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(5));	/* T */
	BIND_SPECIAL(SYMBOL(Slisp, 277), ARG(5));	/* *IGNORE-WILDCARDS* */
	{
		GEN_CLOSURE(array, ARG(6), 5, Z61_lambda, 1);
		COPY(ARG(3), &array[3]);
		COPY(ARG(2), &array[4]);
		LOAD_CLOSURE(array, ARG(6));
	}
	COPY(ARG(6), ARG(6));
	LOAD_GLOBFUN(&CFstringE, ARG(7));
	LOAD_NIL(ARG(8));
	LOAD_NIL(ARG(9));
	LOAD_SMALLFIXNUM(0, ARG(10));
	COPY(SYMVAL(Slisp, 0), ARG(11));	/* MOST-POSITIVE-FIXNUM */
	LOAD_NIL(ARG(12));
	LOAD_NIL(ARG(13));
	LOAD_NIL(ARG(14));
	LOAD_GLOBFUN(&CFstringE, ARG(15));
	LOAD_NIL(ARG(16));
	COPY(ARG(10), ARG(17));
	COPY(ARG(11), ARG(18));
	LOAD_NIL(ARG(19));
	remove_duplicates1(ARG(13));
	COPY(ARG(13), ARG(7));
	LOAD_GLOBFUN(&CFstringL, ARG(8));
	LOAD_NIL(ARG(9));
	if(CL_LISTP(ARG(7)))
	{
		LOAD_GLOBFUN(&CFstringL, ARG(8));
		LOAD_NIL(ARG(9));
		list_merge_sort(ARG(7));
	}
	else
	{
		COPY(ARG(7), ARG(10));
		LOAD_SMALLFIXNUM(0, ARG(11));
		COPY(ARG(7), ARG(12));
		Flength(ARG(12));
		LOAD_GLOBFUN(&CFstringL, ARG(13));
		LOAD_NIL(ARG(14));
		quick_sort(ARG(10));
		COPY(ARG(10), ARG(7));
	}
	Fmapcar(ARG(6), 2);
	COPY(ARG(6), ARG(0));
	RESTORE_SPECIAL;
}

static void Z61_lambda(CL_FORM *base)
{
	if(CL_TRUEP(INDIRECT(GET_FORM(ARG(0)) + 4)))
	{
		COPY(ARG(1), ARG(2));
		LOAD_NIL(ARG(3));
		unix_file_kind1(ARG(2));
	}	/* DIRECTORY */
	else
	{
		goto ELSE1;
	}
	if(CL_SYMBOLP(ARG(2)) && GET_SYMBOL(ARG(2)) == SYMBOL(Slisp, 251))
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 44), ARG(2));	/* STRING */
		COPY(ARG(1), ARG(3));
		LOAD_SMSTR((CL_FORM *)&Kdirectory1[0], ARG(4));	/* / */
		Fconcatenate(ARG(2), 3);
	}
	else
	{
		ELSE1:;
		COPY(ARG(1), ARG(2));
	}
	if(CL_TRUEP(INDIRECT(GET_FORM(ARG(0)) + 3)))
	{
		COPY(ARG(2), ARG(3));
		Fprobe_file(ARG(3));
		if(CL_TRUEP(ARG(3)))
		{
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[220], ARG(4));	/* The file ~S does not exist. */
			COPY(ARG(2), ARG(5));
			Fnamestring(ARG(5));
			Ferror(ARG(4), 2);
		}
		COPY(ARG(3), ARG(0));
	}
	else
	{
		COPY(ARG(2), ARG(3));
		Fpathname(ARG(3));
		COPY(ARG(3), ARG(0));
	}
}

static void Z62_g647(CL_FORM *base)
{
	if(CL_TRUEP(INDIRECT(GET_FORM(ARG(0)) + 4)))
	{
		goto THEN1;
	}
	else
	{
		LOAD_CHAR(ARG(2), '/', ARG(2));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(3));	/* T */
		LOAD_NIL(ARG(4));
		LOAD_NIL(ARG(5));
		LOAD_SMALLFIXNUM(0, ARG(6));
		COPY(SYMVAL(Slisp, 0), ARG(7));	/* MOST-POSITIVE-FIXNUM */
		LOAD_NIL(ARG(8));
		if(CL_LISTP(ARG(1)))
		{
			LOAD_CHAR(ARG(9), '/', ARG(9));
			COPY(ARG(1), ARG(10));
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(11));	/* T */
			LOAD_NIL(ARG(12));
			LOAD_NIL(ARG(13));
			COPY(ARG(6), ARG(14));
			COPY(ARG(7), ARG(15));
			LOAD_NIL(ARG(16));
			list_position(ARG(9));
			COPY(ARG(9), ARG(2));
		}
		else
		{
			LOAD_CHAR(ARG(9), '/', ARG(9));
			COPY(ARG(1), ARG(10));
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(11));	/* T */
			LOAD_NIL(ARG(12));
			LOAD_NIL(ARG(13));
			COPY(ARG(6), ARG(14));
			COPY(ARG(7), ARG(15));
			LOAD_NIL(ARG(16));
			vector_position(ARG(9));
			COPY(ARG(9), ARG(2));
		}
		if(CL_TRUEP(ARG(2)))
		{
			LOAD_NIL(ARG(3));
		}
		else
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(3));	/* T */
		}
		if(CL_TRUEP(ARG(3)))
		{
			goto THEN1;
		}
		else
		{
			COPY(ARG(2), ARG(4));
			F1plus(ARG(4));
			COPY(ARG(1), ARG(5));
			Flength(ARG(5));
			Fnumeql(ARG(4), 2);
			if(CL_TRUEP(ARG(4)))
			{
				goto THEN1;
			}
			else
			{
				COPY(ARG(1), ARG(5));
				COPY(ARG(2), ARG(6));
				F1plus(ARG(6));
				Fschar(ARG(5));
				LOAD_CHAR(ARG(6), '.', ARG(6));
				rt_charNE(ARG(5));
			}
		}
	}
	if(CL_TRUEP(ARG(5)))
	{
		THEN1:;
		ALLOC_CONS(ARG(3), ARG(1), INDIRECT(GET_FORM(ARG(0)) + 3), INDIRECT(GET_FORM(ARG(0)) + 3));
		COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(0));
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
