/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Facons(CL_FORM *base)
{
	ALLOC_CONS(ARG(5), ARG(0), ARG(1), ARG(3));
	ALLOC_CONS(ARG(5), ARG(3), ARG(2), ARG(0));
}
