/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Farray_rank(CL_FORM *base)
{
	LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(0), ARG(2));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(3));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(2));
	}
	if(CL_TRUEP(ARG(2)))
	{
		THEN1:;
		LOAD_SMALLFIXNUM(1, ARG(0));
	}
	else
	{
		complex_array_dims(ARG(0));
		Flength(ARG(0));
	}
}
