/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fcopy_tree(CL_FORM *base)
{
	if(CL_ATOMP(ARG(0)))
	{
	}
	else
	{
		COPY(GET_CAR(ARG(0)), ARG(1));
		Fcopy_tree(ARG(1));
		COPY(GET_CDR(ARG(0)), ARG(2));
		Fcopy_tree(ARG(2));
		ALLOC_CONS(ARG(3), ARG(1), ARG(2), ARG(0));
	}
}
