/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

static void Z164_f(CL_FORM *base);

void Fcopy_alist(CL_FORM *base)
{
	if(CL_TRUEP(ARG(0)))
	{
		if(CL_CONSP(ARG(0)))
		{
			Z164_f(ARG(0));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[48], ARG(1));	/* etypecase: the value ~a is not a legal value */
			COPY(ARG(0), ARG(2));
			Ferror(ARG(1), 2);
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}

static void Z164_f(CL_FORM *base)
{
	if(CL_ATOMP(ARG(0)))
	{
	}
	else
	{
		COPY(GET_CAR(ARG(0)), ARG(1));
		if(CL_ATOMP(ARG(1)))
		{
			COPY(GET_CAR(ARG(0)), ARG(1));
		}
		else
		{
			COPY(GET_CAR(ARG(0)), ARG(1));
			if(CL_CONSP(ARG(1)))
			{
				COPY(GET_CAR(ARG(1)), ARG(1));
			}
			else
			{
				if(CL_TRUEP(ARG(1)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(2));	/* ~a is not a list */
					COPY(ARG(1), ARG(3));
					Ferror(ARG(2), 2);
				}
				else
				{
					LOAD_NIL(ARG(1));
				}
			}
			COPY(GET_CAR(ARG(0)), ARG(2));
			if(CL_CONSP(ARG(2)))
			{
				COPY(GET_CDR(ARG(2)), ARG(2));
			}
			else
			{
				if(CL_TRUEP(ARG(2)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(3));	/* ~a is not a list */
					COPY(ARG(2), ARG(4));
					Ferror(ARG(3), 2);
				}
				else
				{
					LOAD_NIL(ARG(2));
				}
			}
			ALLOC_CONS(ARG(3), ARG(1), ARG(2), ARG(1));
		}
		COPY(GET_CDR(ARG(0)), ARG(2));
		Z164_f(ARG(2));
		ALLOC_CONS(ARG(3), ARG(1), ARG(2), ARG(0));
	}
}
