/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

static void Z163_f(CL_FORM *base);

void Fcopy_list(CL_FORM *base)
{
	if(CL_TRUEP(ARG(0)))
	{
		if(CL_ATOMP(ARG(0)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[50], ARG(1));	/* ~a is not a list */
			COPY(ARG(0), ARG(2));
			Ferror(ARG(1), 2);
		}
		else
		{
			COPY(GET_CAR(ARG(0)), ARG(1));
			COPY(GET_CDR(ARG(0)), ARG(2));
			Z163_f(ARG(2));
			ALLOC_CONS(ARG(3), ARG(1), ARG(2), ARG(0));
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}

static void Z163_f(CL_FORM *base)
{
	if(CL_ATOMP(ARG(0)))
	{
	}
	else
	{
		COPY(GET_CAR(ARG(0)), ARG(1));
		COPY(GET_CDR(ARG(0)), ARG(2));
		Z163_f(ARG(2));
		ALLOC_CONS(ARG(3), ARG(1), ARG(2), ARG(0));
	}
}
