/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fdirectory(CL_FORM *base, int nargs)
{
	BOOL supl_flags[3];
	static CL_FORM * keylist[] =
	{
		SYMBOL(Slisp, 285),	/* ALL */
		SYMBOL(Slisp, 286),	/* CHECK-FOR-SUBDIRS */
		SYMBOL(Slisp, 287),	/* FOLLOW-LINKS */
	};
	keysort(ARG(1), nargs - 1, 3, keylist, supl_flags, FALSE);
	if(NOT(supl_flags[0]))
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(1));	/* T */
	}
	if(NOT(supl_flags[1]))
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(2));	/* T */
	}
	if(NOT(supl_flags[2]))
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(3));	/* T */
	}
	directory1(ARG(0));
}
