/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Felt(CL_FORM *base)
{
	if(CL_LISTP(ARG(0)))
	{
		COPY(ARG(1), ARG(2));
		COPY(ARG(0), ARG(3));
		Fnth(ARG(2));
		COPY(ARG(2), ARG(0));
	}
	else
	{
		Frow_major_aref(ARG(0));
	}
}
