/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CFequalp, Fequalp, 2);

void Fequalp(CL_FORM *base)
{
	M1_1:;
	if(CL_CHARP(ARG(0)))
	{
		if(CL_CHARP(ARG(1)))
		{
			COPY(ARG(0), ARG(2));
			rt_char_upcase(ARG(2));
			rt_char_code(ARG(2));
			COPY(ARG(1), ARG(3));
			rt_char_upcase(ARG(3));
			rt_char_code(ARG(3));
			Fnumeql(ARG(2), 2);
			COPY(ARG(2), ARG(0));
		}
		else
		{
			LOAD_NIL(ARG(0));
		}
	}
	else
	{
		if(CL_NUMBERP(ARG(0)))
		{
			if(CL_NUMBERP(ARG(1)))
			{
				Fnumeql(ARG(0), 2);
			}
			else
			{
				LOAD_NIL(ARG(0));
			}
		}
		else
		{
			if(CL_CONSP(ARG(0)))
			{
				if(CL_CONSP(ARG(1)))
				{
					COPY(GET_CAR(ARG(0)), ARG(2));
					COPY(GET_CAR(ARG(1)), ARG(3));
					Fequalp(ARG(2));
					if(CL_TRUEP(ARG(2)))
					{
						COPY(GET_CDR(ARG(0)), ARG(2));
						COPY(GET_CDR(ARG(1)), ARG(3));
						COPY(ARG(2), ARG(0));
						COPY(ARG(3), ARG(1));
						goto M1_1;
					}
					else
					{
						LOAD_NIL(ARG(0));
					}
				}
				else
				{
					LOAD_NIL(ARG(0));
				}
			}
			else
			{
				LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(2));
				if(CL_TRUEP(ARG(2)))
				{
					goto THEN1;
				}
				else
				{
					COPY(ARG(0), ARG(3));
					LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(4));	/* COMPLEX-VECTOR */
					rt_struct_typep(ARG(3));
				}
				if(CL_TRUEP(ARG(3)))
				{
					THEN1:;
					LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(2));
					if(CL_TRUEP(ARG(2)))
					{
						goto THEN2;
					}
					else
					{
						COPY(ARG(1), ARG(3));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(4));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(3));
					}
					if(CL_TRUEP(ARG(3)))
					{
						THEN2:;
						COPY(ARG(0), ARG(2));
						Flength(ARG(2));
						COPY(ARG(1), ARG(3));
						Flength(ARG(3));
						if(EQL(ARG(2), ARG(3)))
						{
							COPY(ARG(0), ARG(2));
							Flength(ARG(2));
							LOAD_SMALLFIXNUM(0, ARG(3));
							M2_1:;
							COPY(ARG(3), ARG(4));
							COPY(ARG(2), ARG(5));
							Fge(ARG(4), 2);
							if(CL_TRUEP(ARG(4)))
							{
								LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
								goto RETURN2;
							}
							LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(4));
							if(CL_TRUEP(ARG(4)))
							{
								goto THEN3;
							}
							else
							{
								COPY(ARG(0), ARG(5));
								LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(6));	/* COMPLEX-VECTOR */
								rt_struct_typep(ARG(5));
							}
							if(CL_TRUEP(ARG(5)))
							{
								THEN3:;
							}
							else
							{
								COPY(SYMVAL(Slisp, 58), ARG(4));	/* WRONG_TYPE */
								COPY(ARG(0), ARG(5));
								LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(6));	/* VECTOR */
								Ferror(ARG(4), 3);
							}
							COPY(ARG(0), ARG(4));
							COPY(ARG(3), ARG(5));
							Frow_major_aref(ARG(4));
							LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(5));
							if(CL_TRUEP(ARG(5)))
							{
								goto THEN4;
							}
							else
							{
								COPY(ARG(1), ARG(6));
								LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(7));	/* COMPLEX-VECTOR */
								rt_struct_typep(ARG(6));
							}
							if(CL_TRUEP(ARG(6)))
							{
								THEN4:;
							}
							else
							{
								COPY(SYMVAL(Slisp, 58), ARG(5));	/* WRONG_TYPE */
								COPY(ARG(1), ARG(6));
								LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(7));	/* VECTOR */
								Ferror(ARG(5), 3);
							}
							COPY(ARG(1), ARG(5));
							COPY(ARG(3), ARG(6));
							Frow_major_aref(ARG(5));
							Fequalp(ARG(4));
							if(CL_TRUEP(ARG(4)))
							{
							}
							else
							{
								LOAD_NIL(ARG(0));
								goto RETURN2;
							}
							F1plus(ARG(3));
							goto M2_1;
							RETURN2:;
						}
						else
						{
							LOAD_NIL(ARG(0));
						}
					}
					else
					{
						LOAD_NIL(ARG(0));
					}
				}
				else
				{
					LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(2));
					if(CL_TRUEP(ARG(2)))
					{
						goto THEN5;
					}
					else
					{
						COPY(ARG(0), ARG(3));
						LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(4));	/* COMPLEX-BASE-ARRAY */
						rt_struct_typep(ARG(3));
					}
					if(CL_TRUEP(ARG(3)))
					{
						THEN5:;
						LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(2));
						if(CL_TRUEP(ARG(2)))
						{
							goto THEN6;
						}
						else
						{
							COPY(ARG(1), ARG(3));
							LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(4));	/* COMPLEX-BASE-ARRAY */
							rt_struct_typep(ARG(3));
						}
						if(CL_TRUEP(ARG(3)))
						{
							THEN6:;
							COPY(ARG(0), ARG(2));
							Farray_rank(ARG(2));
							COPY(ARG(1), ARG(3));
							Farray_rank(ARG(3));
							if(EQL(ARG(2), ARG(3)))
							{
								COPY(ARG(0), ARG(2));
								Farray_rank(ARG(2));
								LOAD_SMALLFIXNUM(0, ARG(3));
								M3_1:;
								COPY(ARG(3), ARG(4));
								COPY(ARG(2), ARG(5));
								Fge(ARG(4), 2);
								if(CL_TRUEP(ARG(4)))
								{
									bool_result = TRUE;
									goto RETURN3;
								}
								COPY(ARG(0), ARG(4));
								COPY(ARG(3), ARG(5));
								Farray_dimension(ARG(4));
								COPY(ARG(1), ARG(5));
								COPY(ARG(3), ARG(6));
								Farray_dimension(ARG(5));
								if(EQL(ARG(4), ARG(5)))
								{
								}
								else
								{
									bool_result = FALSE;
									goto RETURN3;
								}
								F1plus(ARG(3));
								goto M3_1;
								RETURN3:;
								if(bool_result)
								{
									COPY(ARG(0), ARG(2));
									Farray_total_size(ARG(2));
									LOAD_SMALLFIXNUM(0, ARG(3));
									M4_1:;
									COPY(ARG(3), ARG(4));
									COPY(ARG(2), ARG(5));
									Fge(ARG(4), 2);
									if(CL_TRUEP(ARG(4)))
									{
										LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
										goto RETURN4;
									}
									COPY(ARG(0), ARG(4));
									COPY(ARG(3), ARG(5));
									Frow_major_aref(ARG(4));
									COPY(ARG(1), ARG(5));
									COPY(ARG(3), ARG(6));
									Frow_major_aref(ARG(5));
									Fequalp(ARG(4));
									if(CL_TRUEP(ARG(4)))
									{
									}
									else
									{
										LOAD_NIL(ARG(0));
										goto RETURN4;
									}
									F1plus(ARG(3));
									goto M4_1;
									RETURN4:;
								}
								else
								{
									LOAD_NIL(ARG(0));
								}
							}
							else
							{
								LOAD_NIL(ARG(0));
							}
						}
						else
						{
							LOAD_NIL(ARG(0));
						}
					}
					else
					{
						if(CL_STRUCTP(ARG(0)))
						{
							if(CL_STRUCTP(ARG(1)))
							{
								COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), -1 + 1), ARG(2));
								COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), -1 + 1), ARG(3));
								if(EQ(ARG(2), ARG(3)))
								{
									COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), -1 + 1), ARG(2));
									LOAD_FIXNUM(ARG(4), AR_SIZE(GET_FORM(ARG(0))), ARG(3));
									LOAD_SMALLFIXNUM(0, ARG(4));
									M5_1:;
									COPY(ARG(4), ARG(5));
									COPY(ARG(3), ARG(6));
									Fge(ARG(5), 2);
									if(CL_TRUEP(ARG(5)))
									{
										LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
										goto RETURN5;
									}
									COPY(ARG(0), ARG(5));
									COPY(ARG(2), ARG(6));
									rt_struct_typep(ARG(5));
									if(CL_TRUEP(ARG(5)))
									{
										COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(4)) + 1), ARG(5));
									}
									else
									{
										COPY(SYMVAL(Slisp, 342), ARG(5));	/* NO_STRUCT */
										COPY(ARG(0), ARG(6));
										COPY(ARG(2), ARG(7));
										Ferror(ARG(5), 3);
									}
									COPY(ARG(1), ARG(6));
									COPY(ARG(2), ARG(7));
									rt_struct_typep(ARG(6));
									if(CL_TRUEP(ARG(6)))
									{
										COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), GET_FIXNUM(ARG(4)) + 1), ARG(6));
									}
									else
									{
										COPY(SYMVAL(Slisp, 342), ARG(6));	/* NO_STRUCT */
										COPY(ARG(1), ARG(7));
										COPY(ARG(2), ARG(8));
										Ferror(ARG(6), 3);
									}
									Fequalp(ARG(5));
									if(CL_TRUEP(ARG(5)))
									{
									}
									else
									{
										LOAD_NIL(ARG(0));
										goto RETURN5;
									}
									F1plus(ARG(4));
									goto M5_1;
									RETURN5:;
								}
								else
								{
									LOAD_NIL(ARG(0));
								}
							}
							else
							{
								LOAD_NIL(ARG(0));
							}
						}
						else
						{
							LOAD_BOOL(EQ(ARG(0), ARG(1)), ARG(0));
						}
					}
				}
			}
		}
	}
	goto RETURN1;
	RETURN1:;
}
