/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Ferror(CL_FORM *base, int nargs)
{
	Flist(ARG(1), nargs - 1);
	COPY(SYMVAL(Slisp, 504), ARG(2));	/* *ERROR-PRINT-LENGTH* */
	BIND_SPECIAL(SYMBOL(Slisp, 474), ARG(2));	/* *PRINT-LENGTH* */
	COPY(SYMVAL(Slisp, 505), ARG(3));	/* *ERROR-PRINT-LEVEL* */
	BIND_SPECIAL(SYMBOL(Slisp, 475), ARG(3));	/* *PRINT-LEVEL* */
	COPY(SYMVAL(Slisp, 62), ARG(4));	/* *ERROR-OUTPUT* */
	LOAD_SMSTR((CL_FORM *)&KClisp[54], ARG(5));	/* ~&Error: ~?~% */
	COPY(ARG(0), ARG(6));
	COPY(ARG(1), ARG(7));
	Fformat(ARG(4), 4);
	mv_count = 1;
	RESTORE_SPECIAL;
	RESTORE_SPECIAL;
	LOAD_SMALLFIXNUM(-1, ARG(2));
	{
		int nargs;
		nargs = 1;
		{
			CL_FORM *rest_0;
			CL_FORM *local;
			rest_0 = ARG(2);
			local = ARG(nargs + 2);
			{
				GEN_STATIC_GLOBAL_FUNARG(extern_closure, rt_throw, -2);
				LOAD_GLOBFUN(&extern_closure, LOCAL(0));
			}
			LOAD_SYMBOL(SYMBOL(Slisp, 506), LOCAL(1));	/* ERROR-CATCHER */
			REST_APPLY(LOCAL(0), 2, rest_0);
		}
	}
}
