/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Ffile_length(CL_FORM *base)
{
	stream_length(ARG(0));
	Ffuncall(ARG(0), 1);
}
