/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Ffill(CL_FORM *base, int nargs)
{
	BOOL supl_flags[2];
	static CL_FORM * keylist[] =
	{
		SYMBOL(Slisp, 229),	/* START */
		SYMBOL(Slisp, 230),	/* END */
	};
	keysort(ARG(2), nargs - 2, 2, keylist, supl_flags, FALSE);
	if(NOT(supl_flags[0]))
	{
		LOAD_SMALLFIXNUM(0, ARG(2));
	}
	if(NOT(supl_flags[1]))
	{
		COPY(SYMVAL(Slisp, 0), ARG(3));	/* MOST-POSITIVE-FIXNUM */
	}
	fill1(ARG(0));
}
