/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Ffloat_sign(CL_FORM *base, int nargs)
{
	MEM_UP_MOVE(ARG(0 + nargs), ARG(1), 1);
	LOAD_NIL(ARG(1));
	nargs = nargs + 1;
	switch(nargs)
	{
		default:
		case 3:
		LOAD_T(ARG(1));
		case 2:
	}
	switch(nargs)
	{
		case 2:
		GEN_FLOAT(ARG(2), 1.0, ARG(2));
		case 3:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	float_sign1(ARG(0));
}
