/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XIfile_name1[];
extern CL_INIT XFfile_name1[];
CL_INIT Kfile_name1[] =
{
	MAKE_CONS,	/* 0 CONS(0) */
	MAKE_SYMREF(SYMBOL(Slisp, 90)),	/* FILE-INPUT */
	MAKE_CONSREF(&Kfile_name1[3]),
	MAKE_CONS,	/* CONS(3) */
	MAKE_SYMREF(SYMBOL(Slisp, 91)),	/* FILE-OUTPUT */
	MAKE_CONSREF(&Kfile_name1[6]),
	MAKE_CONS,	/* CONS(6) */
	MAKE_SYMREF(SYMBOL(Slisp, 92)),	/* FILE-IO */
	MAKE_NIL,
	MAKE_STRING(46, "there is no filename associated with stream ~a"),	/* 9 */
};

void file_name1(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(3));	/* STREAM */
	rt_struct_typep(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), 0 + 1), ARG(2));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(2));	/* NO_STRUCT */
		COPY(ARG(0), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
		Ferror(ARG(2), 3);
	}
	LOAD_CONS((CL_FORM *)&Kfile_name1[0], ARG(3));
	COPY(ARG(2), ARG(4));
	COPY(ARG(3), ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	LOAD_NIL(ARG(8));
	member1(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kfile_name1[9], ARG(2));	/* there is no filename associated with stream ~a */
		COPY(ARG(0), ARG(3));
		Ferror(ARG(2), 2);
	}
	if(CL_TRUEP(ARG(1)))
	{
		LOAD_SMALLFIXNUM(1, ARG(2));
		COPY(ARG(0), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
		rt_struct_typep(ARG(3));
		if(CL_TRUEP(ARG(3)))
		{
			COPY(ARG(1), OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(2)) + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(3));	/* NO_STRUCT */
			COPY(ARG(0), ARG(4));
			LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
			Ferror(ARG(3), 3);
		}
	}
	COPY(ARG(0), ARG(2));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(3));	/* STREAM */
	rt_struct_typep(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), 1 + 1), ARG(0));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(2));	/* NO_STRUCT */
		COPY(ARG(0), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
		Ferror(ARG(2), 3);
	}
}
