/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void fill1(CL_FORM *base)
{
	COPY(ARG(0), ARG(4));
	Flength(ARG(4));
	COPY(ARG(3), ARG(5));
	COPY(ARG(4), ARG(6));
	Fgt(ARG(5), 2);
	if(CL_TRUEP(ARG(5)))
	{
		COPY(ARG(4), ARG(3));
	}
	COPY(ARG(2), ARG(5));
	M1_1:;
	COPY(ARG(5), ARG(6));
	COPY(ARG(3), ARG(7));
	Fge(ARG(6), 2);
	if(CL_TRUEP(ARG(6)))
	{
		goto RETURN1;
	}
	COPY(ARG(1), ARG(6));
	COPY(ARG(0), ARG(7));
	COPY(ARG(5), ARG(8));
	Fset_elt(ARG(6));
	F1plus(ARG(5));
	goto M1_1;
	RETURN1:;
}
