/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void find_symbol1(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	string_to_simple_string(ARG(2));
	rt_sxhash_string(ARG(2));
	COPY(ARG(2), ARG(3));
	COPY(SYMVAL(Slisp, 372), ARG(4));	/* PACKAGE-HASHTAB-SIZE */
	LOAD_SMALLFIXNUM(0, ARG(5));
	rt_convert_to_int(ARG(3));
	COPY(&mv_buf[0], ARG(4));
	mv_count = 1;
	{
		COPY(ARG(4), ARG(2));
	}
	COPY(ARG(1), ARG(3));
	if(CL_SYMBOLP(ARG(3)) || CL_NILP(ARG(3)))
	{
		COPY(ARG(3), ARG(4));
		if(CL_SYMBOLP(ARG(4)))
		{
			GET_SYM_NAME(ARG(6), ARG(4), ARG(3));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(3));	/* NIL */
		}
	}
	COPY(ARG(3), ARG(4));
	Fstringp(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		Ffind_package(ARG(3));
	}
	COPY(ARG(3), ARG(1));
	LOAD_NIL(ARG(3));
	COPY(ARG(1), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(5));	/* PACKAGE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 3 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(4));	/* NO_STRUCT */
		COPY(ARG(1), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(6));	/* PACKAGE */
		Ferror(ARG(4), 3);
	}
	COPY(ARG(2), ARG(5));
	Fsvref(ARG(4));
	M1_1:;
	if(CL_ATOMP(ARG(4)))
	{
		LOAD_NIL(ARG(3));
		goto RETURN2;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CAR(ARG(5)), ARG(3));
	if(CL_SYMBOLP(ARG(3)))
	{
		GET_SYM_NAME(ARG(6), ARG(3), ARG(5));
	}
	else
	{
		if(CL_TRUEP(ARG(3)))
		{
			COPY(SYMVAL(Slisp, 679), ARG(5));	/* SYM_EXPECTED */
			COPY(ARG(3), ARG(6));
			Ferror(ARG(5), 2);
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(5));	/* NIL */
		}
	}
	LOAD_SMALLFIXNUM(0, ARG(6));
	LOAD_SMALLFIXNUM(0, ARG(7));
	COPY(ARG(0), ARG(8));
	COPY(ARG(5), ARG(9));
	COPY(ARG(6), ARG(10));
	LOAD_NIL(ARG(11));
	COPY(ARG(7), ARG(12));
	LOAD_NIL(ARG(13));
	stringE1(ARG(8));
	if(CL_TRUEP(ARG(8)))
	{
		COPY(ARG(3), ARG(0));
		LOAD_SYMBOL(SYMBOL(Slisp, 375), ARG(1));	/* EXTERNAL */
		COPY(ARG(1), &mv_buf[0]);
		mv_count = 2;
		goto RETURN1;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CDR(ARG(5)), ARG(4));
	goto M1_1;
	RETURN2:;
	LOAD_NIL(ARG(3));
	COPY(ARG(1), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(5));	/* PACKAGE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 2 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(4));	/* NO_STRUCT */
		COPY(ARG(1), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(6));	/* PACKAGE */
		Ferror(ARG(4), 3);
	}
	COPY(ARG(2), ARG(5));
	Fsvref(ARG(4));
	M2_1:;
	if(CL_ATOMP(ARG(4)))
	{
		LOAD_NIL(ARG(3));
		goto RETURN3;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CAR(ARG(5)), ARG(3));
	if(CL_SYMBOLP(ARG(3)))
	{
		GET_SYM_NAME(ARG(6), ARG(3), ARG(5));
	}
	else
	{
		if(CL_TRUEP(ARG(3)))
		{
			COPY(SYMVAL(Slisp, 679), ARG(5));	/* SYM_EXPECTED */
			COPY(ARG(3), ARG(6));
			Ferror(ARG(5), 2);
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(5));	/* NIL */
		}
	}
	LOAD_SMALLFIXNUM(0, ARG(6));
	LOAD_SMALLFIXNUM(0, ARG(7));
	COPY(ARG(0), ARG(8));
	COPY(ARG(5), ARG(9));
	COPY(ARG(6), ARG(10));
	LOAD_NIL(ARG(11));
	COPY(ARG(7), ARG(12));
	LOAD_NIL(ARG(13));
	stringE1(ARG(8));
	if(CL_TRUEP(ARG(8)))
	{
		COPY(ARG(3), ARG(0));
		LOAD_SYMBOL(SYMBOL(Slisp, 374), ARG(1));	/* INTERNAL */
		COPY(ARG(1), &mv_buf[0]);
		mv_count = 2;
		goto RETURN1;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CDR(ARG(5)), ARG(4));
	goto M2_1;
	RETURN3:;
	LOAD_NIL(ARG(3));
	COPY(ARG(1), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(5));	/* PACKAGE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 5 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(4));	/* NO_STRUCT */
		COPY(ARG(1), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(6));	/* PACKAGE */
		Ferror(ARG(4), 3);
	}
	M3_1:;
	if(CL_ATOMP(ARG(4)))
	{
		LOAD_NIL(ARG(3));
		goto RETURN4;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CAR(ARG(5)), ARG(3));
	LOAD_NIL(ARG(5));
	COPY(ARG(3), ARG(6));
	LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(7));	/* PACKAGE */
	rt_struct_typep(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 3 + 1), ARG(6));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(6));	/* NO_STRUCT */
		COPY(ARG(3), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(8));	/* PACKAGE */
		Ferror(ARG(6), 3);
	}
	COPY(ARG(2), ARG(7));
	Fsvref(ARG(6));
	M4_1:;
	if(CL_ATOMP(ARG(6)))
	{
		LOAD_NIL(ARG(5));
		goto RETURN5;
	}
	COPY(ARG(6), ARG(7));
	COPY(GET_CAR(ARG(7)), ARG(5));
	if(CL_SYMBOLP(ARG(5)))
	{
		GET_SYM_NAME(ARG(8), ARG(5), ARG(7));
	}
	else
	{
		if(CL_TRUEP(ARG(5)))
		{
			COPY(SYMVAL(Slisp, 679), ARG(7));	/* SYM_EXPECTED */
			COPY(ARG(5), ARG(8));
			Ferror(ARG(7), 2);
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(7));	/* NIL */
		}
	}
	LOAD_SMALLFIXNUM(0, ARG(8));
	LOAD_SMALLFIXNUM(0, ARG(9));
	COPY(ARG(0), ARG(10));
	COPY(ARG(7), ARG(11));
	COPY(ARG(8), ARG(12));
	LOAD_NIL(ARG(13));
	COPY(ARG(9), ARG(14));
	LOAD_NIL(ARG(15));
	stringE1(ARG(10));
	if(CL_TRUEP(ARG(10)))
	{
		COPY(ARG(5), ARG(0));
		LOAD_SYMBOL(SYMBOL(Slisp, 383), ARG(1));	/* INHERITED */
		COPY(ARG(1), &mv_buf[0]);
		mv_count = 2;
		goto RETURN1;
	}
	COPY(ARG(6), ARG(7));
	COPY(GET_CDR(ARG(7)), ARG(6));
	goto M4_1;
	RETURN5:;
	COPY(ARG(4), ARG(5));
	COPY(GET_CDR(ARG(5)), ARG(4));
	goto M3_1;
	RETURN4:;
	LOAD_NIL(ARG(0));
	LOAD_NIL(ARG(1));
	COPY(ARG(1), &mv_buf[0]);
	mv_count = 2;
	RETURN1:;
}
