/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Flognand(CL_FORM *base)
{
	Flogand(ARG(0), 2);
	Flognot(ARG(0));
}
