/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Flogorc2(CL_FORM *base)
{
	Flognot(ARG(1));
	Flogior(ARG(0), 2);
}
