/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Flognot(CL_FORM *base)
{
	LOAD_FIXNUM(ARG(2),  ~ GET_FIXNUM(ARG(0)), ARG(0));
}
