/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fmake_symbol(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	string_to_simple_string(ARG(1));
	rt_make_symbol(ARG(1));
	LOAD_NIL(ARG(2));
	COPY(ARG(2), SYM_PLIST(ARG(1)));
	LOAD_NIL(ARG(2));
	COPY(ARG(2), SYM_PACKAGE(ARG(1)));
	COPY(ARG(1), ARG(0));
	Fmakunbound(ARG(0));
}
