/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fname_char(CL_FORM *base)
{
	Fstring(ARG(0));
	COPY(ARG(0), ARG(1));
	LOAD_SMSTR((CL_FORM *)&KClisp[144], ARG(2));	/* Space */
	LOAD_SMALLFIXNUM(0, ARG(3));
	LOAD_NIL(ARG(4));
	LOAD_SMALLFIXNUM(0, ARG(5));
	LOAD_NIL(ARG(6));
	string_equal1(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		LOAD_CHAR(ARG(1), ' ', ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(1));
		LOAD_SMSTR((CL_FORM *)&KClisp[142], ARG(2));	/* Newline */
		LOAD_SMALLFIXNUM(0, ARG(3));
		LOAD_NIL(ARG(4));
		LOAD_SMALLFIXNUM(0, ARG(5));
		LOAD_NIL(ARG(6));
		string_equal1(ARG(1));
		if(CL_TRUEP(ARG(1)))
		{
			LOAD_CHAR(ARG(1), '\n', ARG(0));
		}
		else
		{
			COPY(ARG(0), ARG(1));
			LOAD_SMSTR((CL_FORM *)&KClisp[140], ARG(2));	/* Backspace */
			LOAD_SMALLFIXNUM(0, ARG(3));
			LOAD_NIL(ARG(4));
			LOAD_SMALLFIXNUM(0, ARG(5));
			LOAD_NIL(ARG(6));
			string_equal1(ARG(1));
			if(CL_TRUEP(ARG(1)))
			{
				LOAD_CHAR(ARG(1), '\b', ARG(0));
			}
			else
			{
				COPY(ARG(0), ARG(1));
				LOAD_SMSTR((CL_FORM *)&KClisp[138], ARG(2));	/* Tab */
				LOAD_SMALLFIXNUM(0, ARG(3));
				LOAD_NIL(ARG(4));
				LOAD_SMALLFIXNUM(0, ARG(5));
				LOAD_NIL(ARG(6));
				string_equal1(ARG(1));
				if(CL_TRUEP(ARG(1)))
				{
					LOAD_CHAR(ARG(1), '\t', ARG(0));
				}
				else
				{
					COPY(ARG(0), ARG(1));
					LOAD_SMSTR((CL_FORM *)&KClisp[136], ARG(2));	/* Linefeed */
					LOAD_SMALLFIXNUM(0, ARG(3));
					LOAD_NIL(ARG(4));
					LOAD_SMALLFIXNUM(0, ARG(5));
					LOAD_NIL(ARG(6));
					string_equal1(ARG(1));
					if(CL_TRUEP(ARG(1)))
					{
						LOAD_CHAR(ARG(1), '\n', ARG(0));
					}
					else
					{
						COPY(ARG(0), ARG(1));
						LOAD_SMSTR((CL_FORM *)&KClisp[134], ARG(2));	/* Page */
						LOAD_SMALLFIXNUM(0, ARG(3));
						LOAD_NIL(ARG(4));
						LOAD_SMALLFIXNUM(0, ARG(5));
						LOAD_NIL(ARG(6));
						string_equal1(ARG(1));
						if(CL_TRUEP(ARG(1)))
						{
							LOAD_CHAR(ARG(1), '\f', ARG(0));
						}
						else
						{
							COPY(ARG(0), ARG(1));
							LOAD_SMSTR((CL_FORM *)&KClisp[132], ARG(2));	/* Return */
							LOAD_SMALLFIXNUM(0, ARG(3));
							LOAD_NIL(ARG(4));
							LOAD_SMALLFIXNUM(0, ARG(5));
							LOAD_NIL(ARG(6));
							string_equal1(ARG(1));
							if(CL_TRUEP(ARG(1)))
							{
								LOAD_CHAR(ARG(1), '\r', ARG(0));
							}
							else
							{
								COPY(ARG(0), ARG(1));
								LOAD_SMSTR((CL_FORM *)&KClisp[130], ARG(2));	/* Rubout */
								LOAD_SMALLFIXNUM(0, ARG(3));
								LOAD_NIL(ARG(4));
								LOAD_SMALLFIXNUM(0, ARG(5));
								LOAD_NIL(ARG(6));
								string_equal1(ARG(1));
								if(CL_TRUEP(ARG(1)))
								{
									LOAD_CHAR(ARG(1), '\177', ARG(0));
								}
								else
								{
									LOAD_NIL(ARG(0));
								}
							}
						}
					}
				}
			}
		}
	}
}
