/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fnreverse(CL_FORM *base)
{
	if(CL_TRUEP(ARG(0)))
	{
		if(CL_CONSP(ARG(0)))
		{
			list_nreverse(ARG(0));
		}
		else
		{
			vector_nreverse(ARG(0));
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
