/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void format2(CL_FORM *base, int nargs)
{
	switch(nargs)
	{
		case 3:
		LOAD_SMALLFIXNUM(0, ARG(3));
		case 4:
		LOAD_NIL(ARG(4));
		case 5:
		LOAD_NIL(ARG(5));
		case 6:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	LOAD_NIL(ARG(4));
	LOAD_NIL(ARG(5));
	format21(ARG(0));
}
