/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fprobe_file(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(2));	/* T */
	unix_namestring1(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		COPY(ARG(1), ARG(2));
		LOAD_NIL(ARG(3));
		unix_file_kind1(ARG(2));
	}
	else
	{
		goto ELSE1;
	}
	if(CL_TRUEP(ARG(2)))
	{
		COPY(ARG(1), ARG(2));
		Flength(ARG(2));
		Fplusp(ARG(2));
		if(CL_TRUEP(ARG(2)))
		{
			COPY(ARG(1), ARG(2));
			LOAD_SMALLFIXNUM(0, ARG(3));
			Fschar(ARG(2));
			LOAD_CHAR(ARG(3), '/', ARG(3));
			rt_charE(ARG(2));
		}
		else
		{
			goto ELSE2;
		}
		if(CL_TRUEP(ARG(2)))
		{
			COPY(ARG(1), ARG(2));
		}
		else
		{
			ELSE2:;
			unix_current_directory(ARG(2));
			COPY(&mv_buf[0], ARG(3));
			{
				int nargs;
				nargs = 2;
				mv_count = 1;
				{
					switch(nargs)
					{
						case 0:
						LOAD_NIL(ARG(2));
						case 1:
						LOAD_NIL(ARG(3));
						nargs = 2;
					}
					if(CL_TRUEP(ARG(2)))
					{
						LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(2));	/* SIMPLE-STRING */
						LOAD_SMSTR((CL_FORM *)&KClisp[82], ARG(4));	/* / */
						COPY(ARG(1), ARG(5));
						Fconcatenate(ARG(2), 4);
					}
					else
					{
						COPY(ARG(1), ARG(2));
					}
				}
			}
		}
		COPY(ARG(2), ARG(3));
		Flength(ARG(3));
		COPY(ARG(2), ARG(4));
		COPY(ARG(3), ARG(5));
		Fzerop(ARG(5));
		if(CL_TRUEP(ARG(5)))
		{
		}
		else
		{
			LOAD_FIXNUM(ARG(5), 1024, ARG(5));
			LOAD_SMALLFIXNUM(0, ARG(6));
			LOAD_SMALLFIXNUM(0, ARG(7));
			COPY(ARG(6), ARG(8));
			COPY(SYMVAL(Slisp, 12), ARG(9));	/* CHAR-CODE-LIMIT */
			Fle(ARG(7), 3);
			if(CL_TRUEP(ARG(7)))
			{
				rt_code_char(ARG(6));
			}
			else
			{
				LOAD_NIL(ARG(6));
			}
			make_string1(ARG(5));
			LOAD_SMALLFIXNUM(0, ARG(6));
			LOAD_SMALLFIXNUM(0, ARG(7));
			M1_1:;
			LOAD_CHAR(ARG(8), '/', ARG(8));
			LOAD_NIL(ARG(9));
			LOAD_NIL(ARG(10));
			LOAD_NIL(ARG(11));
			COPY(SYMVAL(Slisp, 0), ARG(12));	/* MOST-POSITIVE-FIXNUM */
			LOAD_NIL(ARG(13));
			if(CL_LISTP(ARG(4)))
			{
				LOAD_CHAR(ARG(14), '/', ARG(14));
				COPY(ARG(4), ARG(15));
				LOAD_NIL(ARG(16));
				LOAD_NIL(ARG(17));
				LOAD_NIL(ARG(18));
				COPY(ARG(7), ARG(19));
				COPY(ARG(12), ARG(20));
				LOAD_NIL(ARG(21));
				list_position(ARG(14));
				COPY(ARG(14), ARG(8));
			}
			else
			{
				LOAD_CHAR(ARG(14), '/', ARG(14));
				COPY(ARG(4), ARG(15));
				LOAD_NIL(ARG(16));
				LOAD_NIL(ARG(17));
				LOAD_NIL(ARG(18));
				COPY(ARG(7), ARG(19));
				COPY(ARG(12), ARG(20));
				LOAD_NIL(ARG(21));
				vector_position(ARG(14));
				COPY(ARG(14), ARG(8));
			}
			if(CL_TRUEP(ARG(8)))
			{
			}
			else
			{
				COPY(ARG(3), ARG(8));
			}
			COPY(ARG(6), ARG(9));
			COPY(ARG(8), ARG(10));
			COPY(ARG(7), ARG(11));
			Fminus(ARG(10), 2);
			Fplus(ARG(9), 2);
			COPY(ARG(5), ARG(10));
			COPY(ARG(4), ARG(11));
			COPY(ARG(6), ARG(12));
			COPY(ARG(9), ARG(13));
			COPY(ARG(7), ARG(14));
			COPY(ARG(8), ARG(15));
			replace1(ARG(10));
			COPY(ARG(8), ARG(10));
			Fzerop(ARG(10));
			if(CL_TRUEP(ARG(10)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[80], ARG(10));	/* / */
			}
			else
			{
				COPY(ARG(5), ARG(10));
			}
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(11));	/* T */
			unix_file_kind1(ARG(10));
			if(CL_TRUEP(ARG(10)))
			{
			}
			else
			{
				LOAD_NIL(ARG(2));
				goto RETURN1;
			}
			if(CL_SYMBOLP(ARG(10)) && GET_SYMBOL(ARG(10)) == SYMBOL(Slisp, 290))	/* LINK */
			{
				COPY(ARG(5), ARG(11));
				unix_readlink(ARG(11));
				MV_TO_STACK(mv_count, 12);
				{
					int nargs;
					nargs = mv_count;
					mv_count = 1;
					{
						switch(nargs)
						{
							case 0:
							LOAD_NIL(ARG(11));
							case 1:
							LOAD_NIL(ARG(12));
							nargs = 2;
						}
						if(CL_TRUEP(ARG(11)))
						{
						}
						else
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[78], ARG(13));	/* Error reading link ~S: ~S */
							LOAD_SMALLFIXNUM(0, ARG(14));
							COPY(ARG(5), ARG(15));
							COPY(ARG(14), ARG(16));
							COPY(ARG(6), ARG(17));
							vector_subseq(ARG(15));
							COPY(ARG(15), ARG(14));
							COPY(SYMVAL(Slisp, 283), ARG(15));	/* *UNIX-ERRORS* */
							COPY(ARG(12), ARG(16));
							Farray_in_bounds_p(ARG(15), 2);
							if(CL_TRUEP(ARG(15)))
							{
								COPY(SYMVAL(Slisp, 283), ARG(15));	/* *UNIX-ERRORS* */
								COPY(ARG(12), ARG(16));
								Fsvref(ARG(15));
							}
							else
							{
								LOAD_NIL(ARG(15));
								LOAD_SMSTR((CL_FORM *)&KClisp[76], ARG(16));	/* Unknown error [~d] */
								COPY(ARG(12), ARG(17));
								Fformat(ARG(15), 3);
								mv_count = 1;
							}
							Ferror(ARG(13), 3);
						}
						COPY(ARG(11), ARG(13));
						Flength(ARG(13));
						Fzerop(ARG(13));
						if(CL_TRUEP(ARG(13)))
						{
							goto THEN3;
						}
						else
						{
							COPY(ARG(11), ARG(14));
							LOAD_SMALLFIXNUM(0, ARG(15));
							Fschar(ARG(14));
							LOAD_CHAR(ARG(15), '/', ARG(15));
							rt_charNE(ARG(14));
						}
						if(CL_TRUEP(ARG(14)))
						{
							THEN3:;
							COPY(ARG(5), ARG(13));
							LOAD_SMALLFIXNUM(0, ARG(14));
							LOAD_SMALLFIXNUM(0, ARG(15));
							COPY(ARG(14), ARG(16));
							COPY(SYMVAL(Slisp, 12), ARG(17));	/* CHAR-CODE-LIMIT */
							Fle(ARG(15), 3);
							if(CL_TRUEP(ARG(15)))
							{
								rt_code_char(ARG(14));
							}
							else
							{
								LOAD_NIL(ARG(14));
							}
							COPY(ARG(6), ARG(15));
							COPY(ARG(9), ARG(16));
							fill1(ARG(13));
						}
						else
						{
							COPY(ARG(5), ARG(13));
							LOAD_SMSTR((CL_FORM *)&KClisp[74], ARG(14));	/* /../ */
							LOAD_SMALLFIXNUM(0, ARG(15));
							LOAD_SMALLFIXNUM(4, ARG(16));
							LOAD_SMALLFIXNUM(0, ARG(17));
							LOAD_NIL(ARG(18));
							stringE1(ARG(13));
							if(CL_TRUEP(ARG(13)))
							{
								LOAD_CHAR(ARG(13), '/', ARG(13));
								LOAD_SMALLFIXNUM(4, ARG(14));
								LOAD_NIL(ARG(15));
								LOAD_NIL(ARG(16));
								LOAD_NIL(ARG(17));
								COPY(SYMVAL(Slisp, 0), ARG(18));	/* MOST-POSITIVE-FIXNUM */
								LOAD_NIL(ARG(19));
								LOAD_CHAR(ARG(20), '/', ARG(20));
								COPY(ARG(5), ARG(21));
								LOAD_NIL(ARG(22));
								LOAD_NIL(ARG(23));
								LOAD_NIL(ARG(24));
								COPY(ARG(14), ARG(25));
								COPY(ARG(18), ARG(26));
								LOAD_NIL(ARG(27));
								vector_position(ARG(20));
								COPY(ARG(20), ARG(13));
								if(CL_TRUEP(ARG(13)))
								{
								}
								else
								{
									LOAD_SMALLFIXNUM(0, ARG(13));
								}
								COPY(ARG(5), ARG(14));
								LOAD_SMALLFIXNUM(0, ARG(15));
								LOAD_SMALLFIXNUM(0, ARG(16));
								COPY(ARG(15), ARG(17));
								COPY(SYMVAL(Slisp, 12), ARG(18));	/* CHAR-CODE-LIMIT */
								Fle(ARG(16), 3);
								if(CL_TRUEP(ARG(16)))
								{
									rt_code_char(ARG(15));
								}
								else
								{
									LOAD_NIL(ARG(15));
								}
								COPY(ARG(13), ARG(16));
								COPY(ARG(9), ARG(17));
								fill1(ARG(14));
								COPY(ARG(13), ARG(6));
							}
							else
							{
								COPY(ARG(5), ARG(13));
								LOAD_SMALLFIXNUM(0, ARG(14));
								LOAD_SMALLFIXNUM(0, ARG(15));
								COPY(ARG(14), ARG(16));
								COPY(SYMVAL(Slisp, 12), ARG(17));	/* CHAR-CODE-LIMIT */
								Fle(ARG(15), 3);
								if(CL_TRUEP(ARG(15)))
								{
									rt_code_char(ARG(14));
								}
								else
								{
									LOAD_NIL(ARG(14));
								}
								LOAD_SMALLFIXNUM(0, ARG(15));
								COPY(ARG(9), ARG(16));
								fill1(ARG(13));
								LOAD_SMALLFIXNUM(0, ARG(6));
							}
						}
						COPY(ARG(8), ARG(13));
						COPY(ARG(3), ARG(14));
						Fnumeql(ARG(13), 2);
						if(CL_TRUEP(ARG(13)))
						{
							COPY(ARG(11), ARG(13));
						}
						else
						{
							LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(13));	/* SIMPLE-STRING */
							COPY(ARG(11), ARG(14));
							if(CL_LISTP(ARG(4)))
							{
								COPY(ARG(4), ARG(15));
								COPY(ARG(8), ARG(16));
								COPY(SYMVAL(Slisp, 0), ARG(17));	/* MOST-POSITIVE-FIXNUM */
								list_subseq(ARG(15));
							}
							else
							{
								COPY(ARG(4), ARG(15));
								COPY(ARG(8), ARG(16));
								COPY(SYMVAL(Slisp, 0), ARG(17));	/* MOST-POSITIVE-FIXNUM */
								vector_subseq(ARG(15));
							}
							Fconcatenate(ARG(13), 3);
						}
						COPY(ARG(13), ARG(4));
						Flength(ARG(13));
						COPY(ARG(13), ARG(3));
						LOAD_SMALLFIXNUM(0, ARG(7));
					}
				}
			}
			else
			{
				COPY(ARG(8), ARG(11));
				COPY(ARG(3), ARG(12));
				Fnumeql(ARG(11), 2);
				if(CL_TRUEP(ARG(11)))
				{
					LOAD_SMALLFIXNUM(0, ARG(11));
					COPY(ARG(5), ARG(2));
					COPY(ARG(11), ARG(3));
					COPY(ARG(9), ARG(4));
					vector_subseq(ARG(2));
					goto RETURN1;
				}
				else
				{
					if(CL_SYMBOLP(ARG(10)) && GET_SYMBOL(ARG(10)) == SYMBOL(Slisp, 251))	/* DIRECTORY */
					{
						LOAD_CHAR(ARG(11), '/', ARG(11));
						COPY(ARG(5), ARG(12));
						COPY(ARG(9), ARG(13));
						Fset_schar(ARG(11));
						COPY(ARG(9), ARG(11));
						F1plus(ARG(11));
						COPY(ARG(11), ARG(6));
						COPY(ARG(8), ARG(11));
						F1plus(ARG(11));
						COPY(ARG(11), ARG(7));
					}
					else
					{
						LOAD_NIL(ARG(2));
						goto RETURN1;
					}
				}
			}
			goto M1_1;
			RETURN1:;
		}
		if(CL_TRUEP(ARG(2)))
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(3));	/* T */
			BIND_SPECIAL(SYMBOL(Slisp, 277), ARG(3));	/* *IGNORE-WILDCARDS* */
			COPY(ARG(2), ARG(4));
			Flength(ARG(4));
			COPY(ARG(4), ARG(5));
			LOAD_CHAR(ARG(6), ' ', ARG(6));
			make_string1(ARG(5));
			LOAD_SMALLFIXNUM(0, ARG(6));
			LOAD_SMALLFIXNUM(0, ARG(7));
			LOAD_NIL(ARG(8));
			LOAD_SMALLFIXNUM(0, ARG(9));
			M2_1:;
			COPY(ARG(9), ARG(10));
			COPY(ARG(4), ARG(11));
			Fge(ARG(10), 2);
			if(CL_TRUEP(ARG(10)))
			{
				goto RETURN3;
			}
			COPY(ARG(2), ARG(10));
			COPY(ARG(9), ARG(11));
			Fschar(ARG(10));
			COPY(ARG(10), ARG(11));
			LOAD_CHAR(ARG(12), '.', ARG(12));
			rt_charE(ARG(11));
			if(CL_TRUEP(ARG(11)))
			{
				if(CL_TRUEP(ARG(7)))
				{
					COPY(ARG(7), ARG(11));
					F1plus(ARG(11));
					COPY(ARG(11), ARG(7));
				}
				COPY(ARG(10), ARG(11));
				COPY(ARG(5), ARG(12));
				COPY(ARG(6), ARG(13));
				Fset_schar(ARG(11));
				COPY(ARG(6), ARG(11));
				F1plus(ARG(11));
				COPY(ARG(11), ARG(6));
			}
			else
			{
				COPY(ARG(10), ARG(11));
				LOAD_CHAR(ARG(12), '/', ARG(12));
				rt_charE(ARG(11));
				if(CL_TRUEP(ARG(11)))
				{
					LOAD_SMALLFIXNUM(0, ARG(12));
					if(EQL(ARG(7), ARG(12)))
					{
						if(CL_TRUEP(ARG(8)))
						{
						}
						else
						{
							COPY(ARG(6), ARG(8));
							COPY(ARG(10), ARG(11));
							COPY(ARG(5), ARG(12));
							COPY(ARG(6), ARG(13));
							Fset_schar(ARG(11));
							COPY(ARG(6), ARG(11));
							F1plus(ARG(11));
							COPY(ARG(11), ARG(6));
						}
					}
					else
					{
						LOAD_SMALLFIXNUM(1, ARG(12));
						if(EQL(ARG(7), ARG(12)))
						{
							COPY(ARG(6), ARG(11));
							F1minus(ARG(11));
							COPY(ARG(11), ARG(6));
						}
						else
						{
							LOAD_SMALLFIXNUM(2, ARG(12));
							if(EQL(ARG(7), ARG(12)))
							{
								if(CL_TRUEP(ARG(8)))
								{
									COPY(ARG(8), ARG(11));
									Fzerop(ARG(11));
									if(CL_TRUEP(ARG(11)))
									{
										goto ELSE4;
									}
									else
									{
										goto THEN5;
									}
								}
								else
								{
									goto ELSE4;
								}
								{
									THEN5:;
									LOAD_CHAR(ARG(11), '/', ARG(11));
									LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(12));	/* T */
									LOAD_NIL(ARG(13));
									LOAD_NIL(ARG(14));
									LOAD_SMALLFIXNUM(0, ARG(15));
									LOAD_NIL(ARG(16));
									LOAD_CHAR(ARG(17), '/', ARG(17));
									COPY(ARG(5), ARG(18));
									LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(19));	/* T */
									LOAD_NIL(ARG(20));
									LOAD_NIL(ARG(21));
									COPY(ARG(15), ARG(22));
									COPY(ARG(8), ARG(23));
									LOAD_NIL(ARG(24));
									vector_position(ARG(17));
									COPY(ARG(17), ARG(11));
									if(CL_TRUEP(ARG(11)))
									{
										COPY(ARG(11), ARG(12));
									}
									else
									{
										LOAD_SMALLFIXNUM(0, ARG(12));
									}
									LOAD_SMALLFIXNUM(2, ARG(13));
									Fplus(ARG(12), 2);
									COPY(ARG(8), ARG(13));
									Fnumeql(ARG(12), 2);
									if(CL_TRUEP(ARG(12)))
									{
										COPY(ARG(5), ARG(12));
										COPY(ARG(8), ARG(13));
										LOAD_SMALLFIXNUM(2, ARG(14));
										Fminus(ARG(13), 2);
										Fschar(ARG(12));
										LOAD_CHAR(ARG(13), '.', ARG(13));
										rt_charE(ARG(12));
										if(CL_TRUEP(ARG(12)))
										{
											COPY(ARG(5), ARG(12));
											COPY(ARG(8), ARG(13));
											F1minus(ARG(13));
											Fschar(ARG(12));
											LOAD_CHAR(ARG(13), '.', ARG(13));
											rt_charE(ARG(12));
										}
										else
										{
											goto ELSE6;
										}
									}
									else
									{
										goto ELSE6;
									}
									if(CL_TRUEP(ARG(12)))
									{
										COPY(ARG(10), ARG(12));
										COPY(ARG(5), ARG(13));
										COPY(ARG(6), ARG(14));
										Fset_schar(ARG(12));
										COPY(ARG(6), ARG(12));
										F1plus(ARG(12));
										COPY(ARG(12), ARG(6));
										COPY(ARG(6), ARG(8));
									}
									else
									{
										ELSE6:;
										if(CL_TRUEP(ARG(11)))
										{
											COPY(ARG(11), ARG(12));
											F1plus(ARG(12));
											COPY(ARG(12), ARG(6));
										}
										else
										{
											LOAD_SMALLFIXNUM(0, ARG(6));
										}
										COPY(ARG(11), ARG(8));
									}
								}
								goto ENDIF7;
								{
									ELSE4:;
									COPY(ARG(6), ARG(8));
									COPY(ARG(10), ARG(11));
									COPY(ARG(5), ARG(12));
									COPY(ARG(6), ARG(13));
									Fset_schar(ARG(11));
									COPY(ARG(6), ARG(11));
									F1plus(ARG(11));
									COPY(ARG(11), ARG(6));
								}
								ENDIF7:;
							}
							else
							{
								COPY(ARG(6), ARG(8));
								COPY(ARG(10), ARG(11));
								COPY(ARG(5), ARG(12));
								COPY(ARG(6), ARG(13));
								Fset_schar(ARG(11));
								COPY(ARG(6), ARG(11));
								F1plus(ARG(11));
								COPY(ARG(11), ARG(6));
							}
						}
					}
					LOAD_SMALLFIXNUM(0, ARG(7));
				}
				else
				{
					LOAD_NIL(ARG(7));
					COPY(ARG(10), ARG(11));
					COPY(ARG(5), ARG(12));
					COPY(ARG(6), ARG(13));
					Fset_schar(ARG(11));
					COPY(ARG(6), ARG(11));
					F1plus(ARG(11));
					COPY(ARG(11), ARG(6));
				}
			}
			F1plus(ARG(9));
			goto M2_1;
			RETURN3:;
			if(CL_TRUEP(ARG(8)))
			{
				COPY(ARG(8), ARG(9));
				Fzerop(ARG(9));
				if(CL_TRUEP(ARG(9)))
				{
					goto ELSE8;
				}
				else
				{
					goto THEN9;
				}
			}
			else
			{
				goto ELSE8;
			}
			{
				THEN9:;
				LOAD_SMALLFIXNUM(1, ARG(10));
				if(EQL(ARG(7), ARG(10)))
				{
					COPY(ARG(6), ARG(9));
					F1minus(ARG(9));
					COPY(ARG(9), ARG(6));
				}
				else
				{
					LOAD_SMALLFIXNUM(2, ARG(10));
					if(EQL(ARG(7), ARG(10)))
					{
						COPY(ARG(8), ARG(9));
						LOAD_SMALLFIXNUM(2, ARG(10));
						Fge(ARG(9), 2);
						if(CL_TRUEP(ARG(9)))
						{
							COPY(ARG(5), ARG(9));
							COPY(ARG(8), ARG(10));
							F1minus(ARG(10));
							Fschar(ARG(9));
							LOAD_CHAR(ARG(10), '.', ARG(10));
							rt_charE(ARG(9));
							if(CL_TRUEP(ARG(9)))
							{
								COPY(ARG(5), ARG(9));
								COPY(ARG(8), ARG(10));
								LOAD_SMALLFIXNUM(2, ARG(11));
								Fminus(ARG(10), 2);
								Fschar(ARG(9));
								LOAD_CHAR(ARG(10), '.', ARG(10));
								rt_charE(ARG(9));
								if(CL_TRUEP(ARG(9)))
								{
									COPY(ARG(8), ARG(9));
									LOAD_SMALLFIXNUM(2, ARG(10));
									Fnumeql(ARG(9), 2);
									if(CL_TRUEP(ARG(9)))
									{
										goto THEN10;
									}
									else
									{
										COPY(ARG(5), ARG(10));
										COPY(ARG(8), ARG(11));
										LOAD_SMALLFIXNUM(3, ARG(12));
										Fminus(ARG(11), 2);
										Fschar(ARG(10));
										LOAD_CHAR(ARG(11), '/', ARG(11));
										rt_charE(ARG(10));
									}
								}
								else
								{
									goto ELSE11;
								}
							}
							else
							{
								goto ELSE11;
							}
						}
						else
						{
							goto ELSE11;
						}
						if(CL_TRUEP(ARG(10)))
						{
							THEN10:;
						}
						else
						{
							ELSE11:;
							LOAD_CHAR(ARG(9), '/', ARG(9));
							LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(10));	/* T */
							LOAD_NIL(ARG(11));
							LOAD_NIL(ARG(12));
							LOAD_SMALLFIXNUM(0, ARG(13));
							LOAD_NIL(ARG(14));
							LOAD_CHAR(ARG(15), '/', ARG(15));
							COPY(ARG(5), ARG(16));
							LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(17));	/* T */
							LOAD_NIL(ARG(18));
							LOAD_NIL(ARG(19));
							COPY(ARG(13), ARG(20));
							COPY(ARG(8), ARG(21));
							LOAD_NIL(ARG(22));
							vector_position(ARG(15));
							COPY(ARG(15), ARG(9));
							if(CL_TRUEP(ARG(9)))
							{
								COPY(ARG(9), ARG(10));
								F1plus(ARG(10));
								COPY(ARG(10), ARG(6));
							}
							else
							{
								LOAD_SMSTR((CL_FORM *)&KClisp[72], ARG(4));	/* ./ */
								goto RETURN2;
							}
						}
					}
				}
			}
			ELSE8:;
			COPY(ARG(6), ARG(9));
			Fzerop(ARG(9));
			if(CL_TRUEP(ARG(9)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[70], ARG(4));	/* ./ */
			}
			else
			{
				COPY(ARG(6), ARG(9));
				COPY(ARG(4), ARG(10));
				Fnumeql(ARG(9), 2);
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(5), ARG(4));
				}
				else
				{
					LOAD_SMALLFIXNUM(0, ARG(9));
					COPY(ARG(5), ARG(4));
					COPY(ARG(9), ARG(5));
					vector_subseq(ARG(4));
				}
			}
			RETURN2:;
			Fpathname(ARG(4));
			COPY(ARG(4), ARG(0));
			RESTORE_SPECIAL;
		}
		else
		{
			LOAD_NIL(ARG(0));
		}
	}
	else
	{
		ELSE1:;
		LOAD_NIL(ARG(0));
	}
}
