/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Freadtablep(CL_FORM *base)
{
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(1));	/* READTABLE */
	rt_struct_typep(ARG(0));
}
