/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Frplaca(CL_FORM *base)
{
	if(CL_CONSP(ARG(0)))
	{
		COPY(ARG(1), GET_CAR(ARG(0)));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[237], ARG(2));	/* ~a is not a cons */
		COPY(ARG(0), ARG(3));
		Ferror(ARG(2), 2);
	}
}
