/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fscale_float(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	COPY(SYMVAL(Slisp, 314), ARG(3));	/* FLOAT-RADIX */
	COPY(ARG(0), ARG(4));
	Ffloat(ARG(3), 2);
	COPY(ARG(1), ARG(4));
	Fexpt(ARG(3));
	Fmult(ARG(2), 2);
	COPY(ARG(2), ARG(0));
}
