/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fset(CL_FORM *base)
{
	if(CL_SYMBOLP(ARG(0)))
	{
		if(SYM_IS_CONST(ARG(0)))
		{
			COPY(SYMVAL(Slisp, 680), ARG(2));	/* TRY_CHANGE_CONST */
			COPY(ARG(0), ARG(3));
			Ferror(ARG(2), 2);
		}
		else
		{
			COPY(ARG(1), SYM_VALUE(ARG(0)));
			COPY(ARG(1), ARG(0));
		}
	}
	else
	{
		if(CL_TRUEP(ARG(0)))
		{
			COPY(SYMVAL(Slisp, 679), ARG(2));	/* SYM_EXPECTED */
			COPY(ARG(0), ARG(3));
			Ferror(ARG(2), 2);
		}
		else
		{
			COPY(SYMVAL(Slisp, 680), ARG(0));	/* TRY_CHANGE_CONST */
			LOAD_NIL(ARG(1));
			Ferror(ARG(0), 2);
		}
	}
}
