/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fset_elt(CL_FORM *base)
{
	if(CL_LISTP(ARG(1)))
	{
		COPY(ARG(2), ARG(3));
		COPY(ARG(1), ARG(4));
		Fnthcdr(ARG(3));
		if(CL_CONSP(ARG(3)))
		{
			COPY(ARG(0), GET_CAR(ARG(3)));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[229], ARG(0));	/* ~a is not a cons */
			COPY(ARG(3), ARG(1));
			Ferror(ARG(0), 2);
		}
	}
	else
	{
		Fset_row_major_aref(ARG(0));
	}
}
