/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fslot_missing(CL_FORM *base)
{
	LOAD_SMSTR((CL_FORM *)&KClisp[212], ARG(4));	/* ~S: The slot ~s is missing from the object ~s of class ~s. */
	COPY(ARG(3), ARG(5));
	COPY(ARG(2), ARG(6));
	COPY(ARG(1), ARG(7));
	COPY(ARG(0), ARG(8));
	Ferror(ARG(4), 5);
}
