/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fslot_unbound(CL_FORM *base)
{
	LOAD_SMSTR((CL_FORM *)&KClisp[214], ARG(3));	/* The slot ~s is unbound in the object ~s of class ~s. */
	COPY(ARG(2), ARG(4));
	COPY(ARG(1), ARG(5));
	COPY(ARG(0), ARG(6));
	Ferror(ARG(3), 4);
}
