/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void FstringNE(CL_FORM *base, int nargs)
{
	BOOL supl_flags[4];
	static CL_FORM * keylist[] =
	{
		SYMBOL(Slisp, 292),	/* START1 */
		SYMBOL(Slisp, 293),	/* END1 */
		SYMBOL(Slisp, 270),	/* START2 */
		SYMBOL(Slisp, 271),	/* END2 */
	};
	keysort(ARG(2), nargs - 2, 4, keylist, supl_flags, FALSE);
	if(NOT(supl_flags[0]))
	{
		LOAD_SMALLFIXNUM(0, ARG(2));
	}
	if(NOT(supl_flags[1]))
	{
		LOAD_NIL(ARG(3));
	}
	if(NOT(supl_flags[2]))
	{
		LOAD_SMALLFIXNUM(0, ARG(4));
	}
	if(NOT(supl_flags[3]))
	{
		LOAD_NIL(ARG(5));
	}
	stringNE1(ARG(0));
}
