/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fsubseq(CL_FORM *base, int nargs)
{
	switch(nargs)
	{
		case 2:
		COPY(SYMVAL(Slisp, 0), ARG(2));	/* MOST-POSITIVE-FIXNUM */
		case 3:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	subseq1(ARG(0));
}
