/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CFthird, Fthird, 1);

void Fthird(CL_FORM *base)
{
	Fcaddr(ARG(0));
}
