/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fvector_push(CL_FORM *base)
{
	COPY(ARG(1), ARG(2));
	complex_vector_fillptr(ARG(2));
	COPY(ARG(2), ARG(3));
	COPY(ARG(1), ARG(4));
	LOAD_SMALLFIXNUM(0, ARG(5));
	Farray_dimension(ARG(4));
	Flt(ARG(3), 2);
	if(CL_TRUEP(ARG(3)))
	{
		COPY(ARG(0), ARG(3));
		COPY(ARG(1), ARG(4));
		COPY(ARG(2), ARG(5));
		rt_set_vref(ARG(3));
		COPY(ARG(2), ARG(3));
		F1plus(ARG(3));
		COPY(ARG(3), ARG(4));
		COPY(ARG(1), ARG(5));
		set_complex_vector_fillptr(ARG(4));
		COPY(ARG(2), ARG(0));
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
