/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CFvector, Fvector, -1);

void Fvector(CL_FORM *base, int nargs)
{
	Flist(ARG(0), nargs - 0);
	COPY(ARG(0), ARG(1));
	Flength(ARG(1));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(2));	/* T */
	LOAD_NIL(ARG(3));
	COPY(ARG(0), ARG(4));
	LOAD_NIL(ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	LOAD_SMALLFIXNUM(0, ARG(8));
	LOAD_NIL(ARG(9));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(10));	/* T */
	make_array1(ARG(1));
	COPY(ARG(1), ARG(0));
}
