/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CFwrite_string, Fwrite_string, -2);

void Fwrite_string(CL_FORM *base, int nargs)
{
	switch(nargs)
	{
		case 1:
		LOAD_NIL(ARG(1));
		nargs = 2;
	}
	{
		BOOL supl_flags[2];
		static CL_FORM * keylist[] =
		{
			SYMBOL(Slisp, 229),	/* START */
			SYMBOL(Slisp, 230),	/* END */
		};
		keysort(ARG(2), nargs - 2, 2, keylist, supl_flags, FALSE);
		if(NOT(supl_flags[0]))
		{
			LOAD_SMALLFIXNUM(0, ARG(2));
		}
		if(NOT(supl_flags[1]))
		{
			COPY(ARG(0), ARG(4));
			Flength(ARG(4));
			COPY(ARG(4), ARG(3));
		}
	}
	write_string1(ARG(0));
}
