/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void getf1(CL_FORM *base)
{
	COPY(ARG(0), ARG(3));
	COPY(ARG(1), ARG(4));
	get_prop(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		COPY(GET_CDR(ARG(3)), ARG(4));
		if(CL_CONSP(ARG(4)))
		{
			COPY(GET_CAR(ARG(4)), ARG(0));
		}
		else
		{
			if(CL_TRUEP(ARG(4)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(0));	/* ~a is not a list */
				COPY(ARG(4), ARG(1));
				Ferror(ARG(0), 2);
			}
			else
			{
				LOAD_NIL(ARG(0));
			}
		}
	}
	else
	{
		COPY(ARG(2), ARG(0));
	}
}
