/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

static void Z55_lambda(CL_FORM *base);
static void Z56_lambda(CL_FORM *base);

void read_from_string1(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(1), ARG(6));
	GEN_HEAPVAR(ARG(2), ARG(6));
	BIND_SPECIAL(SYMBOL(Slisp, 444), ARG(5));	/* *PRESERVE-WHITESPACE* */
	LOAD_NIL(ARG(6));
	GEN_HEAPVAR(ARG(6), ARG(7));
	LOAD_SMALLFIXNUM(0, ARG(7));
	BIND_SPECIAL(SYMBOL(Slisp, 437), ARG(7));	/* *BQ-LEVEL* */
	COPY(ARG(0), ARG(8));
	COPY(ARG(3), ARG(9));
	COPY(ARG(4), ARG(10));
	make_string_input_stream1(ARG(8));
	GEN_HEAPVAR(ARG(8), ARG(9));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(9));	/* T */
	GEN_HEAPVAR(ARG(9), ARG(10));
	{
		GEN_CLOSURE(array, ARG(10), 8, Z56_lambda, 0);
		COPY(ARG(9), &array[3]);
		COPY(ARG(6), &array[4]);
		COPY(ARG(2), &array[5]);
		COPY(ARG(1), &array[6]);
		COPY(ARG(8), &array[7]);
		LOAD_CLOSURE(array, ARG(10));
	}
	COPY(ARG(10), ARG(10));
	{
		GEN_CLOSURE(array, ARG(11), 4, Z55_lambda, 0);
		COPY(ARG(8), &array[3]);
		LOAD_CLOSURE(array, ARG(11));
	}
	COPY(ARG(11), ARG(11));
	rt_unwind_protect(ARG(10));
	COPY(ARG(10), ARG(0));
	RESTORE_SPECIAL;
	RESTORE_SPECIAL;
}

static void Z55_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	COPY(ARG(1), ARG(2));
	LOAD_SMALLFIXNUM(9, ARG(3));
	COPY(ARG(2), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), GET_FIXNUM(ARG(3)) + 1), ARG(1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(1));	/* NO_STRUCT */
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(3));	/* STREAM */
		Ferror(ARG(1), 3);
	}
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(2));
	Ffuncall(ARG(1), 2);
	COPY(ARG(1), ARG(0));
}

static void Z56_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 7), ARG(1));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 6), ARG(2));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 5), ARG(3));
	LOAD_NIL(ARG(4));
	internal_read(ARG(1));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(2));
	COPY(ARG(2), &mv_buf[0]);
	mv_count = 2;
	COPY(&mv_buf[0], ARG(2));
	{
		int nargs;
		nargs = 2;
		mv_count = 1;
		{
			CL_FORM *rest_0;
			CL_FORM *local;
			rest_0 = ARG(1);
			local = ARG(nargs + 1);
			{
				COPY(INDIRECT(GET_FORM(ARG(0)) + 7), LOCAL(0));
				LOAD_NIL(LOCAL(1));
				LOAD_NIL(LOCAL(2));
				file_position1(LOCAL(0));
				mv_count = 1;
				COPY(LOCAL(0), INDIRECT(GET_FORM(ARG(0)) + 4));
			}
			{
				GEN_STATIC_GLOBAL_FUNARG(extern_closure, Fvalues, -1);
				LOAD_GLOBFUN(&extern_closure, LOCAL(0));
			}
			REST_APPLY(LOCAL(0), 1, rest_0);
			COPY(LOCAL(0), ARG(1));
		}
	}
	MV_TO_STACK(mv_count, 2);
	{
		int nargs;
		nargs = mv_count;
		mv_count = 1;
		{
			CL_FORM *rest_0;
			CL_FORM *local;
			rest_0 = ARG(1);
			local = ARG(nargs + 1);
			LOAD_NIL(INDIRECT(GET_FORM(ARG(0)) + 3));
			{
				GEN_STATIC_GLOBAL_FUNARG(extern_closure, Fvalues, -1);
				LOAD_GLOBFUN(&extern_closure, LOCAL(0));
			}
			REST_APPLY(LOCAL(0), 1, rest_0);
			COPY(LOCAL(0), ARG(0));
		}
	}
}
