/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void FFI_make_lisp_string(CL_FORM *base)
{
	if(CL_C_STRING_P(ARG(0)))
	{
		rt_make_lisp_string(ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(1));
		Fstringp(ARG(1));
		if(CL_TRUEP(ARG(1)))
		{
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[218], ARG(1));	/* ~&Error in ~A: ~?~% */
			LOAD_SMSTR((CL_FORM *)&KClisp[4], ARG(2));	/* MAKE-LISP-STRING */
			COPY(SYMVAL(Slisp, 715), ARG(3));	/* NO-STRING */
			COPY(ARG(0), ARG(4));
			Flist(ARG(4), 1);
			Ferror(ARG(1), 4);
		}
	}
}
