/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void coerce_to_package(CL_FORM *base)
{
	if(CL_SYMBOLP(ARG(0)) || CL_NILP(ARG(0)))
	{
		COPY(ARG(0), ARG(1));
		if(CL_SYMBOLP(ARG(1)))
		{
			GET_SYM_NAME(ARG(3), ARG(1), ARG(0));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(0));	/* NIL */
		}
	}
	COPY(ARG(0), ARG(1));
	Fstringp(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		Ffind_package(ARG(0));
	}
}
