/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fmake_string_input_stream(CL_FORM *base, int nargs)
{
	switch(nargs)
	{
		case 1:
		LOAD_SMALLFIXNUM(0, ARG(1));
		case 2:
		COPY(ARG(0), ARG(2));
		Flength(ARG(2));
		case 3:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	make_string_input_stream1(ARG(0));
}
