#include "inline.h"
#include "inline.h"

extern CL_INIT KClisp[];
extern CL_INIT Slisp[];
void make_stream(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cmake_stream;
void Fstreamp(CL_FORM *base);
void stream_extra(CL_FORM *base);
void stream_readc(CL_FORM *base);
void stream_unreadc(CL_FORM *base);
void stream_writec(CL_FORM *base);
void stream_column(CL_FORM *base);
void stream_tell(CL_FORM *base);
void stream_seek(CL_FORM *base);
void stream_length(CL_FORM *base);
void stream_close(CL_FORM *base);
void undef_stream_op(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cundef_stream_op;
void nil_fun(CL_FORM *base);
extern GLOBAL_FUNARG Cnil_fun;
void close_err(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cclose_err;
void close1(CL_FORM *base);
extern GLOBAL_FUNARG Cclose1;
void Fmake_synonym_stream(CL_FORM *base);
void Fmake_broadcast_stream(CL_FORM *base, int nargs);
void Fmake_concatenated_stream(CL_FORM *base, int nargs);
void Fmake_two_way_stream(CL_FORM *base);
void Fmake_echo_stream(CL_FORM *base);
void Fmake_string_input_stream(CL_FORM *base, int nargs);
void Fmake_string_output_stream(CL_FORM *base, int nargs);
void Fget_output_stream_string(CL_FORM *base);
void Finput_stream_p(CL_FORM *base);
void Foutput_stream_p(CL_FORM *base);
void Fstream_element_type(CL_FORM *base);
void file_name(CL_FORM *base, int nargs);
void make_file_input_stream(CL_FORM *base);
void make_file_output_stream(CL_FORM *base);
void make_file_io_stream(CL_FORM *base);
void make_terminal_io(CL_FORM *base);
void Fclose(CL_FORM *base, int nargs);
void Fmake_array(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFmake_array;
void Fvector(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFvector;
void Faref(CL_FORM *base, int nargs);
void Fset_aref(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFset_aref;
void Frow_major_aref(CL_FORM *base);
void Fset_row_major_aref(CL_FORM *base);
extern GLOBAL_FUNARG CFset_row_major_aref;
void vref(CL_FORM *base);
void set_vref(CL_FORM *base);
void Fsvref(CL_FORM *base);
void Fset_svref(CL_FORM *base);
extern GLOBAL_FUNARG CFset_svref;
void Farray_element_type(CL_FORM *base);
void to_element_type(CL_FORM *base);
void Fupgraded_array_element_type(CL_FORM *base);
void type_code_p(CL_FORM *base);
void Farray_dimension(CL_FORM *base);
void Farray_dimensions(CL_FORM *base);
void Farray_in_bounds_p(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFarray_in_bounds_p;
void Farray_row_major_index(CL_FORM *base, int nargs);
void array_rmi_internal(CL_FORM *base);
void Fset_fill_pointer(CL_FORM *base);
extern GLOBAL_FUNARG CFset_fill_pointer;
void Fvector_push(CL_FORM *base);
void Fvector_push_extend(CL_FORM *base, int nargs);
void Fvector_pop(CL_FORM *base);
void rmi_to_subscripts(CL_FORM *base);
void Fadjust_array(CL_FORM *base, int nargs);
void Fdigit_char_p(CL_FORM *base, int nargs);
void Fcode_char(CL_FORM *base);
void Fdigit_char(CL_FORM *base, int nargs);
void Fcharacter(CL_FORM *base);
void Fmake_instance(CL_FORM *base, int nargs);
void Freinitialize_instance(CL_FORM *base, int nargs);
void typep_class(CL_FORM *base);
void Fslot_value(CL_FORM *base);
void Fset_slot_value(CL_FORM *base);
void Fslot_boundp(CL_FORM *base);
void Fslot_makunbound(CL_FORM *base);
void Fclass_of(CL_FORM *base);
void Fno_next_method(CL_FORM *base);
void Fno_applicable_method(CL_FORM *base, int nargs);
void Fslot_missing(CL_FORM *base);
void Fslot_unbound(CL_FORM *base);
void Fcoerce(CL_FORM *base);
void Fopen(CL_FORM *base, int nargs);
void Ffile_position(CL_FORM *base, int nargs);
void Ffile_length(CL_FORM *base);
void Fread_char(CL_FORM *base, int nargs);
void Funread_char(CL_FORM *base, int nargs);
void Fwrite_char(CL_FORM *base, int nargs);
void make_pattern(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cmake_pattern;
void pattern_p(CL_FORM *base);
extern GLOBAL_FUNARG Cpattern_p;
void patternE(CL_FORM *base);
void compare_component(CL_FORM *base);
void Pmake_pathname(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CPmake_pathname;
void Fpathnamep(CL_FORM *base);
void make_host(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cmake_host;
void host_parse(CL_FORM *base);
void host_unparse(CL_FORM *base);
void host_unparse_host(CL_FORM *base);
void host_unparse_directory(CL_FORM *base);
void host_unparse_file(CL_FORM *base);
void host_unparse_enough(CL_FORM *base);
void Fparse_namestring(CL_FORM *base, int nargs);
void Fpathname(CL_FORM *base);
void maybe_diddle_case(CL_FORM *base);
void merge_directories(CL_FORM *base);
void Fmerge_pathnames(CL_FORM *base, int nargs);
void Fmake_pathname(CL_FORM *base, int nargs);
void Fpathname_host(CL_FORM *base, int nargs);
void Fpathname_device(CL_FORM *base, int nargs);
void Fpathname_directory(CL_FORM *base, int nargs);
void Fpathname_name(CL_FORM *base, int nargs);
void Fpathname_type(CL_FORM *base, int nargs);
void Fpathname_version(CL_FORM *base);
void Fnamestring(CL_FORM *base);
void Fhost_namestring(CL_FORM *base);
void Fdirectory_namestring(CL_FORM *base);
void Ffile_namestring(CL_FORM *base);
void Fenough_namestring(CL_FORM *base, int nargs);
void Fwild_pathname_p(CL_FORM *base, int nargs);
void pattern_matches(CL_FORM *base);
void components_match(CL_FORM *base);
void Fpathname_match_p(CL_FORM *base);
void remove_backslashes(CL_FORM *base);
void maybe_make_pattern(CL_FORM *base);
void parse_unix_namestring(CL_FORM *base);
extern GLOBAL_FUNARG Cparse_unix_namestring;
void unparse_unix_host(CL_FORM *base);
extern GLOBAL_FUNARG Cunparse_unix_host;
void unparse_unix_piece(CL_FORM *base);
void unparse_unix_directory_list(CL_FORM *base);
void unparse_unix_directory(CL_FORM *base);
extern GLOBAL_FUNARG Cunparse_unix_directory;
void unparse_unix_file(CL_FORM *base);
extern GLOBAL_FUNARG Cunparse_unix_file;
void unparse_unix_namestring(CL_FORM *base);
extern GLOBAL_FUNARG Cunparse_unix_namestring;
void unparse_unix_enough(CL_FORM *base);
extern GLOBAL_FUNARG Cunparse_unix_enough;
void Penumerate_matches(CL_FORM *base);
void Penumerate_directories(CL_FORM *base);
void Penumerate_files(CL_FORM *base);
void quick_integer_to_string(CL_FORM *base);
void unix_namestring(CL_FORM *base, int nargs);
void Ftruename(CL_FORM *base);
void Fprobe_file(CL_FORM *base);
void Fdirectory(CL_FORM *base, int nargs);
void unix_file_kind(CL_FORM *base, int nargs);
void Fmapcar(CL_FORM *base, int nargs);
void Fmaplist(CL_FORM *base, int nargs);
void Fmapc(CL_FORM *base, int nargs);
void Fmapl(CL_FORM *base, int nargs);
void Fmapcan(CL_FORM *base, int nargs);
void Fmapcon(CL_FORM *base, int nargs);
void Fidentity(CL_FORM *base);
extern GLOBAL_FUNARG CFidentity;
void Fdocumentation(CL_FORM *base);
void Fset_documentation(CL_FORM *base);
void Fmax(CL_FORM *base, int nargs);
void Fmin(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFmin;
void Fexpt(CL_FORM *base);
void Flog(CL_FORM *base, int nargs);
void Fisqrt(CL_FORM *base);
void Fabs(CL_FORM *base);
void Ffloat(CL_FORM *base, int nargs);
void Ffloor(CL_FORM *base, int nargs);
void Fceiling(CL_FORM *base, int nargs);
void Ftruncate(CL_FORM *base, int nargs);
void Fround(CL_FORM *base, int nargs);
void Fmod(CL_FORM *base);
void Frem(CL_FORM *base);
void Flogior(CL_FORM *base, int nargs);
void Flogxor(CL_FORM *base, int nargs);
void Flogand(CL_FORM *base, int nargs);
void Flogeqv(CL_FORM *base, int nargs);
void Flognand(CL_FORM *base);
void Flognor(CL_FORM *base);
void Flogandc1(CL_FORM *base);
void Flogandc2(CL_FORM *base);
void Flogorc1(CL_FORM *base);
void Flogorc2(CL_FORM *base);
void Flognot(CL_FORM *base);
void Flogtest(CL_FORM *base);
void Flogbitp(CL_FORM *base);
void Fash(CL_FORM *base);
void raw_make_package(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Craw_make_package;
void Fpackagep(CL_FORM *base);
void Fpackage_name(CL_FORM *base);
void Fpackage_nicknames(CL_FORM *base);
void del_pack_sym(CL_FORM *base);
void coerce_to_package(CL_FORM *base);
void add_nicknames(CL_FORM *base);
void Fmake_package(CL_FORM *base, int nargs);
void ensure_package(CL_FORM *base);
void Fin_package(CL_FORM *base, int nargs);
void Ffind_package(CL_FORM *base);
void Frename_package(CL_FORM *base, int nargs);
void Fpackage_use_list(CL_FORM *base);
void Fpackage_used_by_list(CL_FORM *base);
void Fpackage_shadowing_symbols(CL_FORM *base);
void Flist_all_packages(CL_FORM *base);
void Fintern(CL_FORM *base, int nargs);
void Ffind_symbol(CL_FORM *base, int nargs);
void Funintern(CL_FORM *base, int nargs);
void Fexport(CL_FORM *base, int nargs);
void Funexport(CL_FORM *base, int nargs);
void Fimport(CL_FORM *base, int nargs);
void internal_import(CL_FORM *base);
void Fshadowing_import(CL_FORM *base, int nargs);
void Fshadow(CL_FORM *base, int nargs);
void Fuse_package(CL_FORM *base, int nargs);
void Funuse_package(CL_FORM *base, int nargs);
void Ffind_all_symbols(CL_FORM *base);
void do_symbols_iterator(CL_FORM *base);
void do_external_symbols_iterator(CL_FORM *base);
void do_all_symbols_iterator(CL_FORM *base);
void setup_symbol(CL_FORM *base);
void Ftypep(CL_FORM *base);
void Fsubtypep(CL_FORM *base);
void check_array(CL_FORM *base);
void check_simple_array(CL_FORM *base);
void check_array_internal(CL_FORM *base);
void struct_typep(CL_FORM *base);
void make_struct(CL_FORM *base, int nargs);
void copy_struct(CL_FORM *base);
void struct_ref(CL_FORM *base);
void set_struct_ref(CL_FORM *base);
void struct_constructor(CL_FORM *base);
void set_struct_constructor(CL_FORM *base);
void new_hash_table(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cnew_hash_table;
void Fhash_table_p(CL_FORM *base);
void Fhash_table_size(CL_FORM *base);
void Fset_hash_table_size(CL_FORM *base);
extern GLOBAL_FUNARG CFset_hash_table_size;
void Fhash_table_count(CL_FORM *base);
void Fset_hash_table_count(CL_FORM *base);
extern GLOBAL_FUNARG CFset_hash_table_count;
void Fhash_table_rehash_size(CL_FORM *base);
void Fset_hash_table_rehash_size(CL_FORM *base);
void Fhash_table_rehash_threshold(CL_FORM *base);
void Fset_hash_table_rehash_threshold(CL_FORM *base);
void Fhash_table_test(CL_FORM *base);
void Fset_hash_table_test(CL_FORM *base);
void Fmake_hash_table(CL_FORM *base, int nargs);
void Fgethash(CL_FORM *base, int nargs);
void Fset_gethash(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFset_gethash;
void Fremhash(CL_FORM *base);
void Fmaphash(CL_FORM *base);
void Fclrhash(CL_FORM *base);
void Fsxhash(CL_FORM *base);
void internal_sxhash(CL_FORM *base);
void backquote_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cbackquote_reader;
void comma_reader(CL_FORM *base);
extern GLOBAL_FUNARG Ccomma_reader;
void bq_process(CL_FORM *base);
void maptree(CL_FORM *base);
void bq_splicing_frob(CL_FORM *base);
extern GLOBAL_FUNARG Cbq_splicing_frob;
void bq_simplify(CL_FORM *base);
extern GLOBAL_FUNARG Cbq_simplify;
void null_or_quoted(CL_FORM *base);
extern GLOBAL_FUNARG Cnull_or_quoted;
void bq_attach_append(CL_FORM *base);
void bq_attach_conses(CL_FORM *base);
void bq_remove_tokens(CL_FORM *base);
extern GLOBAL_FUNARG Cbq_remove_tokens;
void make_readtable(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cmake_readtable;
void Freadtablep(CL_FORM *base);
void Fcopy_readtable(CL_FORM *base, int nargs);
void Fset_syntax_from_char(CL_FORM *base, int nargs);
void copy_dispatch_macro_character(CL_FORM *base);
void Fset_macro_character(CL_FORM *base, int nargs);
void Fget_macro_character(CL_FORM *base, int nargs);
void Fmake_dispatch_macro_character(CL_FORM *base, int nargs);
void Fset_dispatch_macro_character(CL_FORM *base, int nargs);
void Fget_dispatch_macro_character(CL_FORM *base, int nargs);
void read_token(CL_FORM *base);
void cons_reader(CL_FORM *base);
extern GLOBAL_FUNARG Ccons_reader;
void right_parenthesis_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cright_parenthesis_reader;
void quote_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cquote_reader;
void semicolon_reader(CL_FORM *base);
extern GLOBAL_FUNARG Csemicolon_reader;
void string_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cstring_reader;
void char_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cchar_reader;
void function_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cfunction_reader;
void vector_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cvector_reader;
void binary_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cbinary_reader;
void octal_reader(CL_FORM *base);
extern GLOBAL_FUNARG Coctal_reader;
void hex_reader(CL_FORM *base);
extern GLOBAL_FUNARG Chex_reader;
void radix_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cradix_reader;
void uninterned_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cuninterned_reader;
void array_reader(CL_FORM *base);
extern GLOBAL_FUNARG Carray_reader;
void struct_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cstruct_reader;
void feature_plus_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cfeature_plus_reader;
void feature_minus_reader(CL_FORM *base);
extern GLOBAL_FUNARG Cfeature_minus_reader;
void eval_feature(CL_FORM *base);
void comment_block_reader(CL_FORM *base);
extern GLOBAL_FUNARG Ccomment_block_reader;
void internal_read(CL_FORM *base);
void Fread(CL_FORM *base, int nargs);
void Fread_preserving_whitespace(CL_FORM *base, int nargs);
void Fread_delimited_list(CL_FORM *base, int nargs);
void Fread_line(CL_FORM *base, int nargs);
void Fpeek_char(CL_FORM *base, int nargs);
void Fread_from_string(CL_FORM *base, int nargs);
void Fparse_integer(CL_FORM *base, int nargs);
void Fwrite(CL_FORM *base, int nargs);
void print_integer(CL_FORM *base);
void print_float(CL_FORM *base);
void write2(CL_FORM *base);
void Fprin1(CL_FORM *base, int nargs);
void Fprint(CL_FORM *base, int nargs);
void Fpprint(CL_FORM *base, int nargs);
void Fprinc(CL_FORM *base, int nargs);
void Fwrite_to_string(CL_FORM *base, int nargs);
void Fprin1_to_string(CL_FORM *base);
void Fprinc_to_string(CL_FORM *base);
void Fwrite_string(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFwrite_string;
void Fwrite_line(CL_FORM *base, int nargs);
void Fterpri(CL_FORM *base, int nargs);
void Ffresh_line(CL_FORM *base, int nargs);
void Fformat(CL_FORM *base, int nargs);
void format2(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cformat2;
void Ferror(CL_FORM *base, int nargs);
void Fwarn(CL_FORM *base, int nargs);
void Fbreak(CL_FORM *base, int nargs);
void sequence_type(CL_FORM *base);
void check_seq_start_end(CL_FORM *base);
void check_seq_count(CL_FORM *base);
void add_q(CL_FORM *base);
void Fcomplement(CL_FORM *base);
void Felt(CL_FORM *base);
void Fset_elt(CL_FORM *base);
extern GLOBAL_FUNARG CFset_elt;
void Fsubseq(CL_FORM *base, int nargs);
void Fcopy_seq(CL_FORM *base);
void Flength(CL_FORM *base);
extern GLOBAL_FUNARG CFlength;
void Freverse(CL_FORM *base);
void Fnreverse(CL_FORM *base);
void list_nreverse(CL_FORM *base);
void Fmake_sequence(CL_FORM *base, int nargs);
void Fconcatenate(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFconcatenate;
void concatenate_to_non_list(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cconcatenate_to_non_list;
void concatenate_to_list(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cconcatenate_to_list;
void Fmap(CL_FORM *base, int nargs);
void Fsome(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFsome;
void Fevery(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFevery;
void Fnotany(CL_FORM *base, int nargs);
void Fnotevery(CL_FORM *base, int nargs);
void Freduce(CL_FORM *base, int nargs);
void Ffill(CL_FORM *base, int nargs);
void Freplace(CL_FORM *base, int nargs);
void Fremove(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFremove;
void list_remove(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Clist_remove;
void vector_remove(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cvector_remove;
void Fremove_if(CL_FORM *base, int nargs);
void Fremove_if_not(CL_FORM *base, int nargs);
void Fdelete(CL_FORM *base, int nargs);
void Fdelete_if(CL_FORM *base, int nargs);
void Fdelete_if_not(CL_FORM *base, int nargs);
void Fremove_duplicates(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFremove_duplicates;
void Fdelete_duplicates(CL_FORM *base, int nargs);
void Ffind(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFfind;
void vector_find(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cvector_find;
void list_find(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Clist_find;
void Ffind_if(CL_FORM *base, int nargs);
void Ffind_if_not(CL_FORM *base, int nargs);
void Fposition(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFposition;
void vector_position(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Cvector_position;
void list_position(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG Clist_position;
void Fposition_if(CL_FORM *base, int nargs);
void Fposition_if_not(CL_FORM *base, int nargs);
void Fcount(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFcount;
void Fcount_if(CL_FORM *base, int nargs);
void Fcount_if_not(CL_FORM *base, int nargs);
void Fmismatch(CL_FORM *base, int nargs);
void Fsearch(CL_FORM *base, int nargs);
void Fsubstitute(CL_FORM *base, int nargs);
void Fsort(CL_FORM *base, int nargs);
void list_merge_sort(CL_FORM *base);
void quick_sort(CL_FORM *base);
void Fcar(CL_FORM *base);
extern GLOBAL_FUNARG CFcar;
void Fcdr(CL_FORM *base);
void Fset_car(CL_FORM *base);
extern GLOBAL_FUNARG CFset_car;
void Fset_cdr(CL_FORM *base);
extern GLOBAL_FUNARG CFset_cdr;
void Fcaar(CL_FORM *base);
void Fcadr(CL_FORM *base);
extern GLOBAL_FUNARG CFcadr;
void Fcdar(CL_FORM *base);
void Fcddr(CL_FORM *base);
void Fcaaar(CL_FORM *base);
void Fcaadr(CL_FORM *base);
void Fcadar(CL_FORM *base);
void Fcaddr(CL_FORM *base);
void Fcdaar(CL_FORM *base);
void Fcdadr(CL_FORM *base);
void Fcddar(CL_FORM *base);
void Fcdddr(CL_FORM *base);
void Fcaaaar(CL_FORM *base);
void Fcaaadr(CL_FORM *base);
void Fcaadar(CL_FORM *base);
void Fcaaddr(CL_FORM *base);
void Fcadaar(CL_FORM *base);
void Fcadadr(CL_FORM *base);
void Fcaddar(CL_FORM *base);
void Fcadddr(CL_FORM *base);
void Fcdaaar(CL_FORM *base);
void Fcdaadr(CL_FORM *base);
void Fcdadar(CL_FORM *base);
void Fcdaddr(CL_FORM *base);
void Fcddaar(CL_FORM *base);
void Fcddadr(CL_FORM *base);
void Fcdddar(CL_FORM *base);
void Fcddddr(CL_FORM *base);
void Fset_caar(CL_FORM *base);
void Fset_cadr(CL_FORM *base);
extern GLOBAL_FUNARG CFset_cadr;
void Fset_cdar(CL_FORM *base);
void Fset_cddr(CL_FORM *base);
void Fset_caaar(CL_FORM *base);
void Fset_caadr(CL_FORM *base);
void Fset_cadar(CL_FORM *base);
void Fset_caddr(CL_FORM *base);
extern GLOBAL_FUNARG CFset_caddr;
void Fset_cdaar(CL_FORM *base);
void Fset_cdadr(CL_FORM *base);
void Fset_cddar(CL_FORM *base);
void Fset_cdddr(CL_FORM *base);
void Fset_caaaar(CL_FORM *base);
void Fset_caaadr(CL_FORM *base);
void Fset_caadar(CL_FORM *base);
void Fset_caaddr(CL_FORM *base);
void Fset_cadaar(CL_FORM *base);
void Fset_cadadr(CL_FORM *base);
void Fset_caddar(CL_FORM *base);
void Fset_cadddr(CL_FORM *base);
extern GLOBAL_FUNARG CFset_cadddr;
void Fset_cdaaar(CL_FORM *base);
void Fset_cdaadr(CL_FORM *base);
void Fset_cdadar(CL_FORM *base);
void Fset_cdaddr(CL_FORM *base);
void Fset_cddaar(CL_FORM *base);
void Fset_cddadr(CL_FORM *base);
void Fset_cdddar(CL_FORM *base);
void Fset_cddddr(CL_FORM *base);
void Ftree_equal(CL_FORM *base, int nargs);
void Fendp(CL_FORM *base);
void Flist_length(CL_FORM *base);
void Fnth(CL_FORM *base);
void Fset_nth(CL_FORM *base);
extern GLOBAL_FUNARG CFset_nth;
void Ffirst(CL_FORM *base);
void Frest(CL_FORM *base);
void Fsecond(CL_FORM *base);
void Fthird(CL_FORM *base);
extern GLOBAL_FUNARG CFthird;
void Ffourth(CL_FORM *base);
void Ffifth(CL_FORM *base);
void Fsixth(CL_FORM *base);
void Fseventh(CL_FORM *base);
void Feighth(CL_FORM *base);
void Fninth(CL_FORM *base);
void Ftenth(CL_FORM *base);
void Fset_first(CL_FORM *base);
void Fset_rest(CL_FORM *base);
void Fset_second(CL_FORM *base);
void Fset_third(CL_FORM *base);
void Fset_fourth(CL_FORM *base);
void Fset_fifth(CL_FORM *base);
void Fset_sixth(CL_FORM *base);
void Fset_seventh(CL_FORM *base);
void Fset_eighth(CL_FORM *base);
void Fset_ninth(CL_FORM *base);
void Fset_tenth(CL_FORM *base);
void Fnthcdr(CL_FORM *base);
void Flast(CL_FORM *base, int nargs);
void Fmake_list(CL_FORM *base, int nargs);
void Fcopy_list(CL_FORM *base);
void Fcopy_alist(CL_FORM *base);
void Fcopy_tree(CL_FORM *base);
void Frevappend(CL_FORM *base);
void Fnconc(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFnconc;
void Fnreconc(CL_FORM *base);
void Fbutlast(CL_FORM *base, int nargs);
void Fnbutlast(CL_FORM *base, int nargs);
void Fldiff(CL_FORM *base);
void Frplaca(CL_FORM *base);
void Frplacd(CL_FORM *base);
void Fsubst(CL_FORM *base, int nargs);
void Fsubst_if(CL_FORM *base, int nargs);
void Fsubst_if_not(CL_FORM *base, int nargs);
void Fnsubst(CL_FORM *base, int nargs);
void Fnsubst_if(CL_FORM *base, int nargs);
void Fnsubst_if_not(CL_FORM *base, int nargs);
void Fsublis(CL_FORM *base, int nargs);
void Fnsublis(CL_FORM *base, int nargs);
void Fmember(CL_FORM *base, int nargs);
void Fmember_if(CL_FORM *base, int nargs);
void Fmember_if_not(CL_FORM *base, int nargs);
void Ftailp(CL_FORM *base);
void Fadjoin(CL_FORM *base, int nargs);
void Funion(CL_FORM *base, int nargs);
void Fnunion(CL_FORM *base, int nargs);
void Fintersection(CL_FORM *base, int nargs);
void Fset_difference(CL_FORM *base, int nargs);
void Fsubsetp(CL_FORM *base, int nargs);
void Facons(CL_FORM *base);
void Fpairlis(CL_FORM *base, int nargs);
void Fassoc(CL_FORM *base, int nargs);
void Fassoc_if(CL_FORM *base, int nargs);
void Fassoc_if_not(CL_FORM *base, int nargs);
void Frassoc(CL_FORM *base, int nargs);
void Frassoc_if(CL_FORM *base, int nargs);
void Frassoc_if_not(CL_FORM *base, int nargs);
void Fchar(CL_FORM *base);
void Fset_char(CL_FORM *base);
void Fschar(CL_FORM *base);
void Fset_schar(CL_FORM *base);
extern GLOBAL_FUNARG CFset_schar;
void FstringE(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFstringE;
void Fstring_equal(CL_FORM *base, int nargs);
void FstringL(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFstringL;
void FstringG(CL_FORM *base, int nargs);
void FstringLE(CL_FORM *base, int nargs);
void FstringGE(CL_FORM *base, int nargs);
void FstringNE(CL_FORM *base, int nargs);
void Fstring_lessp(CL_FORM *base, int nargs);
void Fstring_greaterp(CL_FORM *base, int nargs);
void Fstring_not_greaterp(CL_FORM *base, int nargs);
void Fstring_not_lessp(CL_FORM *base, int nargs);
void Fstring_not_equal(CL_FORM *base, int nargs);
void Fmake_string(CL_FORM *base, int nargs);
void Fstring_trim(CL_FORM *base);
void Fstring_left_trim(CL_FORM *base);
void Fstring_right_trim(CL_FORM *base);
void Fstring_upcase(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFstring_upcase;
void Fstring_downcase(CL_FORM *base, int nargs);
extern GLOBAL_FUNARG CFstring_downcase;
void Fstring_capitalize(CL_FORM *base, int nargs);
void Fnstring_upcase(CL_FORM *base, int nargs);
void Fnstring_downcase(CL_FORM *base, int nargs);
void Fnstring_capitalize(CL_FORM *base, int nargs);
void Fstring(CL_FORM *base);
void Fequal(CL_FORM *base);
extern GLOBAL_FUNARG CFequal;
void Fequalp(CL_FORM *base);
extern GLOBAL_FUNARG CFequalp;
void Fget(CL_FORM *base, int nargs);
void Fset_get(CL_FORM *base, int nargs);
void Fremprop(CL_FORM *base);
void get_prop(CL_FORM *base);
void set_prop(CL_FORM *base);
void Fgetf(CL_FORM *base, int nargs);
void remf_internal(CL_FORM *base);
void Fget_properties(CL_FORM *base);
void Fcopy_symbol(CL_FORM *base, int nargs);
void Fgensym(CL_FORM *base, int nargs);
void Fgentemp(CL_FORM *base, int nargs);
void Fkeywordp(CL_FORM *base);
void the_type_error(CL_FORM *base);
void Fy_or_n_p(CL_FORM *base, int nargs);
void Fyes_or_no_p(CL_FORM *base, int nargs);
void FFI_c_int(CL_FORM *base);
void FFI_lisp_character(CL_FORM *base);
void FFI_lisp_integer(CL_FORM *base);
void FFI_lisp_float(CL_FORM *base);
void startup(CL_FORM *base);
