/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void set_symbol_package(CL_FORM *base)
{
	if(CL_SYMBOLP(ARG(0)))
	{
		COPY(ARG(1), SYM_PACKAGE(ARG(0)));
		COPY(ARG(1), ARG(0));
	}
	else
	{
		if(CL_TRUEP(ARG(0)))
		{
			LOAD_NIL(ARG(0));
		}
		else
		{
			COPY(ARG(1), SYMVAL(Slisp, 682));	/* *NIL-PACKAGE* */
			COPY(SYMVAL(Slisp, 682), ARG(0));	/* *NIL-PACKAGE* */
		}
	}
}
