/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Finteger_decode_float(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	Fdecode_float(ARG(1));
	COPY(&mv_buf[0], ARG(2));
	COPY(&mv_buf[1], ARG(3));
	{
		int nargs;
		nargs = 3;
		mv_count = 1;
		{
			switch(nargs)
			{
				case 0:
				LOAD_NIL(ARG(1));
				case 1:
				LOAD_NIL(ARG(2));
				case 2:
				LOAD_NIL(ARG(3));
				nargs = 3;
			}
			COPY(SYMVAL(Slisp, 333), ARG(4));	/* I-D-F-FAKTOR */
			COPY(ARG(1), ARG(5));
			Fmult(ARG(4), 2);
			LOAD_SMALLFIXNUM(1, ARG(5));
			LOAD_SMALLFIXNUM(0, ARG(6));
			rt_convert_to_int(ARG(4));
			mv_count = 1;
			COPY(ARG(2), ARG(5));
			COPY(SYMVAL(Slisp, 332), ARG(6));	/* FLOAT-SIGNIFICAND-LENGTH */
			Fminus(ARG(5), 2);
			LOAD_SMALLFIXNUM(1, ARG(6));
			COPY(ARG(3), ARG(7));
			COPY(ARG(6), ARG(8));
			LOAD_SMALLFIXNUM(0, ARG(9));
			rt_convert_to_int(ARG(7));
			mv_count = 1;
			COPY(ARG(7), ARG(6));
			COPY(ARG(4), ARG(0));
			COPY(ARG(5), &mv_buf[0]);
			COPY(ARG(6), &mv_buf[1]);
			mv_count = 3;
		}
	}
}
