/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Ffloat_precision(CL_FORM *base)
{
	COPY(SYMVAL(Slisp, 332), ARG(0));	/* FLOAT-SIGNIFICAND-LENGTH */
}
