/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void get_token_string(CL_FORM *base)
{
	COPY(SYMVAL(Slisp, 440), ARG(0));	/* *FILL-POINTER* */
	LOAD_CHAR(ARG(1), ' ', ARG(1));
	make_string1(ARG(0));
	LOAD_SMALLFIXNUM(0, ARG(1));
	M1_1:;
	COPY(ARG(1), ARG(2));
	COPY(SYMVAL(Slisp, 440), ARG(3));	/* *FILL-POINTER* */
	Fnumeql(ARG(2), 2);
	if(CL_TRUEP(ARG(2)))
	{
		goto RETURN1;
	}
	COPY(SYMVAL(Slisp, 439), ARG(2));	/* *TOKEN* */
	COPY(ARG(1), ARG(3));
	Fschar(ARG(2));
	COPY(ARG(0), ARG(3));
	COPY(ARG(1), ARG(4));
	Fset_schar(ARG(2));
	F1plus(ARG(1));
	goto M1_1;
	RETURN1:;
}
