/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void vector_nreverse(CL_FORM *base)
{
	LOAD_SMALLFIXNUM(0, ARG(1));
	COPY(ARG(0), ARG(2));
	Flength(ARG(2));
	F1minus(ARG(2));
	LOAD_NIL(ARG(3));
	M1_1:;
	COPY(ARG(1), ARG(4));
	COPY(ARG(2), ARG(5));
	Fge(ARG(4), 2);
	if(CL_TRUEP(ARG(4)))
	{
		goto RETURN1;
	}
	COPY(ARG(0), ARG(4));
	COPY(ARG(1), ARG(5));
	if(CL_LISTP(ARG(4)))
	{
		COPY(ARG(5), ARG(6));
		COPY(ARG(4), ARG(7));
		COPY(ARG(6), ARG(8));
		COPY(ARG(7), ARG(9));
		Fnthcdr(ARG(8));
		if(CL_CONSP(ARG(8)))
		{
			COPY(GET_CAR(ARG(8)), ARG(3));
		}
		else
		{
			if(CL_TRUEP(ARG(8)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(3));	/* ~a is not a list */
				COPY(ARG(8), ARG(4));
				Ferror(ARG(3), 2);
			}
			else
			{
				LOAD_NIL(ARG(3));
			}
		}
	}
	else
	{
		COPY(ARG(4), ARG(3));
		COPY(ARG(5), ARG(4));
		Frow_major_aref(ARG(3));
	}
	if(CL_LISTP(ARG(0)))
	{
		COPY(ARG(2), ARG(4));
		COPY(ARG(0), ARG(5));
		Fnthcdr(ARG(4));
		if(CL_CONSP(ARG(4)))
		{
			COPY(GET_CAR(ARG(4)), ARG(4));
		}
		else
		{
			if(CL_TRUEP(ARG(4)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(5));	/* ~a is not a list */
				COPY(ARG(4), ARG(6));
				Ferror(ARG(5), 2);
			}
			else
			{
				LOAD_NIL(ARG(4));
			}
		}
	}
	else
	{
		COPY(ARG(0), ARG(4));
		COPY(ARG(2), ARG(5));
		Frow_major_aref(ARG(4));
	}
	COPY(ARG(4), ARG(5));
	COPY(ARG(0), ARG(6));
	COPY(ARG(1), ARG(7));
	Fset_elt(ARG(5));
	COPY(ARG(3), ARG(4));
	COPY(ARG(0), ARG(5));
	COPY(ARG(2), ARG(6));
	Fset_elt(ARG(4));
	COPY(ARG(1), ARG(4));
	F1plus(ARG(4));
	COPY(ARG(2), ARG(5));
	F1minus(ARG(5));
	COPY(ARG(5), ARG(2));
	COPY(ARG(4), ARG(1));
	goto M1_1;
	RETURN1:;
}
