/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void FFI_c_unsigned_char_p(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	c_unsigned_char_p(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		COPY(ARG(1), ARG(0));
	}
	else
	{
		rt_check_unsigned_char(ARG(0));
	}
}
