/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

static void Z67_lambda(CL_FORM *base);
static void Z68_lambda(CL_FORM *base);
static void Z69_lambda(CL_FORM *base);
static void Z70_lambda(CL_FORM *base);
static void Z71_lambda(CL_FORM *base);

void make_string_output_stream1(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(0), ARG(1));
	LOAD_SMALLFIXNUM(0, ARG(1));
	GEN_HEAPVAR(ARG(1), ARG(2));
	LOAD_SYMBOL(SYMBOL(Slisp, 102), ARG(2));	/* STRING-OUTPUT */
	{
		GEN_CLOSURE(array, ARG(3), 5, Z71_lambda, 1);
		COPY(ARG(0), &array[3]);
		COPY(ARG(1), &array[4]);
		LOAD_CLOSURE(array, ARG(3));
	}
	COPY(ARG(3), ARG(3));
	{
		GEN_CLOSURE(array, ARG(4), 4, Z70_lambda, 0);
		COPY(ARG(1), &array[3]);
		LOAD_CLOSURE(array, ARG(4));
	}
	COPY(ARG(4), ARG(4));
	{
		GEN_CLOSURE(array, ARG(5), 4, Z69_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(5));
	}
	COPY(ARG(5), ARG(5));
	{
		GEN_CLOSURE(array, ARG(6), 4, Z68_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(6));
	}
	COPY(ARG(6), ARG(6));
	{
		GEN_CLOSURE(array, ARG(7), 4, Z67_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(7));
	}
	COPY(ARG(7), ARG(7));
	LOAD_GLOBFUN(&Cclose1, ARG(8));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(9));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(10));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(11));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(12));	/* STREAM */
	COPY(ARG(2), ARG(13));
	COPY(ARG(7), ARG(14));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(15));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(16));
	COPY(ARG(3), ARG(17));
	COPY(ARG(4), ARG(18));
	COPY(ARG(5), ARG(19));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(20));
	COPY(ARG(6), ARG(21));
	LOAD_GLOBFUN(&Cclose1, ARG(22));
	rt_make_struct(ARG(12), 11);
	COPY(ARG(12), ARG(0));
}

static void Z67_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	Flength(ARG(1));
	LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(2));	/* CHARACTER */
	LOAD_NIL(ARG(3));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(4));
	LOAD_NIL(ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	LOAD_SMALLFIXNUM(0, ARG(8));
	LOAD_NIL(ARG(9));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(10));	/* T */
	make_array1(ARG(1));
	LOAD_SMALLFIXNUM(0, ARG(2));
	LOAD_SMALLFIXNUM(3, ARG(3));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(5));	/* COMPLEX-VECTOR */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(ARG(2), OFFSET(AR_BASE(GET_FORM(INDIRECT(GET_FORM(ARG(0)) + 3))), GET_FIXNUM(ARG(3)) + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(4));	/* NO_STRUCT */
		COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(6));	/* COMPLEX-VECTOR */
		Ferror(ARG(4), 3);
	}
	COPY(ARG(1), ARG(0));
}

static void Z68_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	Flength(ARG(1));
	COPY(ARG(1), ARG(0));
}

static void Z69_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	Flength(ARG(1));
	COPY(ARG(1), ARG(0));
}

static void Z70_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(0));
}

static void Z71_lambda(CL_FORM *base)
{
	if(CL_CHARP(ARG(1)) && GET_CHAR(ARG(1)) == '\n')
	{
		LOAD_SMALLFIXNUM(0, INDIRECT(GET_FORM(ARG(0)) + 4));
	}
	else
	{
		COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(2));
		F1plus(ARG(2));
		COPY(ARG(2), INDIRECT(GET_FORM(ARG(0)) + 4));
	}
	COPY(ARG(1), ARG(2));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(3));
	LOAD_NIL(ARG(4));
	vector_push_extend1(ARG(2));
	COPY(ARG(2), ARG(0));
}
