/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fset_hash_table_size(CL_FORM *base)
{
	LOAD_SMALLFIXNUM(0, ARG(2));
	LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(3));	/* HASH-TABLE */
	rt_set_struct_ref(ARG(0));
}
