/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Csemicolon_reader, semicolon_reader, 2);

void semicolon_reader(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	LOAD_NIL(ARG(3));
	LOAD_NIL(ARG(4));
	LOAD_NIL(ARG(5));
	read_line1(ARG(2));
	mv_count = 1;
	LOAD_NIL(ARG(0));
	mv_count = 0;
}
