/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

static void Z96_lambda(CL_FORM *base);
static void Z97_lambda(CL_FORM *base);
static void Z98_lambda(CL_FORM *base);
static void Z99_lambda(CL_FORM *base);
static void Z100_lambda(CL_FORM *base);
static void Z101_lambda(CL_FORM *base);

void make_file_input_stream(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(0), ARG(2));
	LOAD_SYMBOL(SYMBOL(Slisp, 90), ARG(2));	/* FILE-INPUT */
	{
		GEN_CLOSURE(array, ARG(3), 4, Z101_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(3));
	}
	COPY(ARG(3), ARG(3));
	{
		GEN_CLOSURE(array, ARG(4), 4, Z100_lambda, 1);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(4));
	}
	COPY(ARG(4), ARG(4));
	{
		GEN_CLOSURE(array, ARG(5), 4, Z99_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(5));
	}
	COPY(ARG(5), ARG(5));
	{
		GEN_CLOSURE(array, ARG(6), 4, Z98_lambda, 1);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(6));
	}
	COPY(ARG(6), ARG(6));
	{
		GEN_CLOSURE(array, ARG(7), 4, Z97_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(7));
	}
	COPY(ARG(7), ARG(7));
	{
		GEN_CLOSURE(array, ARG(8), 4, Z96_lambda, 1);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(8));
	}
	COPY(ARG(8), ARG(8));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(9));
	LOAD_GLOBFUN(&Cnil_fun, ARG(10));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(11));	/* STREAM */
	COPY(ARG(2), ARG(12));
	COPY(ARG(1), ARG(13));
	COPY(ARG(3), ARG(14));
	COPY(ARG(4), ARG(15));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(16));
	LOAD_GLOBFUN(&Cnil_fun, ARG(17));
	COPY(ARG(5), ARG(18));
	COPY(ARG(6), ARG(19));
	COPY(ARG(7), ARG(20));
	COPY(ARG(8), ARG(21));
	rt_make_struct(ARG(11), 11);
	COPY(ARG(11), ARG(0));
}

static void Z96_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(2));
	c_fclose(ARG(2));
	COPY(ARG(1), ARG(2));
	close1(ARG(2));
	COPY(ARG(2), ARG(0));
}

static void Z97_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	c_file_length(ARG(1));
	COPY(ARG(1), ARG(0));
}

static void Z98_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(2));
	COPY(ARG(1), ARG(3));
	c_fseek(ARG(2));
	COPY(ARG(2), ARG(0));
}

static void Z99_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	c_ftell(ARG(1));
	COPY(ARG(1), ARG(0));
}

static void Z100_lambda(CL_FORM *base)
{
	COPY(ARG(1), ARG(2));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(3));
	c_ungetc(ARG(2));
	COPY(ARG(2), ARG(0));
}

static void Z101_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	c_fgetc(ARG(1));
	COPY(ARG(1), ARG(0));
}
