/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XImake_plain_vector[];
extern CL_INIT XFmake_plain_vector[];
CL_INIT Kmake_plain_vector[] =
{
	MAKE_STRING(40, "ecase: the value ~a is not a legal value"),	/* 0 */
};

void make_plain_vector(CL_FORM *base)
{
	LOAD_SMALLFIXNUM(0, ARG(3));
	if(EQL(ARG(1), ARG(3)))
	{
		rt_make_vector_t(ARG(0));
	}
	else
	{
		LOAD_SMALLFIXNUM(1, ARG(3));
		if(EQL(ARG(1), ARG(3)))
		{
			rt_make_vector_fixnum(ARG(0));
		}
		else
		{
			LOAD_SMALLFIXNUM(2, ARG(3));
			if(EQL(ARG(1), ARG(3)))
			{
				rt_make_vector_float(ARG(0));
			}
			else
			{
				LOAD_SMALLFIXNUM(3, ARG(3));
				if(EQL(ARG(1), ARG(3)))
				{
					LOAD_CHAR(ARG(1), ' ', ARG(1));
					rt_make_vector_char(ARG(0));
				}
				else
				{
					LOAD_SMALLFIXNUM(4, ARG(3));
					if(EQL(ARG(1), ARG(3)))
					{
						rt_make_vector_bit(ARG(0));
					}
					else
					{
						LOAD_SMSTR((CL_FORM *)&Kmake_plain_vector[0], ARG(0));	/* ecase: the value ~a is not a legal value */
						Ferror(ARG(0), 2);
					}
				}
			}
		}
	}
}
