/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void list_substitute(CL_FORM *base)
{
	LOAD_NIL(ARG(8));
	Flist(ARG(8), 1);
	LOAD_NIL(ARG(9));
	COPY(ARG(8), ARG(10));
	COPY(ARG(2), ARG(11));
	LOAD_SMALLFIXNUM(0, ARG(12));
	M1_1:;
	COPY(ARG(12), ARG(13));
	COPY(ARG(4), ARG(14));
	Fnumeql(ARG(13), 2);
	if(CL_TRUEP(ARG(13)))
	{
		goto RETURN1;
	}
	COPY(ARG(10), ARG(13));
	COPY(ARG(11), ARG(14));
	if(CL_CONSP(ARG(14)))
	{
		COPY(GET_CAR(ARG(14)), ARG(14));
	}
	else
	{
		if(CL_TRUEP(ARG(14)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(15));	/* ~a is not a list */
			COPY(ARG(14), ARG(16));
			Ferror(ARG(15), 2);
		}
		else
		{
			LOAD_NIL(ARG(14));
		}
	}
	Flist(ARG(14), 1);
	if(CL_CONSP(ARG(13)))
	{
		COPY(ARG(14), GET_CDR(ARG(13)));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[235], ARG(15));	/* ~a is not a cons */
		COPY(ARG(13), ARG(16));
		Ferror(ARG(15), 2);
	}
	if(CL_CONSP(ARG(13)))
	{
		COPY(GET_CDR(ARG(13)), ARG(10));
	}
	else
	{
		if(CL_TRUEP(ARG(13)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(14));	/* ~a is not a list */
			COPY(ARG(13), ARG(15));
			Ferror(ARG(14), 2);
		}
		else
		{
			LOAD_NIL(ARG(10));
		}
	}
	COPY(ARG(11), ARG(13));
	if(CL_CONSP(ARG(13)))
	{
		COPY(GET_CDR(ARG(13)), ARG(11));
	}
	else
	{
		if(CL_TRUEP(ARG(13)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(14));	/* ~a is not a list */
			COPY(ARG(13), ARG(15));
			Ferror(ARG(14), 2);
		}
		else
		{
			LOAD_NIL(ARG(11));
		}
	}
	F1plus(ARG(12));
	goto M1_1;
	RETURN1:;
	COPY(ARG(4), ARG(12));
	M2_1:;
	COPY(ARG(12), ARG(13));
	COPY(ARG(5), ARG(14));
	Fnumeql(ARG(13), 2);
	if(CL_TRUEP(ARG(13)))
	{
		goto THEN1;
	}
	else
	{
		if(CL_TRUEP(ARG(11)))
		{
			LOAD_NIL(ARG(14));
		}
		else
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(14));	/* T */
		}
		if(CL_TRUEP(ARG(14)))
		{
			goto THEN1;
		}
		else
		{
			COPY(ARG(6), ARG(15));
			Fzerop(ARG(15));
		}
	}
	if(CL_TRUEP(ARG(15)))
	{
		THEN1:;
		goto RETURN2;
	}
	COPY(ARG(11), ARG(13));
	if(CL_CONSP(ARG(13)))
	{
		COPY(GET_CAR(ARG(13)), ARG(9));
	}
	else
	{
		if(CL_TRUEP(ARG(13)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(14));	/* ~a is not a list */
			COPY(ARG(13), ARG(15));
			Ferror(ARG(14), 2);
		}
		else
		{
			LOAD_NIL(ARG(9));
		}
	}
	COPY(ARG(10), ARG(13));
	COPY(ARG(3), ARG(14));
	COPY(ARG(1), ARG(15));
	if(CL_TRUEP(ARG(7)))
	{
		COPY(ARG(7), ARG(16));
		COPY(ARG(9), ARG(17));
		Ffuncall(ARG(16), 2);
		mv_count = 1;
	}
	else
	{
		COPY(ARG(9), ARG(16));
	}
	Ffuncall(ARG(14), 3);
	mv_count = 1;
	if(CL_TRUEP(ARG(14)))
	{
		COPY(ARG(6), ARG(14));
		F1minus(ARG(14));
		COPY(ARG(14), ARG(6));
		COPY(ARG(0), ARG(14));
	}
	else
	{
		COPY(ARG(9), ARG(14));
	}
	Flist(ARG(14), 1);
	if(CL_CONSP(ARG(13)))
	{
		COPY(ARG(14), GET_CDR(ARG(13)));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[235], ARG(15));	/* ~a is not a cons */
		COPY(ARG(13), ARG(16));
		Ferror(ARG(15), 2);
	}
	if(CL_CONSP(ARG(13)))
	{
		COPY(GET_CDR(ARG(13)), ARG(10));
	}
	else
	{
		if(CL_TRUEP(ARG(13)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(14));	/* ~a is not a list */
			COPY(ARG(13), ARG(15));
			Ferror(ARG(14), 2);
		}
		else
		{
			LOAD_NIL(ARG(10));
		}
	}
	COPY(ARG(11), ARG(13));
	if(CL_CONSP(ARG(13)))
	{
		COPY(GET_CDR(ARG(13)), ARG(11));
	}
	else
	{
		if(CL_TRUEP(ARG(13)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(14));	/* ~a is not a list */
			COPY(ARG(13), ARG(15));
			Ferror(ARG(14), 2);
		}
		else
		{
			LOAD_NIL(ARG(11));
		}
	}
	F1plus(ARG(12));
	goto M2_1;
	RETURN2:;
	M3_1:;
	if(CL_TRUEP(ARG(11)))
	{
	}
	else
	{
		goto RETURN3;
	}
	COPY(ARG(10), ARG(12));
	COPY(ARG(11), ARG(13));
	if(CL_CONSP(ARG(13)))
	{
		COPY(GET_CAR(ARG(13)), ARG(13));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(14));	/* ~a is not a list */
		COPY(ARG(13), ARG(15));
		Ferror(ARG(14), 2);
	}
	Flist(ARG(13), 1);
	if(CL_CONSP(ARG(12)))
	{
		COPY(ARG(13), GET_CDR(ARG(12)));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[235], ARG(14));	/* ~a is not a cons */
		COPY(ARG(12), ARG(15));
		Ferror(ARG(14), 2);
	}
	if(CL_CONSP(ARG(12)))
	{
		COPY(GET_CDR(ARG(12)), ARG(10));
	}
	else
	{
		if(CL_TRUEP(ARG(12)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(13));	/* ~a is not a list */
			COPY(ARG(12), ARG(14));
			Ferror(ARG(13), 2);
		}
		else
		{
			LOAD_NIL(ARG(10));
		}
	}
	COPY(ARG(11), ARG(12));
	if(CL_CONSP(ARG(12)))
	{
		COPY(GET_CDR(ARG(12)), ARG(11));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(11));	/* ~a is not a list */
		Ferror(ARG(11), 2);
	}
	goto M3_1;
	RETURN3:;
	COPY(GET_CDR(ARG(8)), ARG(0));
}
