/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XIunix_namestring1[];
extern CL_INIT XFunix_namestring1[];
CL_INIT Kunix_namestring1[] =
{
	MAKE_STRING(26, "~S is ambiguous:~{~%  ~A~}"),	/* 0 */
};

static void Z63_g643(CL_FORM *base);

void unix_namestring1(CL_FORM *base)
{
	LOAD_NIL(ARG(2));
	LOAD_NIL(ARG(3));
	ALLOC_CONS(ARG(4), ARG(2), ARG(3), ARG(2));
	GEN_HEAPVAR(ARG(2), ARG(3));
	{
		GEN_CLOSURE(array, ARG(3), 4, Z63_g643, 1);
		COPY(ARG(2), &array[3]);
		LOAD_CLOSURE(array, ARG(3));
	}
	COPY(ARG(0), ARG(4));
	Fpathname(ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(5));	/* T */
	COPY(ARG(3), ARG(6));
	Penumerate_matches(ARG(4));
	mv_count = 1;
	COPY(GET_CAR(INDIRECT(ARG(2))), ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		if(CL_CONSP(ARG(3)))
		{
			bool_result = CL_TRUEP(GET_CDR(ARG(3)));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(4));	/* ~a is not a list */
			COPY(ARG(3), ARG(5));
			Ferror(ARG(4), 2);
		}
		if(bool_result)
		{
			LOAD_SMSTR((CL_FORM *)&Kunix_namestring1[0], ARG(4));	/* ~S is ambiguous:~{~%  ~A~} */
			COPY(ARG(0), ARG(5));
			COPY(ARG(3), ARG(6));
			Ferror(ARG(4), 3);
		}
		if(CL_CONSP(ARG(3)))
		{
			COPY(GET_CAR(ARG(3)), ARG(0));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(0));	/* ~a is not a list */
			COPY(ARG(3), ARG(1));
			Ferror(ARG(0), 2);
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}

static void Z63_g643(CL_FORM *base)
{
	COPY(ARG(1), ARG(2));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(3));
	add_q(ARG(2));
	COPY(ARG(2), ARG(0));
}
