/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fset_slot_value(CL_FORM *base)
{
	if(CL_INSTANCEP(ARG(1)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), -1 + 1), ARG(3));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[216], ARG(3));	/* ~S ist not a valid argument for CLASS-OF, ~
              these have been restricted to instances of user-defined-classes. */
		COPY(ARG(1), ARG(4));
		Ferror(ARG(3), 2);
	}
	COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 3 + 1), ARG(3));
	LOAD_GLOBFUN(&CFthird, ARG(4));
	LOAD_NIL(ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	LOAD_SMALLFIXNUM(0, ARG(8));
	COPY(SYMVAL(Slisp, 0), ARG(9));	/* MOST-POSITIVE-FIXNUM */
	if(CL_LISTP(ARG(3)))
	{
		COPY(ARG(2), ARG(10));
		COPY(ARG(3), ARG(11));
		LOAD_NIL(ARG(12));
		LOAD_NIL(ARG(13));
		LOAD_NIL(ARG(14));
		COPY(ARG(8), ARG(15));
		COPY(ARG(9), ARG(16));
		LOAD_GLOBFUN(&CFthird, ARG(17));
		list_position(ARG(10));
		COPY(ARG(10), ARG(4));
	}
	else
	{
		COPY(ARG(2), ARG(10));
		COPY(ARG(3), ARG(11));
		LOAD_NIL(ARG(12));
		LOAD_NIL(ARG(13));
		LOAD_NIL(ARG(14));
		COPY(ARG(8), ARG(15));
		COPY(ARG(9), ARG(16));
		LOAD_GLOBFUN(&CFthird, ARG(17));
		vector_position(ARG(10));
		COPY(ARG(10), ARG(4));
	}
	if(CL_TRUEP(ARG(4)))
	{
		COPY(ARG(0), OFFSET(AR_BASE(GET_FORM(ARG(1))), GET_FIXNUM(ARG(4)) + 1));
	}
	else
	{
		if(CL_INSTANCEP(ARG(1)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), -1 + 1), ARG(5));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[216], ARG(5));	/* ~S ist not a valid argument for CLASS-OF, ~
              these have been restricted to instances of user-defined-classes. */
			COPY(ARG(1), ARG(6));
			Ferror(ARG(5), 2);
		}
		LOAD_CONS((CL_FORM *)&KClisp[118], ARG(6));
		LOAD_SMSTR((CL_FORM *)&KClisp[212], ARG(7));	/* ~S: The slot ~s is missing from the object ~s of class ~s. */
		COPY(ARG(6), ARG(8));
		COPY(ARG(2), ARG(9));
		COPY(ARG(1), ARG(10));
		COPY(ARG(5), ARG(11));
		Ferror(ARG(7), 5);
	}
}
