/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void rt_set_struct_printer(CL_FORM *base)
{
	LOAD_SYMBOL(SYMBOL(Slisp, 341), ARG(2));	/* STRUCT-PRINTER */
	Fset_get(ARG(0), 3);
}
