/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XImake_pathname1[];
extern CL_INIT XFmake_pathname1[];
CL_INIT Kmake_pathname1[] =
{
	MAKE_STRING(44, "etypecase: the value ~a is not a legal value"),	/* 0 */
	MAKE_STRING(40, "ecase: the value ~a is not a legal value"),	/* 2 */
	MAKE_STRING(30, ":WILD-INFERIORS not supported."),	/* 4 */
	MAKE_CONS,	/* 6 CONS(6) */
	MAKE_SYMREF(SYMBOL(Slisp, 265)),	/* UP */
	MAKE_CONSREF(&Kmake_pathname1[9]),
	MAKE_CONS,	/* CONS(9) */
	MAKE_SYMREF(SYMBOL(Slisp, 258)),	/* BACK */
	MAKE_NIL,
	MAKE_STRING(43, "~S is not allowed as a directory component."),	/* 12 */
	MAKE_STRING(44, "etypecase: the value ~a is not a legal value"),	/* 14 */
};

void make_pathname1(CL_FORM *base)
{
	if(CL_TRUEP(ARG(6)))
	{
		COPY(ARG(6), ARG(14));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(15));	/* PATHNAME */
		rt_struct_typep(ARG(14));
		if(CL_TRUEP(ARG(14)))
		{
			COPY(ARG(6), ARG(14));
		}
		else
		{
			COPY(ARG(6), ARG(14));
			Fstringp(ARG(14));
			if(CL_TRUEP(ARG(14)))
			{
				COPY(ARG(6), ARG(14));
				LOAD_NIL(ARG(15));
				COPY(SYMVAL(Slisp, 231), ARG(16));	/* *DEFAULT-PATHNAME-DEFAULTS* */
				LOAD_SMALLFIXNUM(0, ARG(17));
				LOAD_NIL(ARG(18));
				LOAD_NIL(ARG(19));
				parse_namestring1(ARG(14));
				mv_count = 1;
			}
			else
			{
				COPY(ARG(6), ARG(14));
				LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(15));	/* STREAM */
				rt_struct_typep(ARG(14));
				if(CL_TRUEP(ARG(14)))
				{
					COPY(ARG(6), ARG(14));
					LOAD_NIL(ARG(15));
					file_name1(ARG(14));
					COPY(SYMVAL(Slisp, 231), ARG(15));	/* *DEFAULT-PATHNAME-DEFAULTS* */
					LOAD_SMALLFIXNUM(0, ARG(16));
					COPY(ARG(14), ARG(17));
					LOAD_NIL(ARG(18));
					COPY(ARG(15), ARG(19));
					COPY(ARG(16), ARG(20));
					LOAD_NIL(ARG(21));
					LOAD_NIL(ARG(22));
					parse_namestring1(ARG(17));
					mv_count = 1;
					COPY(ARG(17), ARG(14));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&Kmake_pathname1[0], ARG(14));	/* etypecase: the value ~a is not a legal value */
					COPY(ARG(6), ARG(15));
					Ferror(ARG(14), 2);
				}
			}
		}
	}
	else
	{
		LOAD_NIL(ARG(14));
	}
	if(CL_TRUEP(ARG(14)))
	{
		COPY(ARG(14), ARG(15));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(16));	/* PATHNAME */
		rt_struct_typep(ARG(15));
		if(CL_TRUEP(ARG(15)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 0 + 1), ARG(15));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(15));	/* NO_STRUCT */
			COPY(ARG(14), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(17));	/* PATHNAME */
			Ferror(ARG(15), 3);
		}
	}
	else
	{
		COPY(SYMVAL(Slisp, 231), ARG(15));	/* *DEFAULT-PATHNAME-DEFAULTS* */
		LOAD_SYMBOL(SYMBOL(Slisp, 267), ARG(16));	/* LOCAL */
		pathname_host1(ARG(15));
	}
	if(CL_TRUEP(ARG(8)))
	{
		COPY(ARG(0), ARG(16));
	}
	else
	{
		COPY(ARG(15), ARG(16));
	}
	if(CL_SYMBOLP(ARG(7)) && GET_SYMBOL(ARG(7)) == SYMBOL(Slisp, 269))	/* COMMON */
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(17));	/* T */
	}
	else
	{
		LOAD_NIL(ARG(17));
	}
	LOAD_NIL(ARG(18));
	if(CL_TRUEP(ARG(9)))
	{
		COPY(ARG(1), ARG(19));
	}
	else
	{
		if(CL_TRUEP(ARG(14)))
		{
			COPY(ARG(14), ARG(19));
			LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(20));	/* PATHNAME */
			rt_struct_typep(ARG(19));
			if(CL_TRUEP(ARG(19)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 1 + 1), ARG(19));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(19));	/* NO_STRUCT */
				COPY(ARG(14), ARG(20));
				LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(21));	/* PATHNAME */
				Ferror(ARG(19), 3);
			}
		}
		else
		{
			LOAD_NIL(ARG(19));
		}
	}
	COPY(ARG(2), ARG(20));
	if(CL_TRUEP(ARG(20)))
	{
		if(CL_LISTP(ARG(20)))
		{
			LOAD_NIL(ARG(21));
			LOAD_NIL(ARG(22));
			ALLOC_CONS(ARG(23), ARG(21), ARG(22), ARG(21));
			COPY(GET_CAR(ARG(20)), ARG(22));
			COPY(ARG(20), ARG(23));
			COPY(ARG(23), ARG(24));
			COPY(GET_CDR(ARG(24)), ARG(20));
			if(CL_SYMBOLP(ARG(22)) && GET_SYMBOL(ARG(22)) == SYMBOL(Slisp, 257))	/* ABSOLUTE */
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 257), ARG(23));	/* ABSOLUTE */
				COPY(ARG(21), ARG(24));
				add_q(ARG(23));
			}
			else
			{
				if(CL_SYMBOLP(ARG(22)) && GET_SYMBOL(ARG(22)) == SYMBOL(Slisp, 261))	/* RELATIVE */
				{
					LOAD_SYMBOL(SYMBOL(Slisp, 261), ARG(23));	/* RELATIVE */
					COPY(ARG(21), ARG(24));
					add_q(ARG(23));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&Kmake_pathname1[2], ARG(23));	/* ecase: the value ~a is not a legal value */
					COPY(ARG(22), ARG(24));
					Ferror(ARG(23), 2);
				}
			}
			LOAD_NIL(ARG(22));
			COPY(ARG(20), ARG(23));
			M1_1:;
			if(CL_ATOMP(ARG(23)))
			{
				LOAD_NIL(ARG(22));
				goto RETURN1;
			}
			COPY(ARG(23), ARG(24));
			COPY(GET_CAR(ARG(24)), ARG(22));
			if(CL_SYMBOLP(ARG(22)) && GET_SYMBOL(ARG(22)) == SYMBOL(Slisp, 262))	/* WILD */
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 248), ARG(24));	/* PATTERN */
				LOAD_SYMBOL(SYMBOL(Slisp, 263), ARG(25));	/* MULTI-CHAR-WILD */
				Flist(ARG(25), 1);
				rt_make_struct(ARG(24), 2);
				COPY(ARG(21), ARG(25));
				add_q(ARG(24));
			}
			else
			{
				if(CL_SYMBOLP(ARG(22)) && GET_SYMBOL(ARG(22)) == SYMBOL(Slisp, 264))	/* WILD-INFERIORS */
				{
					LOAD_SMSTR((CL_FORM *)&Kmake_pathname1[4], ARG(24));	/* :WILD-INFERIORS not supported. */
					Ferror(ARG(24), 1);
				}
				else
				{
					COPY(ARG(22), ARG(24));
					LOAD_CONS((CL_FORM *)&Kmake_pathname1[6], ARG(25));
					LOAD_NIL(ARG(26));
					LOAD_NIL(ARG(27));
					LOAD_NIL(ARG(28));
					member1(ARG(24));
					if(CL_TRUEP(ARG(24)))
					{
						COPY(ARG(22), ARG(24));
						COPY(ARG(21), ARG(25));
						add_q(ARG(24));
					}
					else
					{
						LOAD_BOOL(CL_SMSTRP(ARG(22)), ARG(24));
						if(CL_TRUEP(ARG(24)))
						{
							goto THEN1;
						}
						else
						{
							COPY(ARG(22), ARG(25));
							LOAD_SYMBOL(SYMBOL(Slisp, 248), ARG(26));	/* PATTERN */
							rt_struct_typep(ARG(25));
						}
						if(CL_TRUEP(ARG(25)))
						{
							THEN1:;
							COPY(ARG(22), ARG(24));
							COPY(ARG(17), ARG(25));
							maybe_diddle_case(ARG(24));
							mv_count = 1;
							COPY(ARG(21), ARG(25));
							add_q(ARG(24));
						}
						else
						{
							COPY(ARG(22), ARG(24));
							Fstringp(ARG(24));
							if(CL_TRUEP(ARG(24)))
							{
								COPY(ARG(22), ARG(24));
								LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(25));	/* SIMPLE-STRING */
								Fcoerce(ARG(24));
								COPY(ARG(17), ARG(25));
								maybe_diddle_case(ARG(24));
								mv_count = 1;
								COPY(ARG(21), ARG(25));
								add_q(ARG(24));
							}
							else
							{
								LOAD_SMSTR((CL_FORM *)&Kmake_pathname1[12], ARG(24));	/* ~S is not allowed as a directory component. */
								COPY(ARG(22), ARG(25));
								Ferror(ARG(24), 2);
							}
						}
					}
				}
			}
			COPY(ARG(23), ARG(24));
			COPY(GET_CDR(ARG(24)), ARG(23));
			goto M1_1;
			RETURN1:;
			COPY(GET_CAR(ARG(21)), ARG(20));
		}
		else
		{
			if(CL_SMSTRP(ARG(20)))
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 257), ARG(21));	/* ABSOLUTE */
				COPY(ARG(20), ARG(22));
				COPY(ARG(17), ARG(23));
				maybe_diddle_case(ARG(22));
				mv_count = 1;
				Flist(ARG(21), 2);
				COPY(ARG(21), ARG(20));
			}
			else
			{
				COPY(ARG(20), ARG(21));
				Fstringp(ARG(21));
				if(CL_TRUEP(ARG(21)))
				{
					LOAD_SYMBOL(SYMBOL(Slisp, 257), ARG(21));	/* ABSOLUTE */
					COPY(ARG(20), ARG(22));
					LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(23));	/* SIMPLE-STRING */
					Fcoerce(ARG(22));
					COPY(ARG(17), ARG(23));
					maybe_diddle_case(ARG(22));
					mv_count = 1;
					Flist(ARG(21), 2);
					COPY(ARG(21), ARG(20));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&Kmake_pathname1[14], ARG(21));	/* etypecase: the value ~a is not a legal value */
					COPY(ARG(20), ARG(22));
					Ferror(ARG(21), 2);
				}
			}
		}
	}
	else
	{
		LOAD_NIL(ARG(20));
	}
	if(CL_TRUEP(ARG(14)))
	{
		if(CL_TRUEP(ARG(10)))
		{
			goto ELSE2;
		}
		else
		{
			goto THEN3;
		}
	}
	else
	{
		goto ELSE2;
	}
	{
		THEN3:;
		COPY(ARG(20), ARG(21));
		COPY(ARG(14), ARG(22));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(23));	/* PATHNAME */
		rt_struct_typep(ARG(22));
		if(CL_TRUEP(ARG(22)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 2 + 1), ARG(22));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(22));	/* NO_STRUCT */
			COPY(ARG(14), ARG(23));
			LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(24));	/* PATHNAME */
			Ferror(ARG(22), 3);
		}
		COPY(ARG(18), ARG(23));
		merge_directories(ARG(21));
		COPY(ARG(21), ARG(20));
	}
	goto ENDIF4;
	{
		ELSE2:;
	}
	ENDIF4:;
	if(CL_SYMBOLP(ARG(3)) && GET_SYMBOL(ARG(3)) == SYMBOL(Slisp, 262))	/* WILD */
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 248), ARG(21));	/* PATTERN */
		LOAD_SYMBOL(SYMBOL(Slisp, 263), ARG(22));	/* MULTI-CHAR-WILD */
		Flist(ARG(22), 1);
		rt_make_struct(ARG(21), 2);
	}
	else
	{
		LOAD_BOOL(CL_SMSTRP(ARG(3)), ARG(21));
		if(CL_TRUEP(ARG(21)))
		{
			goto THEN5;
		}
		else
		{
			COPY(ARG(3), ARG(22));
			LOAD_SYMBOL(SYMBOL(Slisp, 248), ARG(23));	/* PATTERN */
			rt_struct_typep(ARG(22));
		}
		if(CL_TRUEP(ARG(22)))
		{
			THEN5:;
			COPY(ARG(3), ARG(21));
			COPY(ARG(17), ARG(22));
			maybe_diddle_case(ARG(21));
			mv_count = 1;
		}
		else
		{
			COPY(ARG(3), ARG(21));
			Fstringp(ARG(21));
			if(CL_TRUEP(ARG(21)))
			{
				COPY(ARG(3), ARG(21));
				LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(22));	/* SIMPLE-STRING */
				Fcoerce(ARG(21));
				COPY(ARG(17), ARG(22));
				maybe_diddle_case(ARG(21));
				mv_count = 1;
			}
			else
			{
				if(CL_TRUEP(ARG(11)))
				{
					COPY(ARG(3), ARG(21));
					COPY(ARG(17), ARG(22));
					maybe_diddle_case(ARG(21));
					mv_count = 1;
				}
				else
				{
					if(CL_TRUEP(ARG(14)))
					{
						COPY(ARG(14), ARG(21));
						LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(22));	/* PATHNAME */
						rt_struct_typep(ARG(21));
						if(CL_TRUEP(ARG(21)))
						{
							COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 3 + 1), ARG(21));
						}
						else
						{
							COPY(SYMVAL(Slisp, 342), ARG(21));	/* NO_STRUCT */
							COPY(ARG(14), ARG(22));
							LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(23));	/* PATHNAME */
							Ferror(ARG(21), 3);
						}
						COPY(ARG(18), ARG(22));
						maybe_diddle_case(ARG(21));
						mv_count = 1;
					}
					else
					{
						LOAD_NIL(ARG(21));
					}
				}
			}
		}
	}
	if(CL_SYMBOLP(ARG(4)) && GET_SYMBOL(ARG(4)) == SYMBOL(Slisp, 262))	/* WILD */
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 248), ARG(22));	/* PATTERN */
		LOAD_SYMBOL(SYMBOL(Slisp, 263), ARG(23));	/* MULTI-CHAR-WILD */
		Flist(ARG(23), 1);
		rt_make_struct(ARG(22), 2);
	}
	else
	{
		LOAD_BOOL(CL_SMSTRP(ARG(4)), ARG(22));
		if(CL_TRUEP(ARG(22)))
		{
			goto THEN6;
		}
		else
		{
			COPY(ARG(4), ARG(23));
			LOAD_SYMBOL(SYMBOL(Slisp, 248), ARG(24));	/* PATTERN */
			rt_struct_typep(ARG(23));
		}
		if(CL_TRUEP(ARG(23)))
		{
			THEN6:;
			COPY(ARG(4), ARG(22));
			COPY(ARG(17), ARG(23));
			maybe_diddle_case(ARG(22));
			mv_count = 1;
		}
		else
		{
			COPY(ARG(4), ARG(22));
			Fstringp(ARG(22));
			if(CL_TRUEP(ARG(22)))
			{
				COPY(ARG(4), ARG(22));
				LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(23));	/* SIMPLE-STRING */
				Fcoerce(ARG(22));
				COPY(ARG(17), ARG(23));
				maybe_diddle_case(ARG(22));
				mv_count = 1;
			}
			else
			{
				if(CL_TRUEP(ARG(12)))
				{
					COPY(ARG(4), ARG(22));
					COPY(ARG(17), ARG(23));
					maybe_diddle_case(ARG(22));
					mv_count = 1;
				}
				else
				{
					if(CL_TRUEP(ARG(14)))
					{
						COPY(ARG(14), ARG(22));
						LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(23));	/* PATHNAME */
						rt_struct_typep(ARG(22));
						if(CL_TRUEP(ARG(22)))
						{
							COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 4 + 1), ARG(22));
						}
						else
						{
							COPY(SYMVAL(Slisp, 342), ARG(22));	/* NO_STRUCT */
							COPY(ARG(14), ARG(23));
							LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(24));	/* PATHNAME */
							Ferror(ARG(22), 3);
						}
						COPY(ARG(18), ARG(23));
						maybe_diddle_case(ARG(22));
						mv_count = 1;
					}
					else
					{
						LOAD_NIL(ARG(22));
					}
				}
			}
		}
	}
	if(CL_TRUEP(ARG(13)))
	{
		COPY(ARG(5), ARG(23));
	}
	else
	{
		if(CL_TRUEP(ARG(14)))
		{
			COPY(ARG(14), ARG(23));
			LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(24));	/* PATHNAME */
			rt_struct_typep(ARG(23));
			if(CL_TRUEP(ARG(23)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 5 + 1), ARG(23));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(23));	/* NO_STRUCT */
				COPY(ARG(14), ARG(24));
				LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(25));	/* PATHNAME */
				Ferror(ARG(23), 3);
			}
		}
		else
		{
			LOAD_NIL(ARG(23));
		}
	}
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(0));	/* PATHNAME */
	COPY(ARG(16), ARG(1));
	COPY(ARG(19), ARG(2));
	COPY(ARG(20), ARG(3));
	COPY(ARG(21), ARG(4));
	COPY(ARG(22), ARG(5));
	COPY(ARG(23), ARG(6));
	rt_make_struct(ARG(0), 7);
}
