/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fadjustable_array_p(CL_FORM *base)
{
	complex_base_array_p(ARG(0));
}
