/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XIparse_namestring1[];
extern CL_INIT XFparse_namestring1[];
CL_INIT Kparse_namestring1[] =
{
	MAKE_STRING(44, "etypecase: the value ~a is not a legal value"),	/* 0 */
	MAKE_STRING(29, ":junk-allowed will be ignored"),	/* 2 */
	MAKE_STRING(28, "search lists not implemented"),	/* 4 */
	MAKE_STRING(2, ".."),	/* 6 */
	MAKE_STRING(44, "etypecase: the value ~a is not a legal value"),	/* 8 */
	MAKE_STRING(30, "Hosts do not match: ~S and ~S."),	/* 10 */
};

void parse_namestring1(CL_FORM *base)
{
	COPY(ARG(0), ARG(6));
	Fstringp(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(ARG(0), ARG(6));
		COPY(ARG(3), ARG(7));
		if(CL_TRUEP(ARG(4)))
		{
			COPY(ARG(4), ARG(8));
		}
		else
		{
			COPY(ARG(0), ARG(8));
			Flength(ARG(8));
		}
		if(CL_TRUEP(ARG(1)))
		{
			COPY(ARG(1), ARG(9));
		}
		else
		{
			COPY(ARG(2), ARG(9));
			LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(10));	/* PATHNAME */
			rt_struct_typep(ARG(9));
			if(CL_TRUEP(ARG(9)))
			{
				COPY(ARG(2), ARG(9));
			}
			else
			{
				COPY(ARG(2), ARG(9));
				Fstringp(ARG(9));
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(2), ARG(9));
					LOAD_NIL(ARG(10));
					COPY(SYMVAL(Slisp, 231), ARG(11));	/* *DEFAULT-PATHNAME-DEFAULTS* */
					LOAD_SMALLFIXNUM(0, ARG(12));
					LOAD_NIL(ARG(13));
					LOAD_NIL(ARG(14));
					parse_namestring1(ARG(9));
					mv_count = 1;
				}
				else
				{
					COPY(ARG(2), ARG(9));
					LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(10));	/* STREAM */
					rt_struct_typep(ARG(9));
					if(CL_TRUEP(ARG(9)))
					{
						COPY(ARG(2), ARG(9));
						LOAD_NIL(ARG(10));
						file_name1(ARG(9));
						COPY(SYMVAL(Slisp, 231), ARG(10));	/* *DEFAULT-PATHNAME-DEFAULTS* */
						LOAD_SMALLFIXNUM(0, ARG(11));
						COPY(ARG(9), ARG(12));
						LOAD_NIL(ARG(13));
						COPY(ARG(10), ARG(14));
						COPY(ARG(11), ARG(15));
						LOAD_NIL(ARG(16));
						LOAD_NIL(ARG(17));
						parse_namestring1(ARG(12));
						mv_count = 1;
						COPY(ARG(12), ARG(9));
					}
					else
					{
						LOAD_SMSTR((CL_FORM *)&Kparse_namestring1[0], ARG(9));	/* etypecase: the value ~a is not a legal value */
						COPY(ARG(2), ARG(10));
						Ferror(ARG(9), 2);
					}
				}
			}
			COPY(ARG(9), ARG(10));
			LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(11));	/* PATHNAME */
			rt_struct_typep(ARG(10));
			if(CL_TRUEP(ARG(10)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(9))), 0 + 1), ARG(9));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(10));	/* NO_STRUCT */
				COPY(ARG(9), ARG(11));
				LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(12));	/* PATHNAME */
				Ferror(ARG(10), 3);
			}
		}
		COPY(ARG(5), ARG(10));
		M1_1:;
		if(CL_TRUEP(ARG(10)))
		{
			LOAD_SMSTR((CL_FORM *)&Kparse_namestring1[2], ARG(0));	/* :junk-allowed will be ignored */
			Fwarn(ARG(0), 1);
		}
		else
		{
			if(CL_SMSTRP(ARG(6)))
			{
				COPY(ARG(7), ARG(11));
				COPY(ARG(11), ARG(12));
				COPY(ARG(8), ARG(13));
				Fnumneql(ARG(12), 2);
				if(CL_TRUEP(ARG(12)))
				{
					COPY(ARG(6), ARG(12));
					COPY(ARG(11), ARG(13));
					Fschar(ARG(12));
					LOAD_CHAR(ARG(13), '/', ARG(13));
					rt_charE(ARG(12));
				}
				else
				{
					LOAD_NIL(ARG(12));
				}
				if(CL_TRUEP(ARG(12)))
				{
					COPY(ARG(11), ARG(13));
					F1plus(ARG(13));
					COPY(ARG(13), ARG(11));
				}
				LOAD_NIL(ARG(13));
				LOAD_NIL(ARG(14));
				ALLOC_CONS(ARG(15), ARG(13), ARG(14), ARG(13));
				M2_1:;
				LOAD_CHAR(ARG(14), '/', ARG(14));
				LOAD_NIL(ARG(15));
				LOAD_NIL(ARG(16));
				LOAD_NIL(ARG(17));
				LOAD_NIL(ARG(18));
				if(CL_LISTP(ARG(6)))
				{
					LOAD_CHAR(ARG(14), '/', ARG(14));
					COPY(ARG(6), ARG(15));
					LOAD_NIL(ARG(16));
					LOAD_NIL(ARG(17));
					LOAD_NIL(ARG(18));
					COPY(ARG(11), ARG(19));
					COPY(ARG(8), ARG(20));
					LOAD_NIL(ARG(21));
					list_position(ARG(14));
				}
				else
				{
					LOAD_CHAR(ARG(14), '/', ARG(14));
					COPY(ARG(6), ARG(15));
					LOAD_NIL(ARG(16));
					LOAD_NIL(ARG(17));
					LOAD_NIL(ARG(18));
					COPY(ARG(11), ARG(19));
					COPY(ARG(8), ARG(20));
					LOAD_NIL(ARG(21));
					vector_position(ARG(14));
				}
				if(CL_TRUEP(ARG(14)))
				{
					COPY(ARG(14), ARG(16));
				}
				else
				{
					COPY(ARG(8), ARG(16));
				}
				ALLOC_CONS(ARG(17), ARG(11), ARG(16), ARG(15));
				COPY(ARG(13), ARG(16));
				add_q(ARG(15));
				if(CL_TRUEP(ARG(14)))
				{
				}
				else
				{
					goto RETURN2;
				}
				COPY(ARG(14), ARG(15));
				F1plus(ARG(15));
				COPY(ARG(15), ARG(11));
				goto M2_1;
				RETURN2:;
				COPY(ARG(12), ARG(11));
				COPY(ARG(13), ARG(12));
				COPY(GET_CAR(ARG(12)), ARG(12));
				COPY(ARG(12), &mv_buf[0]);
				mv_count = 2;
				COPY(&mv_buf[0], ARG(12));
				{
					int nargs;
					nargs = 2;
					mv_count = 1;
					{
						switch(nargs)
						{
							case 0:
							LOAD_NIL(ARG(11));
							case 1:
							LOAD_NIL(ARG(12));
							nargs = 2;
						}
						if(CL_TRUEP(ARG(11)))
						{
							LOAD_NIL(ARG(13));
						}
						else
						{
							if(CL_CONSP(ARG(12)))
							{
								COPY(GET_CAR(ARG(12)), ARG(13));
							}
							else
							{
								if(CL_TRUEP(ARG(12)))
								{
									LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(13));	/* ~a is not a list */
									COPY(ARG(12), ARG(14));
									Ferror(ARG(13), 2);
								}
								else
								{
									COPY(ARG(12), ARG(13));
								}
							}
							if(CL_CONSP(ARG(13)))
							{
								COPY(GET_CAR(ARG(13)), ARG(14));
							}
							else
							{
								if(CL_TRUEP(ARG(13)))
								{
									LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(14));	/* ~a is not a list */
									COPY(ARG(13), ARG(15));
									Ferror(ARG(14), 2);
								}
								else
								{
									COPY(ARG(13), ARG(14));
								}
							}
							if(CL_CONSP(ARG(13)))
							{
								COPY(GET_CDR(ARG(13)), ARG(15));
							}
							else
							{
								if(CL_TRUEP(ARG(13)))
								{
									LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(15));	/* ~a is not a list */
									COPY(ARG(13), ARG(16));
									Ferror(ARG(15), 2);
								}
								else
								{
									COPY(ARG(13), ARG(15));
								}
							}
							LOAD_NIL(ARG(16));
							COPY(ARG(14), ARG(17));
							M3_1:;
							COPY(ARG(17), ARG(18));
							COPY(ARG(15), ARG(19));
							Fnumeql(ARG(18), 2);
							if(CL_TRUEP(ARG(18)))
							{
								LOAD_NIL(ARG(18));
								COPY(ARG(14), ARG(19));
								COPY(ARG(18), ARG(14));
								COPY(ARG(19), &mv_buf[0]);
								mv_count = 2;
								goto RETURN3;
							}
							if(CL_TRUEP(ARG(16)))
							{
								LOAD_NIL(ARG(16));
							}
							else
							{
								COPY(ARG(6), ARG(18));
								COPY(ARG(17), ARG(19));
								Fschar(ARG(18));
								if(CL_CHARP(ARG(18)) && GET_CHAR(ARG(18)) == '\\')
								{
									LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(16));	/* T */
								}
								else
								{
									if(CL_CHARP(ARG(18)) && GET_CHAR(ARG(18)) == ':')
									{
										COPY(ARG(6), ARG(19));
										COPY(ARG(14), ARG(20));
										COPY(ARG(17), ARG(21));
										remove_backslashes(ARG(19));
										COPY(ARG(17), ARG(20));
										F1plus(ARG(20));
										COPY(ARG(19), ARG(14));
										COPY(ARG(20), &mv_buf[0]);
										mv_count = 2;
										goto RETURN3;
									}
								}
							}
							F1plus(ARG(17));
							goto M3_1;
							RETURN3:;
							COPY(&mv_buf[0], ARG(15));
							{
								int nargs;
								nargs = 2;
								mv_count = 1;
								{
									switch(nargs)
									{
										case 0:
										LOAD_NIL(ARG(14));
										case 1:
										LOAD_NIL(ARG(15));
										nargs = 2;
									}
									if(CL_TRUEP(ARG(14)))
									{
										LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(11));	/* T */
										if(CL_CONSP(ARG(13)))
										{
											COPY(ARG(15), GET_CAR(ARG(13)));
										}
										else
										{
											LOAD_SMSTR((CL_FORM *)&KClisp[229], ARG(16));	/* ~a is not a cons */
											COPY(ARG(13), ARG(17));
											Ferror(ARG(16), 2);
										}
									}
									COPY(ARG(14), ARG(13));
								}
							}
						}
						COPY(ARG(12), ARG(14));
						LOAD_SMALLFIXNUM(1, ARG(15));
						last1(ARG(14));
						if(CL_CONSP(ARG(14)))
						{
							COPY(GET_CAR(ARG(14)), ARG(14));
						}
						else
						{
							if(CL_TRUEP(ARG(14)))
							{
								LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(15));	/* ~a is not a list */
								COPY(ARG(14), ARG(16));
								Ferror(ARG(15), 2);
							}
							else
							{
								LOAD_NIL(ARG(14));
							}
						}
						if(CL_CONSP(ARG(14)))
						{
							COPY(GET_CAR(ARG(14)), ARG(15));
						}
						else
						{
							if(CL_TRUEP(ARG(14)))
							{
								LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(15));	/* ~a is not a list */
								COPY(ARG(14), ARG(16));
								Ferror(ARG(15), 2);
							}
							else
							{
								COPY(ARG(14), ARG(15));
							}
						}
						if(CL_CONSP(ARG(14)))
						{
							COPY(GET_CDR(ARG(14)), ARG(16));
						}
						else
						{
							if(CL_TRUEP(ARG(14)))
							{
								LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(16));	/* ~a is not a list */
								COPY(ARG(14), ARG(17));
								Ferror(ARG(16), 2);
							}
							else
							{
								COPY(ARG(14), ARG(16));
							}
						}
						COPY(ARG(15), ARG(17));
						COPY(ARG(16), ARG(18));
						Fnumeql(ARG(17), 2);
						if(CL_TRUEP(ARG(17)))
						{
							LOAD_NIL(ARG(14));
						}
						else
						{
							COPY(ARG(12), ARG(17));
							LOAD_SMALLFIXNUM(1, ARG(18));
							butlast1(ARG(17));
							COPY(ARG(17), ARG(12));
							LOAD_CHAR(ARG(17), '.', ARG(17));
							COPY(ARG(15), ARG(18));
							F1plus(ARG(18));
							LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(19));	/* T */
							LOAD_NIL(ARG(20));
							LOAD_NIL(ARG(21));
							LOAD_NIL(ARG(22));
							if(CL_LISTP(ARG(6)))
							{
								LOAD_CHAR(ARG(23), '.', ARG(23));
								COPY(ARG(6), ARG(24));
								LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(25));	/* T */
								LOAD_NIL(ARG(26));
								LOAD_NIL(ARG(27));
								COPY(ARG(18), ARG(28));
								COPY(ARG(16), ARG(29));
								LOAD_NIL(ARG(30));
								list_position(ARG(23));
								COPY(ARG(23), ARG(17));
							}
							else
							{
								LOAD_CHAR(ARG(23), '.', ARG(23));
								COPY(ARG(6), ARG(24));
								LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(25));	/* T */
								LOAD_NIL(ARG(26));
								LOAD_NIL(ARG(27));
								COPY(ARG(18), ARG(28));
								COPY(ARG(16), ARG(29));
								LOAD_NIL(ARG(30));
								vector_position(ARG(23));
								COPY(ARG(23), ARG(17));
							}
							if(CL_TRUEP(ARG(17)))
							{
								LOAD_CHAR(ARG(18), '.', ARG(18));
								COPY(ARG(15), ARG(19));
								F1plus(ARG(19));
								LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(20));	/* T */
								LOAD_NIL(ARG(21));
								LOAD_NIL(ARG(22));
								LOAD_NIL(ARG(23));
								if(CL_LISTP(ARG(6)))
								{
									LOAD_CHAR(ARG(24), '.', ARG(24));
									COPY(ARG(6), ARG(25));
									LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(26));	/* T */
									LOAD_NIL(ARG(27));
									LOAD_NIL(ARG(28));
									COPY(ARG(19), ARG(29));
									COPY(ARG(17), ARG(30));
									LOAD_NIL(ARG(31));
									list_position(ARG(24));
									COPY(ARG(24), ARG(18));
								}
								else
								{
									LOAD_CHAR(ARG(24), '.', ARG(24));
									COPY(ARG(6), ARG(25));
									LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(26));	/* T */
									LOAD_NIL(ARG(27));
									LOAD_NIL(ARG(28));
									COPY(ARG(19), ARG(29));
									COPY(ARG(17), ARG(30));
									LOAD_NIL(ARG(31));
									vector_position(ARG(24));
									COPY(ARG(24), ARG(18));
								}
							}
							else
							{
								LOAD_NIL(ARG(18));
							}
							LOAD_SYMBOL(SYMBOL(Slisp, 259), ARG(19));	/* NEWEST */
							if(CL_TRUEP(ARG(18)))
							{
								COPY(ARG(17), ARG(20));
								LOAD_SMALLFIXNUM(2, ARG(21));
								Fplus(ARG(20), 2);
								COPY(ARG(16), ARG(21));
								Fnumeql(ARG(20), 2);
								if(CL_TRUEP(ARG(20)))
								{
									COPY(ARG(6), ARG(20));
									COPY(ARG(17), ARG(21));
									F1plus(ARG(21));
									Fschar(ARG(20));
									LOAD_CHAR(ARG(21), '*', ARG(21));
									rt_charE(ARG(20));
								}
								else
								{
									goto ELSE1;
								}
								if(CL_TRUEP(ARG(20)))
								{
									LOAD_SYMBOL(SYMBOL(Slisp, 262), ARG(19));	/* WILD */
								}
								else
								{
									ELSE1:;
									COPY(ARG(17), ARG(20));
									F1plus(ARG(20));
									COPY(ARG(16), ARG(21));
									Flt(ARG(20), 2);
									if(CL_TRUEP(ARG(20)))
									{
										COPY(ARG(17), ARG(20));
										F1plus(ARG(20));
										M4_1:;
										COPY(ARG(20), ARG(21));
										COPY(ARG(16), ARG(22));
										Fnumeql(ARG(21), 2);
										if(CL_TRUEP(ARG(21)))
										{
											bool_result = TRUE;
											goto RETURN4;
										}
										LOAD_CHAR(ARG(21), '0', ARG(21));
										COPY(ARG(6), ARG(22));
										COPY(ARG(20), ARG(23));
										Fschar(ARG(22));
										LOAD_CHAR(ARG(23), '9', ARG(23));
										FcharLE(ARG(21), 3);
										if(CL_TRUEP(ARG(21)))
										{
										}
										else
										{
											bool_result = FALSE;
											goto RETURN4;
										}
										F1plus(ARG(20));
										goto M4_1;
										RETURN4:;
									}
									else
									{
										goto ELSE2;
									}
									if(bool_result)
									{
										COPY(ARG(6), ARG(20));
										COPY(ARG(17), ARG(21));
										F1plus(ARG(21));
										COPY(ARG(16), ARG(22));
										LOAD_SMALLFIXNUM(10, ARG(23));
										LOAD_NIL(ARG(24));
										parse_integer1(ARG(20));
										mv_count = 1;
										COPY(ARG(20), ARG(19));
									}
									else
									{
										ELSE2:;
										LOAD_NIL(ARG(18));
									}
								}
							}
							if(CL_TRUEP(ARG(18)))
							{
								COPY(ARG(6), ARG(20));
								COPY(ARG(15), ARG(21));
								COPY(ARG(18), ARG(22));
								maybe_make_pattern(ARG(20));
								COPY(ARG(6), ARG(21));
								COPY(ARG(18), ARG(22));
								F1plus(ARG(22));
								COPY(ARG(17), ARG(23));
								maybe_make_pattern(ARG(21));
								COPY(ARG(19), ARG(22));
								COPY(ARG(20), ARG(14));
								COPY(ARG(21), &mv_buf[0]);
								COPY(ARG(22), &mv_buf[1]);
								mv_count = 3;
							}
							else
							{
								if(CL_TRUEP(ARG(17)))
								{
									COPY(ARG(6), ARG(20));
									COPY(ARG(15), ARG(21));
									COPY(ARG(17), ARG(22));
									maybe_make_pattern(ARG(20));
									COPY(ARG(6), ARG(21));
									COPY(ARG(17), ARG(22));
									F1plus(ARG(22));
									COPY(ARG(16), ARG(23));
									maybe_make_pattern(ARG(21));
									COPY(ARG(19), ARG(22));
									COPY(ARG(20), ARG(14));
									COPY(ARG(21), &mv_buf[0]);
									COPY(ARG(22), &mv_buf[1]);
									mv_count = 3;
								}
								else
								{
									COPY(ARG(6), ARG(20));
									COPY(ARG(15), ARG(21));
									COPY(ARG(16), ARG(22));
									maybe_make_pattern(ARG(20));
									LOAD_NIL(ARG(21));
									COPY(ARG(19), ARG(22));
									COPY(ARG(20), ARG(14));
									COPY(ARG(21), &mv_buf[0]);
									COPY(ARG(22), &mv_buf[1]);
									mv_count = 3;
								}
							}
						}
						MV_TO_STACK(mv_count, 15);
						{
							int nargs;
							nargs = mv_count;
							mv_count = 1;
							{
								switch(nargs)
								{
									case 0:
									LOAD_NIL(ARG(14));
									case 1:
									LOAD_NIL(ARG(15));
									case 2:
									LOAD_NIL(ARG(16));
									nargs = 3;
								}
								LOAD_NIL(ARG(17));
								LOAD_NIL(ARG(18));
								LOAD_NIL(ARG(19));
								LOAD_NIL(ARG(20));
								ALLOC_CONS(ARG(21), ARG(19), ARG(20), ARG(19));
								if(CL_TRUEP(ARG(13)))
								{
									LOAD_SMSTR((CL_FORM *)&Kparse_namestring1[4], ARG(20));	/* search lists not implemented */
									Ferror(ARG(20), 1);
								}
								LOAD_NIL(ARG(20));
								COPY(ARG(12), ARG(21));
								M5_1:;
								if(CL_ATOMP(ARG(21)))
								{
									LOAD_NIL(ARG(20));
									goto RETURN5;
								}
								COPY(ARG(21), ARG(22));
								COPY(GET_CAR(ARG(22)), ARG(20));
								if(CL_CONSP(ARG(20)))
								{
									COPY(GET_CAR(ARG(20)), ARG(22));
								}
								else
								{
									if(CL_TRUEP(ARG(20)))
									{
										LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(22));	/* ~a is not a list */
										COPY(ARG(20), ARG(23));
										Ferror(ARG(22), 2);
									}
									else
									{
										COPY(ARG(20), ARG(22));
									}
								}
								if(CL_CONSP(ARG(20)))
								{
									COPY(GET_CDR(ARG(20)), ARG(23));
								}
								else
								{
									if(CL_TRUEP(ARG(20)))
									{
										LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(23));	/* ~a is not a list */
										COPY(ARG(20), ARG(24));
										Ferror(ARG(23), 2);
									}
									else
									{
										COPY(ARG(20), ARG(23));
									}
								}
								COPY(ARG(22), ARG(24));
								COPY(ARG(23), ARG(25));
								Fnumeql(ARG(24), 2);
								if(CL_TRUEP(ARG(24)))
								{
								}
								else
								{
									COPY(ARG(6), ARG(24));
									COPY(ARG(22), ARG(25));
									COPY(ARG(23), ARG(26));
									maybe_make_pattern(ARG(24));
									if(CL_SMSTRP(ARG(24)))
									{
										COPY(ARG(24), ARG(25));
										LOAD_SMSTR((CL_FORM *)&Kparse_namestring1[6], ARG(26));	/* .. */
										LOAD_SMALLFIXNUM(0, ARG(27));
										LOAD_NIL(ARG(28));
										LOAD_SMALLFIXNUM(0, ARG(29));
										LOAD_NIL(ARG(30));
										stringE1(ARG(25));
									}
									else
									{
										goto ELSE3;
									}
									if(CL_TRUEP(ARG(25)))
									{
										LOAD_SYMBOL(SYMBOL(Slisp, 265), ARG(25));	/* UP */
										COPY(ARG(19), ARG(26));
										add_q(ARG(25));
									}
									else
									{
										ELSE3:;
										COPY(ARG(24), ARG(25));
										COPY(ARG(19), ARG(26));
										add_q(ARG(25));
									}
								}
								COPY(ARG(21), ARG(22));
								COPY(GET_CDR(ARG(22)), ARG(21));
								goto M5_1;
								RETURN5:;
								COPY(ARG(19), ARG(20));
								COPY(ARG(20), ARG(21));
								COPY(GET_CAR(ARG(21)), ARG(19));
								if(CL_TRUEP(ARG(11)))
								{
									LOAD_SYMBOL(SYMBOL(Slisp, 257), ARG(20));	/* ABSOLUTE */
									ALLOC_CONS(ARG(22), ARG(20), ARG(19), ARG(19));
								}
								else
								{
									if(CL_TRUEP(ARG(19)))
									{
										LOAD_SYMBOL(SYMBOL(Slisp, 261), ARG(20));	/* RELATIVE */
										ALLOC_CONS(ARG(22), ARG(20), ARG(19), ARG(19));
									}
									else
									{
										LOAD_NIL(ARG(19));
									}
								}
								COPY(ARG(14), ARG(20));
								COPY(ARG(15), ARG(21));
								COPY(ARG(16), ARG(22));
								COPY(ARG(17), ARG(11));
								COPY(ARG(18), &mv_buf[0]);
								COPY(ARG(19), &mv_buf[1]);
								COPY(ARG(20), &mv_buf[2]);
								COPY(ARG(21), &mv_buf[3]);
								COPY(ARG(22), &mv_buf[4]);
								mv_count = 6;
							}
						}
					}
				}
				COPY(&mv_buf[0], ARG(12));
				COPY(&mv_buf[1], ARG(13));
				COPY(&mv_buf[2], ARG(14));
				COPY(&mv_buf[3], ARG(15));
				COPY(&mv_buf[4], ARG(16));
				{
					int nargs;
					nargs = 6;
					mv_count = 1;
					{
						switch(nargs)
						{
							case 0:
							LOAD_NIL(ARG(11));
							case 1:
							LOAD_NIL(ARG(12));
							case 2:
							LOAD_NIL(ARG(13));
							case 3:
							LOAD_NIL(ARG(14));
							case 4:
							LOAD_NIL(ARG(15));
							case 5:
							LOAD_NIL(ARG(16));
							nargs = 6;
						}
						if(CL_TRUEP(ARG(11)))
						{
							COPY(ARG(11), ARG(17));
						}
						else
						{
							COPY(ARG(9), ARG(17));
						}
						LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(18));	/* PATHNAME */
						COPY(ARG(17), ARG(19));
						COPY(ARG(12), ARG(20));
						COPY(ARG(13), ARG(21));
						COPY(ARG(14), ARG(22));
						COPY(ARG(15), ARG(23));
						COPY(ARG(16), ARG(24));
						rt_make_struct(ARG(18), 7);
						COPY(ARG(18), ARG(17));
						COPY(ARG(8), ARG(18));
						COPY(ARG(17), ARG(0));
						COPY(ARG(18), &mv_buf[0]);
						mv_count = 2;
					}
				}
			}
			else
			{
				COPY(ARG(6), ARG(11));
				LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(12));	/* SIMPLE-STRING */
				Fcoerce(ARG(11));
				COPY(ARG(11), ARG(6));
				LOAD_NIL(ARG(10));
				goto M1_1;
			}
		}
		goto RETURN1;
		RETURN1:;
	}
	else
	{
		COPY(ARG(0), ARG(6));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(7));	/* PATHNAME */
		rt_struct_typep(ARG(6));
		if(CL_TRUEP(ARG(6)))
		{
			COPY(ARG(0), ARG(6));
		}
		else
		{
			COPY(ARG(0), ARG(6));
			Fstringp(ARG(6));
			if(CL_TRUEP(ARG(6)))
			{
				COPY(ARG(0), ARG(6));
				LOAD_NIL(ARG(7));
				COPY(SYMVAL(Slisp, 231), ARG(8));	/* *DEFAULT-PATHNAME-DEFAULTS* */
				LOAD_SMALLFIXNUM(0, ARG(9));
				LOAD_NIL(ARG(10));
				LOAD_NIL(ARG(11));
				parse_namestring1(ARG(6));
				mv_count = 1;
			}
			else
			{
				COPY(ARG(0), ARG(6));
				LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(7));	/* STREAM */
				rt_struct_typep(ARG(6));
				if(CL_TRUEP(ARG(6)))
				{
					COPY(ARG(0), ARG(6));
					LOAD_NIL(ARG(7));
					file_name1(ARG(6));
					COPY(SYMVAL(Slisp, 231), ARG(7));	/* *DEFAULT-PATHNAME-DEFAULTS* */
					LOAD_SMALLFIXNUM(0, ARG(8));
					COPY(ARG(6), ARG(9));
					LOAD_NIL(ARG(10));
					COPY(ARG(7), ARG(11));
					COPY(ARG(8), ARG(12));
					LOAD_NIL(ARG(13));
					LOAD_NIL(ARG(14));
					parse_namestring1(ARG(9));
					mv_count = 1;
					COPY(ARG(9), ARG(6));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&Kparse_namestring1[8], ARG(6));	/* etypecase: the value ~a is not a legal value */
					COPY(ARG(0), ARG(7));
					Ferror(ARG(6), 2);
				}
			}
		}
		if(CL_TRUEP(ARG(1)))
		{
			COPY(ARG(6), ARG(8));
			LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(9));	/* PATHNAME */
			rt_struct_typep(ARG(8));
			if(CL_TRUEP(ARG(8)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(6))), 0 + 1), ARG(8));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(8));	/* NO_STRUCT */
				COPY(ARG(6), ARG(9));
				LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(10));	/* PATHNAME */
				Ferror(ARG(8), 3);
			}
			if(EQ(ARG(1), ARG(8)))
			{
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&Kparse_namestring1[10], ARG(7));	/* Hosts do not match: ~S and ~S. */
				COPY(ARG(1), ARG(8));
				COPY(ARG(6), ARG(9));
				LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(10));	/* PATHNAME */
				rt_struct_typep(ARG(9));
				if(CL_TRUEP(ARG(9)))
				{
					COPY(OFFSET(AR_BASE(GET_FORM(ARG(6))), 0 + 1), ARG(9));
				}
				else
				{
					COPY(SYMVAL(Slisp, 342), ARG(9));	/* NO_STRUCT */
					COPY(ARG(6), ARG(10));
					LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(11));	/* PATHNAME */
					Ferror(ARG(9), 3);
				}
				Ferror(ARG(7), 3);
			}
		}
		COPY(ARG(6), ARG(0));
		COPY(ARG(3), ARG(1));
		COPY(ARG(1), &mv_buf[0]);
		mv_count = 2;
	}
}
