/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void set_macro_character1(CL_FORM *base)
{
	LOAD_NIL(SYMVAL(Slisp, 447));	/* *READTABLE-UNCHANGED* */
	COPY(ARG(3), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(5));	/* READTABLE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 0 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(4));	/* NO_STRUCT */
		COPY(ARG(3), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(6));	/* READTABLE */
		Ferror(ARG(4), 3);
	}
	if(CL_CHARP(ARG(0)))
	{
		COPY(ARG(0), ARG(5));
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(5));	/* WRONG_TYPE */
		COPY(ARG(0), ARG(6));
		LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(7));	/* CHARACTER */
		Ferror(ARG(5), 3);
	}
	rt_char_code(ARG(5));
	ALLOC_CONS(ARG(8), ARG(1), ARG(2), ARG(6));
	COPY(ARG(6), ARG(7));
	COPY(ARG(4), ARG(8));
	COPY(ARG(5), ARG(9));
	rt_set_vref(ARG(7));
	COPY(ARG(3), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(5));	/* READTABLE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 1 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(4));	/* NO_STRUCT */
		COPY(ARG(3), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(6));	/* READTABLE */
		Ferror(ARG(4), 3);
	}
	COPY(ARG(0), ARG(5));
	COPY(ARG(4), ARG(6));
	LOAD_NIL(ARG(7));
	LOAD_NIL(ARG(8));
	LOAD_NIL(ARG(9));
	assoc1(ARG(5));
	COPY(ARG(5), ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		if(CL_CONSP(ARG(4)))
		{
			LOAD_NIL(ARG(6));
			COPY(ARG(6), GET_CAR(ARG(4)));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[229], ARG(5));	/* ~a is not a cons */
			COPY(ARG(4), ARG(6));
			Ferror(ARG(5), 2);
		}
		if(CL_CONSP(ARG(4)))
		{
			LOAD_NIL(ARG(6));
			COPY(ARG(6), GET_CDR(ARG(4)));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[231], ARG(5));	/* ~a is not a cons */
			COPY(ARG(4), ARG(6));
			Ferror(ARG(5), 2);
		}
	}
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
}
