/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Farray_dimension(CL_FORM *base)
{
	if(CL_FIXNUMP(ARG(1)))
	{
		LOAD_SMALLFIXNUM(0, ARG(2));
		COPY(ARG(1), ARG(3));
		COPY(ARG(0), ARG(4));
		Farray_rank(ARG(4));
		F1minus(ARG(4));
		Fle(ARG(2), 3);
	}
	else
	{
		goto ELSE1;
	}
	if(CL_TRUEP(ARG(2)))
	{
	}
	else
	{
		ELSE1:;
		LOAD_SMSTR((CL_FORM *)&KClisp[168], ARG(2));	/* The value ~A is not suitable as an axis-number ~
            for an array with rank ~A */
		COPY(ARG(1), ARG(3));
		COPY(ARG(0), ARG(4));
		Farray_rank(ARG(4));
		Ferror(ARG(2), 3);
	}
	if(CL_SMVECP(ARG(0)))
	{
		LOAD_FIXNUM(ARG(3), AR_SIZE(GET_FORM(ARG(0))), ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(2));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(3));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(2));
		if(CL_TRUEP(ARG(2)))
		{
			complex_vector_length(ARG(0));
		}
		else
		{
			COPY(ARG(0), ARG(2));
			complex_array_dims(ARG(2));
			if(CL_LISTP(ARG(2)))
			{
				COPY(ARG(1), ARG(3));
				COPY(ARG(2), ARG(4));
				Fnthcdr(ARG(3));
				if(CL_CONSP(ARG(3)))
				{
					COPY(GET_CAR(ARG(3)), ARG(0));
				}
				else
				{
					if(CL_TRUEP(ARG(3)))
					{
						LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(0));	/* ~a is not a list */
						COPY(ARG(3), ARG(1));
						Ferror(ARG(0), 2);
					}
					else
					{
						LOAD_NIL(ARG(0));
					}
				}
			}
			else
			{
				COPY(ARG(2), ARG(0));
				Frow_major_aref(ARG(0));
			}
		}
	}
}
