/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void copy_readtable1(CL_FORM *base)
{
	LOAD_NIL(SYMVAL(Slisp, 447));	/* *READTABLE-UNCHANGED* */
	if(CL_TRUEP(ARG(0)))
	{
	}
	else
	{
		COPY(SYMVAL(Slisp, 448), ARG(0));	/* *STANDARD-READTABLE* */
	}
	if(CL_TRUEP(ARG(1)))
	{
	}
	else
	{
		COPY(SYMVAL(Slisp, 12), ARG(2));	/* CHAR-CODE-LIMIT */
		LOAD_SMALLFIXNUM(0, ARG(3));
		COPY(ARG(2), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(5));	/* T */
		LOAD_NIL(ARG(6));
		LOAD_NIL(ARG(7));
		LOAD_NIL(ARG(8));
		LOAD_NIL(ARG(9));
		LOAD_NIL(ARG(10));
		COPY(ARG(3), ARG(11));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(12));	/* T */
		LOAD_NIL(ARG(13));
		make_array1(ARG(4));
		COPY(ARG(4), ARG(2));
		COPY(ARG(2), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(1));	/* READTABLE */
		COPY(ARG(3), ARG(2));
		LOAD_NIL(ARG(3));
		rt_make_struct(ARG(1), 3);
	}
	COPY(ARG(0), ARG(2));
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(3));	/* READTABLE */
	rt_struct_typep(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), 0 + 1), ARG(2));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(2));	/* NO_STRUCT */
		COPY(ARG(0), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(4));	/* READTABLE */
		Ferror(ARG(2), 3);
	}
	COPY(ARG(1), ARG(3));
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(4));	/* READTABLE */
	rt_struct_typep(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 0 + 1), ARG(3));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(3));	/* NO_STRUCT */
		COPY(ARG(1), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(5));	/* READTABLE */
		Ferror(ARG(3), 3);
	}
	COPY(SYMVAL(Slisp, 12), ARG(4));	/* CHAR-CODE-LIMIT */
	LOAD_SMALLFIXNUM(0, ARG(5));
	M1_1:;
	COPY(ARG(5), ARG(6));
	COPY(ARG(4), ARG(7));
	Fge(ARG(6), 2);
	if(CL_TRUEP(ARG(6)))
	{
		goto RETURN1;
	}
	LOAD_BOOL(CL_SMVECP(ARG(2)), ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(2), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(8));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(7));
	}
	if(CL_TRUEP(ARG(7)))
	{
		THEN1:;
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(6));	/* WRONG_TYPE */
		COPY(ARG(2), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(8));	/* VECTOR */
		Ferror(ARG(6), 3);
	}
	COPY(ARG(2), ARG(6));
	COPY(ARG(5), ARG(7));
	Frow_major_aref(ARG(6));
	COPY(ARG(6), ARG(7));
	COPY(ARG(3), ARG(8));
	COPY(ARG(5), ARG(9));
	rt_set_vref(ARG(7));
	F1plus(ARG(5));
	goto M1_1;
	RETURN1:;
	LOAD_NIL(ARG(4));
	LOAD_SMALLFIXNUM(1, ARG(5));
	COPY(ARG(1), ARG(6));
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(7));	/* READTABLE */
	rt_struct_typep(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		LOAD_NIL(ARG(6));
		COPY(ARG(6), OFFSET(AR_BASE(GET_FORM(ARG(1))), GET_FIXNUM(ARG(5)) + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(6));	/* NO_STRUCT */
		COPY(ARG(1), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(8));	/* READTABLE */
		Ferror(ARG(6), 3);
	}
	LOAD_NIL(ARG(4));
	COPY(ARG(0), ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(6));	/* READTABLE */
	rt_struct_typep(ARG(5));
	if(CL_TRUEP(ARG(5)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), 1 + 1), ARG(5));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(5));	/* NO_STRUCT */
		COPY(ARG(0), ARG(6));
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(7));	/* READTABLE */
		Ferror(ARG(5), 3);
	}
	M2_1:;
	if(CL_ATOMP(ARG(5)))
	{
		LOAD_NIL(ARG(4));
		goto RETURN2;
	}
	COPY(ARG(5), ARG(6));
	COPY(GET_CAR(ARG(6)), ARG(4));
	if(CL_CONSP(ARG(4)))
	{
		bool_result = CL_TRUEP(GET_CAR(ARG(4)));
	}
	else
	{
		if(CL_TRUEP(ARG(4)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(6));	/* ~a is not a list */
			COPY(ARG(4), ARG(7));
			Ferror(ARG(6), 2);
		}
		else
		{
			bool_result = CL_TRUEP(ARG(4));
		}
	}
	if(bool_result)
	{
		COPY(ARG(4), ARG(6));
		COPY(ARG(0), ARG(7));
		COPY(ARG(1), ARG(8));
		copy_dispatch_macro_character(ARG(6));
	}
	COPY(ARG(5), ARG(6));
	COPY(GET_CDR(ARG(6)), ARG(5));
	goto M2_1;
	RETURN2:;
	COPY(ARG(1), ARG(0));
}
