/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Farray_has_fill_pointer_p(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	complex_vector_p(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		complex_vector_fillptr(ARG(0));
		Fminusp(ARG(0));
		Fnot(ARG(0));
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
