/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Cbq_remove_tokens, bq_remove_tokens, 1);

void bq_remove_tokens(CL_FORM *base)
{
	M1_1:;
	if(CL_ATOMP(ARG(0)))
	{
		if(EQ(ARG(0), SYMVAL(Slisp, 429)))	/* *BQ-LIST* */
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 28), ARG(0));	/* LIST */
		}
		else
		{
			if(EQ(ARG(0), SYMVAL(Slisp, 430)))	/* *BQ-APPEND* */
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 454), ARG(0));	/* APPEND */
			}
			else
			{
				if(EQ(ARG(0), SYMVAL(Slisp, 432)))	/* *BQ-NCONC* */
				{
					LOAD_SYMBOL(SYMBOL(Slisp, 455), ARG(0));	/* NCONC */
				}
				else
				{
					if(EQ(ARG(0), SYMVAL(Slisp, 431)))	/* *BQ-LIST** */
					{
						LOAD_SYMBOL(SYMBOL(Slisp, 456), ARG(0));	/* LIST* */
					}
					else
					{
						if(EQ(ARG(0), SYMVAL(Slisp, 434)))	/* *BQ-QUOTE* */
						{
							LOAD_SYMBOL(SYMBOL(Slisp, 452), ARG(0));	/* QUOTE */
						}
						else
						{
						}
					}
				}
			}
		}
	}
	else
	{
		COPY(GET_CAR(ARG(0)), ARG(1));
		if(EQ(ARG(1), SYMVAL(Slisp, 433)))	/* *BQ-CLOBBERABLE* */
		{
			COPY(GET_CDR(ARG(0)), ARG(1));
			if(CL_CONSP(ARG(1)))
			{
				COPY(GET_CAR(ARG(1)), ARG(1));
			}
			else
			{
				if(CL_TRUEP(ARG(1)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(2));	/* ~a is not a list */
					COPY(ARG(1), ARG(3));
					Ferror(ARG(2), 2);
				}
				else
				{
					LOAD_NIL(ARG(1));
				}
			}
			COPY(ARG(1), ARG(0));
			goto M1_1;
		}
		else
		{
			COPY(GET_CAR(ARG(0)), ARG(1));
			if(EQ(ARG(1), SYMVAL(Slisp, 431)))	/* *BQ-LIST** */
			{
				COPY(GET_CDR(ARG(0)), ARG(1));
				if(CL_CONSP(ARG(1)))
				{
					COPY(GET_CDR(ARG(1)), ARG(1));
				}
				else
				{
					if(CL_TRUEP(ARG(1)))
					{
						LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(2));	/* ~a is not a list */
						COPY(ARG(1), ARG(3));
						Ferror(ARG(2), 2);
					}
					else
					{
						LOAD_NIL(ARG(1));
					}
				}
				if(CL_CONSP(ARG(1)))
				{
					COPY(GET_CDR(ARG(0)), ARG(1));
					if(CL_CONSP(ARG(1)))
					{
						COPY(GET_CDR(ARG(1)), ARG(1));
					}
					else
					{
						if(CL_TRUEP(ARG(1)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(2));	/* ~a is not a list */
							COPY(ARG(1), ARG(3));
							Ferror(ARG(2), 2);
						}
						else
						{
							LOAD_NIL(ARG(1));
						}
					}
					if(CL_CONSP(ARG(1)))
					{
						COPY(GET_CDR(ARG(1)), ARG(1));
					}
					else
					{
						if(CL_TRUEP(ARG(1)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(2));	/* ~a is not a list */
							COPY(ARG(1), ARG(3));
							Ferror(ARG(2), 2);
						}
						else
						{
							LOAD_NIL(ARG(1));
						}
					}
					if(CL_TRUEP(ARG(1)))
					{
						goto ELSE1;
					}
					else
					{
						goto THEN2;
					}
				}
				else
				{
					goto ELSE1;
				}
			}
			else
			{
				goto ELSE1;
			}
			{
				THEN2:;
				LOAD_SYMBOL(SYMBOL(Slisp, 21), ARG(1));	/* CONS */
				LOAD_GLOBFUN(&Cbq_remove_tokens, ARG(2));
				COPY(GET_CDR(ARG(0)), ARG(3));
				maptree(ARG(2));
				mv_count = 1;
				ALLOC_CONS(ARG(3), ARG(1), ARG(2), ARG(0));
			}
			goto ENDIF3;
			{
				ELSE1:;
				LOAD_GLOBFUN(&Cbq_remove_tokens, ARG(1));
				COPY(ARG(0), ARG(2));
				maptree(ARG(1));
				COPY(ARG(1), ARG(0));
			}
			ENDIF3:;
		}
	}
	goto RETURN1;
	RETURN1:;
}
