/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fpackage_shadowing_symbols(CL_FORM *base)
{
	coerce_to_package(ARG(0));
	Ppackage_shadowings(ARG(0));
}
