/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void vector_reverse(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	Flength(ARG(1));
	COPY(ARG(1), ARG(2));
	COPY(ARG(0), ARG(3));
	array_element_type_internal(ARG(3));
	to_element_type(ARG(3));
	LOAD_NIL(ARG(4));
	LOAD_NIL(ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	LOAD_NIL(ARG(8));
	LOAD_SMALLFIXNUM(0, ARG(9));
	LOAD_NIL(ARG(10));
	LOAD_NIL(ARG(11));
	make_array1(ARG(2));
	LOAD_SMALLFIXNUM(0, ARG(3));
	COPY(ARG(1), ARG(4));
	F1minus(ARG(4));
	M1_1:;
	COPY(ARG(3), ARG(5));
	COPY(ARG(1), ARG(6));
	Fnumeql(ARG(5), 2);
	if(CL_TRUEP(ARG(5)))
	{
		COPY(ARG(2), ARG(0));
		goto RETURN1;
	}
	if(CL_LISTP(ARG(0)))
	{
		COPY(ARG(3), ARG(5));
		COPY(ARG(0), ARG(6));
		Fnthcdr(ARG(5));
		if(CL_CONSP(ARG(5)))
		{
			COPY(GET_CAR(ARG(5)), ARG(5));
		}
		else
		{
			if(CL_TRUEP(ARG(5)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(6));	/* ~a is not a list */
				COPY(ARG(5), ARG(7));
				Ferror(ARG(6), 2);
			}
			else
			{
				LOAD_NIL(ARG(5));
			}
		}
	}
	else
	{
		COPY(ARG(0), ARG(5));
		COPY(ARG(3), ARG(6));
		Frow_major_aref(ARG(5));
	}
	COPY(ARG(5), ARG(6));
	COPY(ARG(2), ARG(7));
	COPY(ARG(4), ARG(8));
	Fset_elt(ARG(6));
	COPY(ARG(3), ARG(5));
	F1plus(ARG(5));
	COPY(ARG(4), ARG(6));
	F1minus(ARG(6));
	COPY(ARG(6), ARG(4));
	COPY(ARG(5), ARG(3));
	goto M1_1;
	RETURN1:;
}
