/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CPprint_pathname, Pprint_pathname, 3);

extern CL_INIT XIPprint_pathname[];
extern CL_INIT XFPprint_pathname[];
CL_INIT KPprint_pathname[] =
{
	MAKE_STRING(3, "#P\""),	/* 0 */
};

void Pprint_pathname(CL_FORM *base)
{
	LOAD_SMSTR((CL_FORM *)&KPprint_pathname[0], ARG(3));	/* #P" */
	COPY(ARG(3), ARG(4));
	COPY(ARG(1), ARG(5));
	LOAD_SMALLFIXNUM(0, ARG(6));
	COPY(ARG(3), ARG(7));
	Flength(ARG(7));
	write_string1(ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(3));	/* SIMPLE-STRING */
	COPY(ARG(0), ARG(4));
	Ppathname_directory(ARG(4));
	unparse_unix_directory_list(ARG(4));
	COPY(ARG(0), ARG(5));
	unparse_unix_file(ARG(5));
	Fconcatenate(ARG(3), 3);
	LOAD_SMALLFIXNUM(0, ARG(4));
	COPY(ARG(3), ARG(5));
	Flength(ARG(5));
	COPY(ARG(3), ARG(6));
	COPY(ARG(1), ARG(7));
	COPY(ARG(4), ARG(8));
	COPY(ARG(5), ARG(9));
	write_string1(ARG(6));
	LOAD_CHAR(ARG(0), '\"', ARG(0));
	write_char1(ARG(0));
}
