/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Cmake_readtable, make_readtable, -1);

void make_readtable(CL_FORM *base, int nargs)
{
	BOOL supl_flags[2];
	static CL_FORM * keylist[] =
	{
		SYMBOL(Slisp, 457),	/* SYNTAX */
		SYMBOL(Slisp, 458),	/* DISPATCH */
	};
	keysort(ARG(0), nargs - 0, 2, keylist, supl_flags, FALSE);
	if(NOT(supl_flags[0]))
	{
		COPY(SYMVAL(Slisp, 12), ARG(2));	/* CHAR-CODE-LIMIT */
		LOAD_SYMBOL(SYMBOL(Slisp, 152), ARG(3));	/* INITIAL-ELEMENT */
		LOAD_NIL(ARG(4));
		Fmake_array(ARG(2), 3);
		COPY(ARG(2), ARG(0));
	}
	if(NOT(supl_flags[1]))
	{
		LOAD_NIL(ARG(1));
	}
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(2));	/* READTABLE */
	COPY(ARG(0), ARG(3));
	COPY(ARG(1), ARG(4));
	rt_make_struct(ARG(2), 3);
	COPY(ARG(2), ARG(0));
}
