/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Flist_all_packages(CL_FORM *base)
{
	LOAD_SYMBOL(SYMBOL(Slisp, 28), ARG(0));	/* LIST */
	COPY(SYMVAL(Slisp, 379), ARG(1));	/* *PACKAGE-ARRAY* */
	Fconcatenate(ARG(0), 2);
}
