/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void internal_sxhash(CL_FORM *base)
{
	M1_1:;
	if(CL_SYMBOLP(ARG(0)) || CL_NILP(ARG(0)))
	{
		if(CL_SYMBOLP(ARG(0)))
		{
			GET_SYM_NAME(ARG(3), ARG(0), ARG(2));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				COPY(SYMVAL(Slisp, 679), ARG(2));	/* SYM_EXPECTED */
				COPY(ARG(0), ARG(3));
				Ferror(ARG(2), 2);
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(2));	/* NIL */
			}
		}
		rt_sxhash_string(ARG(2));
		COPY(ARG(2), ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(2));
		Fstringp(ARG(2));
		if(CL_TRUEP(ARG(2)))
		{
			string_to_simple_string(ARG(0));
			rt_sxhash_string(ARG(0));
		}
		else
		{
			if(CL_FIXNUMP(ARG(0)))
			{
			}
			else
			{
				if(CL_FLOATP(ARG(0)))
				{
					LOAD_SMALLFIXNUM(1, ARG(2));
					COPY(ARG(2), ARG(1));
					LOAD_SMALLFIXNUM(2, ARG(2));
					rt_convert_to_int(ARG(0));
				}
				else
				{
					if(CL_CHARP(ARG(0)))
					{
						rt_char_code(ARG(0));
					}
					else
					{
						if(CL_LISTP(ARG(0)))
						{
							COPY(ARG(1), ARG(2));
							COPY(SYMVAL(Slisp, 406), ARG(3));	/* SXHASH-MAX-DEPTH */
							Fnumeql(ARG(2), 2);
							if(CL_TRUEP(ARG(2)))
							{
								LOAD_SMALLFIXNUM(0, ARG(0));
							}
							else
							{
								COPY(ARG(0), ARG(2));
								LOAD_SMALLFIXNUM(0, ARG(3));
								LOAD_SMALLFIXNUM(2, ARG(4));
								M2_1:;
								LOAD_BOOL(CL_ATOMP(ARG(2)), ARG(5));
								if(CL_TRUEP(ARG(5)))
								{
									goto THEN1;
								}
								else
								{
									COPY(ARG(3), ARG(6));
									COPY(SYMVAL(Slisp, 405), ARG(7));	/* SXHASH-MAX-LEN */
									Fnumeql(ARG(6), 2);
								}
								if(CL_TRUEP(ARG(6)))
								{
									THEN1:;
									COPY(ARG(4), ARG(0));
									goto RETURN2;
								}
								if(CL_CONSP(ARG(2)))
								{
									COPY(GET_CAR(ARG(2)), ARG(5));
								}
								else
								{
									if(CL_TRUEP(ARG(2)))
									{
										LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(5));	/* ~a is not a list */
										COPY(ARG(2), ARG(6));
										Ferror(ARG(5), 2);
									}
									else
									{
										COPY(ARG(2), ARG(5));
									}
								}
								COPY(ARG(1), ARG(6));
								F1plus(ARG(6));
								internal_sxhash(ARG(5));
								mv_count = 1;
								COPY(ARG(2), ARG(5));
								if(CL_CONSP(ARG(5)))
								{
									COPY(GET_CDR(ARG(5)), ARG(5));
								}
								else
								{
									if(CL_TRUEP(ARG(5)))
									{
										LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(6));	/* ~a is not a list */
										COPY(ARG(5), ARG(7));
										Ferror(ARG(6), 2);
									}
									else
									{
										LOAD_NIL(ARG(5));
									}
								}
								COPY(ARG(3), ARG(6));
								F1plus(ARG(6));
								COPY(ARG(6), ARG(3));
								COPY(ARG(5), ARG(2));
								goto M2_1;
								RETURN2:;
							}
						}
						else
						{
							if(CL_STRUCTP(ARG(0)))
							{
								COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), -1 + 1), ARG(0));
								goto M1_1;
							}
							else
							{
								LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(2));
								if(CL_TRUEP(ARG(2)))
								{
									goto THEN2;
								}
								else
								{
									COPY(ARG(0), ARG(3));
									LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(4));	/* COMPLEX-BASE-ARRAY */
									rt_struct_typep(ARG(3));
								}
								if(CL_TRUEP(ARG(3)))
								{
									THEN2:;
									Farray_rank(ARG(0));
								}
								else
								{
									LOAD_SMALLFIXNUM(42, ARG(0));
								}
							}
						}
					}
				}
			}
		}
	}
	goto RETURN1;
	RETURN1:;
}
