/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void unuse_package1(CL_FORM *base)
{
	COPY(ARG(1), ARG(2));
	if(CL_SYMBOLP(ARG(2)) || CL_NILP(ARG(2)))
	{
		COPY(ARG(2), ARG(3));
		if(CL_SYMBOLP(ARG(3)))
		{
			GET_SYM_NAME(ARG(5), ARG(3), ARG(2));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(2));	/* NIL */
		}
	}
	COPY(ARG(2), ARG(3));
	Fstringp(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		Ffind_package(ARG(2));
	}
	COPY(ARG(2), ARG(1));
	if(CL_LISTP(ARG(0)))
	{
	}
	else
	{
		COPY(ARG(0), ARG(2));
		Flist(ARG(2), 1);
		COPY(ARG(2), ARG(0));
	}
	LOAD_NIL(ARG(2));
	COPY(ARG(0), ARG(3));
	M1_1:;
	if(CL_ATOMP(ARG(3)))
	{
		LOAD_NIL(ARG(2));
		goto RETURN1;
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CAR(ARG(4)), ARG(2));
	COPY(ARG(2), ARG(4));
	if(CL_SYMBOLP(ARG(4)) || CL_NILP(ARG(4)))
	{
		COPY(ARG(4), ARG(5));
		if(CL_SYMBOLP(ARG(5)))
		{
			GET_SYM_NAME(ARG(7), ARG(5), ARG(4));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(4));	/* NIL */
		}
	}
	COPY(ARG(4), ARG(5));
	Fstringp(ARG(5));
	if(CL_TRUEP(ARG(5)))
	{
		Ffind_package(ARG(4));
	}
	COPY(ARG(4), ARG(2));
	COPY(ARG(1), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(5));	/* PACKAGE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 5 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(4));	/* NO_STRUCT */
		COPY(ARG(1), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(6));	/* PACKAGE */
		Ferror(ARG(4), 3);
	}
	LOAD_SMALLFIXNUM(1, ARG(5));
	LOAD_SMALLFIXNUM(0, ARG(6));
	COPY(SYMVAL(Slisp, 0), ARG(7));	/* MOST-POSITIVE-FIXNUM */
	COPY(ARG(2), ARG(8));
	COPY(ARG(4), ARG(9));
	LOAD_NIL(ARG(10));
	LOAD_NIL(ARG(11));
	LOAD_NIL(ARG(12));
	COPY(ARG(6), ARG(13));
	COPY(ARG(7), ARG(14));
	COPY(ARG(5), ARG(15));
	LOAD_NIL(ARG(16));
	delete1(ARG(8));
	COPY(ARG(8), ARG(4));
	LOAD_SMALLFIXNUM(5, ARG(5));
	COPY(ARG(1), ARG(6));
	LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(7));	/* PACKAGE */
	rt_struct_typep(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(ARG(4), OFFSET(AR_BASE(GET_FORM(ARG(1))), GET_FIXNUM(ARG(5)) + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(6));	/* NO_STRUCT */
		COPY(ARG(1), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(8));	/* PACKAGE */
		Ferror(ARG(6), 3);
	}
	COPY(ARG(2), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(5));	/* PACKAGE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 6 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(4));	/* NO_STRUCT */
		COPY(ARG(2), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(6));	/* PACKAGE */
		Ferror(ARG(4), 3);
	}
	LOAD_SMALLFIXNUM(1, ARG(5));
	LOAD_SMALLFIXNUM(0, ARG(6));
	COPY(SYMVAL(Slisp, 0), ARG(7));	/* MOST-POSITIVE-FIXNUM */
	COPY(ARG(1), ARG(8));
	COPY(ARG(4), ARG(9));
	LOAD_NIL(ARG(10));
	LOAD_NIL(ARG(11));
	LOAD_NIL(ARG(12));
	COPY(ARG(6), ARG(13));
	COPY(ARG(7), ARG(14));
	COPY(ARG(5), ARG(15));
	LOAD_NIL(ARG(16));
	delete1(ARG(8));
	COPY(ARG(8), ARG(4));
	LOAD_SMALLFIXNUM(6, ARG(5));
	COPY(ARG(2), ARG(6));
	LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(7));	/* PACKAGE */
	rt_struct_typep(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(ARG(4), OFFSET(AR_BASE(GET_FORM(ARG(2))), GET_FIXNUM(ARG(5)) + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(6));	/* NO_STRUCT */
		COPY(ARG(2), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(8));	/* PACKAGE */
		Ferror(ARG(6), 3);
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CDR(ARG(4)), ARG(3));
	goto M1_1;
	RETURN1:;
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
}
