/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fstream_element_type(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	Fstreamp(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[170], ARG(0));	/* stream expected */
		Ferror(ARG(0), 1);
	}
	else
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(0));	/* CHARACTER */
	}
}
