/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Farray_element_type(CL_FORM *base)
{
	array_element_type_internal(ARG(0));
	to_element_type(ARG(0));
}
