/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void nstring_downcase1(CL_FORM *base)
{
	if(CL_TRUEP(ARG(2)))
	{
	}
	else
	{
		COPY(ARG(0), ARG(2));
		Flength(ARG(2));
	}
	COPY(ARG(1), ARG(3));
	M1_1:;
	COPY(ARG(3), ARG(4));
	COPY(ARG(2), ARG(5));
	Fnumeql(ARG(4), 2);
	if(CL_TRUEP(ARG(4)))
	{
		goto RETURN1;
	}
	COPY(ARG(0), ARG(4));
	COPY(ARG(3), ARG(5));
	Fschar(ARG(4));
	if(CL_CHARP(ARG(4)))
	{
		COPY(ARG(4), ARG(5));
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(5));	/* WRONG_TYPE */
		COPY(ARG(4), ARG(6));
		LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(7));	/* CHARACTER */
		Ferror(ARG(5), 3);
	}
	rt_char_downcase(ARG(5));
	COPY(ARG(5), ARG(4));
	COPY(ARG(0), ARG(6));
	COPY(ARG(3), ARG(7));
	Fset_schar(ARG(5));
	F1plus(ARG(3));
	goto M1_1;
	RETURN1:;
}
