/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void rt_struct_constructor(CL_FORM *base)
{
	LOAD_SYMBOL(SYMBOL(Slisp, 340), ARG(1));	/* STRUCT-CONSTRUCTOR */
	Fget(ARG(0), 2);
}
