/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fno_next_method(CL_FORM *base)
{
	LOAD_SMSTR((CL_FORM *)&KClisp[116], ARG(0));	/* No next method. */
	Ferror(ARG(0), 1);
}
