/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void nlist_substitute(CL_FORM *base)
{
	COPY(ARG(4), ARG(8));
	COPY(ARG(2), ARG(9));
	Fnthcdr(ARG(8));
	COPY(ARG(4), ARG(9));
	M1_1:;
	if(CL_TRUEP(ARG(8)))
	{
		if(CL_CONSP(ARG(8)))
		{
			LOAD_NIL(ARG(10));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[233], ARG(10));	/* ~a is not a list */
			COPY(ARG(8), ARG(11));
			Ferror(ARG(10), 2);
		}
	}
	else
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(10));	/* T */
	}
	if(CL_TRUEP(ARG(10)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(9), ARG(11));
		COPY(ARG(5), ARG(12));
		Fnumeql(ARG(11), 2);
		if(CL_TRUEP(ARG(11)))
		{
			goto THEN1;
		}
		else
		{
			COPY(ARG(6), ARG(12));
			Fzerop(ARG(12));
		}
	}
	if(CL_TRUEP(ARG(12)))
	{
		THEN1:;
		COPY(ARG(2), ARG(0));
		goto RETURN1;
	}
	COPY(ARG(3), ARG(10));
	COPY(ARG(1), ARG(11));
	if(CL_TRUEP(ARG(7)))
	{
		COPY(ARG(7), ARG(12));
		if(CL_CONSP(ARG(8)))
		{
			COPY(GET_CAR(ARG(8)), ARG(13));
		}
		else
		{
			if(CL_TRUEP(ARG(8)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(13));	/* ~a is not a list */
				COPY(ARG(8), ARG(14));
				Ferror(ARG(13), 2);
			}
			else
			{
				COPY(ARG(8), ARG(13));
			}
		}
		Ffuncall(ARG(12), 2);
		mv_count = 1;
	}
	else
	{
		if(CL_CONSP(ARG(8)))
		{
			COPY(GET_CAR(ARG(8)), ARG(12));
		}
		else
		{
			if(CL_TRUEP(ARG(8)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(12));	/* ~a is not a list */
				COPY(ARG(8), ARG(13));
				Ferror(ARG(12), 2);
			}
			else
			{
				COPY(ARG(8), ARG(12));
			}
		}
	}
	Ffuncall(ARG(10), 3);
	mv_count = 1;
	if(CL_TRUEP(ARG(10)))
	{
		if(CL_CONSP(ARG(8)))
		{
			COPY(ARG(0), GET_CAR(ARG(8)));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[237], ARG(10));	/* ~a is not a cons */
			COPY(ARG(8), ARG(11));
			Ferror(ARG(10), 2);
		}
		COPY(ARG(6), ARG(10));
		F1minus(ARG(10));
		COPY(ARG(10), ARG(6));
	}
	COPY(ARG(8), ARG(10));
	if(CL_CONSP(ARG(10)))
	{
		COPY(GET_CDR(ARG(10)), ARG(10));
	}
	else
	{
		if(CL_TRUEP(ARG(10)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(11));	/* ~a is not a list */
			COPY(ARG(10), ARG(12));
			Ferror(ARG(11), 2);
		}
		else
		{
			LOAD_NIL(ARG(10));
		}
	}
	COPY(ARG(9), ARG(11));
	F1plus(ARG(11));
	COPY(ARG(11), ARG(9));
	COPY(ARG(10), ARG(8));
	goto M1_1;
	RETURN1:;
}
