/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XIfill_data_vector[];
extern CL_INIT XFfill_data_vector[];
CL_INIT Kfill_data_vector[] =
{
	MAKE_STRING(89, "Malformed :initial-contents.  Dimension of ~\n\t\t\t        axis ~D is ~D, but ~S is ~D long."),	/* 0 */
};

static void Z120_frob(CL_FORM *base, CL_FORM *display[]);

void fill_data_vector(CL_FORM *base)
{
	CL_FORM *display[1];
	LOAD_SMALLFIXNUM(0, ARG(3));
	LOAD_SMALLFIXNUM(0, ARG(4));
	COPY(ARG(1), ARG(5));
	COPY(ARG(2), ARG(6));
	display[0] = ARG(0);
	Z120_frob(ARG(4), display);
	COPY(ARG(4), ARG(0));
}

static void Z120_frob(CL_FORM *base, CL_FORM *display[])
{
	if(CL_TRUEP(ARG(1)))
	{
		COPY(ARG(2), ARG(3));
		Flength(ARG(3));
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CAR(ARG(1)), ARG(4));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(4));	/* ~a is not a list */
			COPY(ARG(1), ARG(5));
			Ferror(ARG(4), 2);
		}
		Fnumeql(ARG(3), 2);
		if(CL_TRUEP(ARG(3)))
		{
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&Kfill_data_vector[0], ARG(3));	/* Malformed :initial-contents.  Dimension of ~
			        axis ~D is ~D, but ~S is ~D long. */
			COPY(ARG(0), ARG(4));
			if(CL_CONSP(ARG(1)))
			{
				COPY(GET_CAR(ARG(1)), ARG(5));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(5));	/* ~a is not a list */
				COPY(ARG(1), ARG(6));
				Ferror(ARG(5), 2);
			}
			COPY(ARG(2), ARG(6));
			COPY(ARG(2), ARG(7));
			Flength(ARG(7));
			Ferror(ARG(3), 5);
		}
		if(CL_LISTP(ARG(2)))
		{
			LOAD_NIL(ARG(3));
			COPY(ARG(2), ARG(4));
			M1_1:;
			if(CL_ATOMP(ARG(4)))
			{
				LOAD_NIL(ARG(3));
				COPY(ARG(3), ARG(0));
				goto RETURN1;
			}
			COPY(ARG(4), ARG(5));
			COPY(GET_CAR(ARG(5)), ARG(3));
			COPY(ARG(0), ARG(5));
			F1plus(ARG(5));
			if(CL_CONSP(ARG(1)))
			{
				COPY(GET_CDR(ARG(1)), ARG(6));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(6));	/* ~a is not a list */
				COPY(ARG(1), ARG(7));
				Ferror(ARG(6), 2);
			}
			COPY(ARG(3), ARG(7));
			Z120_frob(ARG(5), display);
			COPY(ARG(4), ARG(5));
			COPY(GET_CDR(ARG(5)), ARG(4));
			goto M1_1;
			RETURN1:;
		}
		else
		{
			COPY(ARG(2), ARG(3));
			Flength(ARG(3));
			LOAD_SMALLFIXNUM(0, ARG(4));
			M2_1:;
			COPY(ARG(4), ARG(5));
			COPY(ARG(3), ARG(6));
			Fge(ARG(5), 2);
			if(CL_TRUEP(ARG(5)))
			{
				LOAD_NIL(ARG(0));
				goto RETURN2;
			}
			COPY(ARG(0), ARG(5));
			F1plus(ARG(5));
			if(CL_CONSP(ARG(1)))
			{
				COPY(GET_CDR(ARG(1)), ARG(6));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(6));	/* ~a is not a list */
				COPY(ARG(1), ARG(7));
				Ferror(ARG(6), 2);
			}
			LOAD_BOOL(CL_SMVECP(ARG(2)), ARG(7));
			if(CL_TRUEP(ARG(7)))
			{
				goto THEN1;
			}
			else
			{
				COPY(ARG(2), ARG(8));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(9));	/* COMPLEX-VECTOR */
				rt_struct_typep(ARG(8));
			}
			if(CL_TRUEP(ARG(8)))
			{
				THEN1:;
			}
			else
			{
				COPY(SYMVAL(Slisp, 58), ARG(7));	/* WRONG_TYPE */
				COPY(ARG(2), ARG(8));
				LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(9));	/* VECTOR */
				Ferror(ARG(7), 3);
			}
			COPY(ARG(2), ARG(7));
			COPY(ARG(4), ARG(8));
			Frow_major_aref(ARG(7));
			Z120_frob(ARG(5), display);
			F1plus(ARG(4));
			goto M2_1;
			RETURN2:;
		}
	}
	else
	{
		COPY(ARG(2), ARG(3));
		COPY(&display[0][0], ARG(4));
		COPY(&display[0][3], ARG(5));
		rt_set_vref(ARG(3));
		COPY(&display[0][3], ARG(3));
		F1plus(ARG(3));
		COPY(ARG(3), &display[0][3]);
		COPY(&display[0][3], ARG(0));
	}
}
