/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XImerge_pathnames1[];
extern CL_INIT XFmerge_pathnames1[];
CL_INIT Kmerge_pathnames1[] =
{
	MAKE_STRING(44, "etypecase: the value ~a is not a legal value"),	/* 0 */
};

void merge_pathnames1(CL_FORM *base)
{
	COPY(ARG(1), ARG(3));
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(4));	/* PATHNAME */
	rt_struct_typep(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		COPY(ARG(1), ARG(3));
	}
	else
	{
		COPY(ARG(1), ARG(3));
		Fstringp(ARG(3));
		if(CL_TRUEP(ARG(3)))
		{
			COPY(ARG(1), ARG(3));
			LOAD_NIL(ARG(4));
			COPY(SYMVAL(Slisp, 231), ARG(5));	/* *DEFAULT-PATHNAME-DEFAULTS* */
			LOAD_SMALLFIXNUM(0, ARG(6));
			LOAD_NIL(ARG(7));
			LOAD_NIL(ARG(8));
			parse_namestring1(ARG(3));
			mv_count = 1;
		}
		else
		{
			COPY(ARG(1), ARG(3));
			LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
			rt_struct_typep(ARG(3));
			if(CL_TRUEP(ARG(3)))
			{
				COPY(ARG(1), ARG(3));
				LOAD_NIL(ARG(4));
				file_name1(ARG(3));
				COPY(SYMVAL(Slisp, 231), ARG(4));	/* *DEFAULT-PATHNAME-DEFAULTS* */
				LOAD_SMALLFIXNUM(0, ARG(5));
				COPY(ARG(3), ARG(6));
				LOAD_NIL(ARG(7));
				COPY(ARG(4), ARG(8));
				COPY(ARG(5), ARG(9));
				LOAD_NIL(ARG(10));
				LOAD_NIL(ARG(11));
				parse_namestring1(ARG(6));
				mv_count = 1;
				COPY(ARG(6), ARG(3));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&Kmerge_pathnames1[0], ARG(3));	/* etypecase: the value ~a is not a legal value */
				COPY(ARG(1), ARG(4));
				Ferror(ARG(3), 2);
			}
		}
	}
	COPY(ARG(3), ARG(4));
	BIND_SPECIAL(SYMBOL(Slisp, 231), ARG(4));	/* *DEFAULT-PATHNAME-DEFAULTS* */
	COPY(ARG(0), ARG(4));
	Fpathname(ARG(4));
	RESTORE_SPECIAL;
	COPY(ARG(3), ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(6));	/* PATHNAME */
	rt_struct_typep(ARG(5));
	if(CL_TRUEP(ARG(5)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 0 + 1), ARG(5));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(5));	/* NO_STRUCT */
		COPY(ARG(3), ARG(6));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(7));	/* PATHNAME */
		Ferror(ARG(5), 3);
	}
	COPY(ARG(4), ARG(6));
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(7));	/* PATHNAME */
	rt_struct_typep(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(4))), 0 + 1), ARG(6));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(6));	/* NO_STRUCT */
		COPY(ARG(4), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(8));	/* PATHNAME */
		Ferror(ARG(6), 3);
	}
	if(CL_TRUEP(ARG(6)))
	{
		COPY(ARG(6), ARG(7));
	}
	else
	{
		COPY(ARG(5), ARG(7));
	}
	COPY(ARG(4), ARG(8));
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(9));	/* PATHNAME */
	rt_struct_typep(ARG(8));
	if(CL_TRUEP(ARG(8)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(4))), 1 + 1), ARG(8));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(8));	/* NO_STRUCT */
		COPY(ARG(4), ARG(9));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(10));	/* PATHNAME */
		Ferror(ARG(8), 3);
	}
	if(CL_TRUEP(ARG(8)))
	{
	}
	else
	{
		COPY(ARG(3), ARG(9));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(10));	/* PATHNAME */
		rt_struct_typep(ARG(9));
		if(CL_TRUEP(ARG(9)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 1 + 1), ARG(9));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(9));	/* NO_STRUCT */
			COPY(ARG(3), ARG(10));
			LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(11));	/* PATHNAME */
			Ferror(ARG(9), 3);
		}
		LOAD_NIL(ARG(10));
		maybe_diddle_case(ARG(9));
		mv_count = 1;
		COPY(ARG(9), ARG(8));
	}
	COPY(ARG(4), ARG(9));
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(10));	/* PATHNAME */
	rt_struct_typep(ARG(9));
	if(CL_TRUEP(ARG(9)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(4))), 2 + 1), ARG(9));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(9));	/* NO_STRUCT */
		COPY(ARG(4), ARG(10));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(11));	/* PATHNAME */
		Ferror(ARG(9), 3);
	}
	COPY(ARG(3), ARG(10));
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(11));	/* PATHNAME */
	rt_struct_typep(ARG(10));
	if(CL_TRUEP(ARG(10)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 2 + 1), ARG(10));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(10));	/* NO_STRUCT */
		COPY(ARG(3), ARG(11));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(12));	/* PATHNAME */
		Ferror(ARG(10), 3);
	}
	LOAD_NIL(ARG(11));
	merge_directories(ARG(9));
	COPY(ARG(4), ARG(10));
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(11));	/* PATHNAME */
	rt_struct_typep(ARG(10));
	if(CL_TRUEP(ARG(10)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(4))), 3 + 1), ARG(10));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(10));	/* NO_STRUCT */
		COPY(ARG(4), ARG(11));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(12));	/* PATHNAME */
		Ferror(ARG(10), 3);
	}
	if(CL_TRUEP(ARG(10)))
	{
	}
	else
	{
		COPY(ARG(3), ARG(11));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(12));	/* PATHNAME */
		rt_struct_typep(ARG(11));
		if(CL_TRUEP(ARG(11)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 3 + 1), ARG(11));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(11));	/* NO_STRUCT */
			COPY(ARG(3), ARG(12));
			LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(13));	/* PATHNAME */
			Ferror(ARG(11), 3);
		}
		LOAD_NIL(ARG(12));
		maybe_diddle_case(ARG(11));
		mv_count = 1;
		COPY(ARG(11), ARG(10));
	}
	COPY(ARG(4), ARG(11));
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(12));	/* PATHNAME */
	rt_struct_typep(ARG(11));
	if(CL_TRUEP(ARG(11)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(4))), 4 + 1), ARG(11));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(11));	/* NO_STRUCT */
		COPY(ARG(4), ARG(12));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(13));	/* PATHNAME */
		Ferror(ARG(11), 3);
	}
	if(CL_TRUEP(ARG(11)))
	{
	}
	else
	{
		COPY(ARG(3), ARG(12));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(13));	/* PATHNAME */
		rt_struct_typep(ARG(12));
		if(CL_TRUEP(ARG(12)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 4 + 1), ARG(12));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(12));	/* NO_STRUCT */
			COPY(ARG(3), ARG(13));
			LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(14));	/* PATHNAME */
			Ferror(ARG(12), 3);
		}
		LOAD_NIL(ARG(13));
		maybe_diddle_case(ARG(12));
		mv_count = 1;
		COPY(ARG(12), ARG(11));
	}
	COPY(ARG(4), ARG(12));
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(13));	/* PATHNAME */
	rt_struct_typep(ARG(12));
	if(CL_TRUEP(ARG(12)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(4))), 5 + 1), ARG(12));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(12));	/* NO_STRUCT */
		COPY(ARG(4), ARG(13));
		LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(14));	/* PATHNAME */
		Ferror(ARG(12), 3);
	}
	if(CL_TRUEP(ARG(12)))
	{
	}
	else
	{
		COPY(ARG(2), ARG(12));
	}
	LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(0));	/* PATHNAME */
	COPY(ARG(7), ARG(1));
	COPY(ARG(8), ARG(2));
	COPY(ARG(9), ARG(3));
	COPY(ARG(10), ARG(4));
	COPY(ARG(11), ARG(5));
	COPY(ARG(12), ARG(6));
	rt_make_struct(ARG(0), 7);
}
