/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XImake_string_input_stream1[];
extern CL_INIT XFmake_string_input_stream1[];
CL_INIT Kmake_string_input_stream1[] =
{
	MAKE_STRING(23, "reached start of stream"),	/* 0 */
	MAKE_STRING(22, "%s should be eql to %s"),	/* 2 */
	MAKE_STRING(16, "illegal position"),	/* 4 */
};

static void Z72_lambda(CL_FORM *base);
static void Z73_lambda(CL_FORM *base);
static void Z74_lambda(CL_FORM *base);
static void Z75_lambda(CL_FORM *base);
static void Z76_lambda(CL_FORM *base);

void make_string_input_stream1(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(0), ARG(3));
	GEN_HEAPVAR(ARG(1), ARG(3));
	GEN_HEAPVAR(ARG(2), ARG(3));
	COPY(INDIRECT(ARG(1)), ARG(3));
	GEN_HEAPVAR(ARG(3), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 98), ARG(4));	/* STRING-INPUT */
	{
		GEN_CLOSURE(array, ARG(5), 6, Z76_lambda, 0);
		COPY(ARG(0), &array[3]);
		COPY(ARG(2), &array[4]);
		COPY(ARG(3), &array[5]);
		LOAD_CLOSURE(array, ARG(5));
	}
	COPY(ARG(5), ARG(5));
	{
		GEN_CLOSURE(array, ARG(6), 6, Z75_lambda, 1);
		COPY(ARG(0), &array[3]);
		COPY(ARG(1), &array[4]);
		COPY(ARG(3), &array[5]);
		LOAD_CLOSURE(array, ARG(6));
	}
	COPY(ARG(6), ARG(6));
	{
		GEN_CLOSURE(array, ARG(7), 4, Z74_lambda, 0);
		COPY(ARG(3), &array[3]);
		LOAD_CLOSURE(array, ARG(7));
	}
	COPY(ARG(7), ARG(7));
	{
		GEN_CLOSURE(array, ARG(8), 5, Z73_lambda, 1);
		COPY(ARG(3), &array[3]);
		COPY(ARG(2), &array[4]);
		LOAD_CLOSURE(array, ARG(8));
	}
	COPY(ARG(8), ARG(8));
	{
		GEN_CLOSURE(array, ARG(9), 4, Z72_lambda, 0);
		COPY(ARG(2), &array[3]);
		LOAD_CLOSURE(array, ARG(9));
	}
	COPY(ARG(9), ARG(9));
	LOAD_GLOBFUN(&Cclose1, ARG(10));
	LOAD_NIL(ARG(11));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(12));
	LOAD_GLOBFUN(&Cnil_fun, ARG(13));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(0));	/* STREAM */
	COPY(ARG(4), ARG(1));
	LOAD_NIL(ARG(2));
	COPY(ARG(5), ARG(3));
	COPY(ARG(6), ARG(4));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(5));
	LOAD_GLOBFUN(&Cnil_fun, ARG(6));
	LOAD_GLOBFUN(&Cclose1, ARG(10));
	rt_make_struct(ARG(0), 11);
}

static void Z72_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(0));
}

static void Z73_lambda(CL_FORM *base)
{
	COPY(ARG(1), ARG(2));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(3));
	Fle(ARG(2), 2);
	if(CL_TRUEP(ARG(2)))
	{
		COPY(ARG(1), INDIRECT(GET_FORM(ARG(0)) + 3));
		COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(0));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kmake_string_input_stream1[4], ARG(2));	/* illegal position */
		Ferror(ARG(2), 1);
	}
}

static void Z74_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(0));
}

static void Z75_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 5), ARG(2));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(3));
	Fle(ARG(2), 2);
	if(CL_TRUEP(ARG(2)))
	{
		LOAD_SMSTR((CL_FORM *)&Kmake_string_input_stream1[0], ARG(2));	/* reached start of stream */
		Ferror(ARG(2), 1);
	}
	COPY(INDIRECT(GET_FORM(ARG(0)) + 5), ARG(2));
	F1minus(ARG(2));
	COPY(ARG(2), INDIRECT(GET_FORM(ARG(0)) + 5));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(3));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 5), ARG(4));
	Frow_major_aref(ARG(3));
	if(EQL(ARG(1), ARG(3)))
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kmake_string_input_stream1[2], ARG(2));	/* %s should be eql to %s */
		COPY(ARG(1), ARG(3));
		COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(4));
		COPY(INDIRECT(GET_FORM(ARG(0)) + 5), ARG(5));
		Frow_major_aref(ARG(4));
		Ferror(ARG(2), 3);
	}
	LOAD_NIL(ARG(0));
}

static void Z76_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 5), ARG(1));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(2));
	Flt(ARG(1), 2);
	if(CL_TRUEP(ARG(1)))
	{
		COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
		COPY(INDIRECT(GET_FORM(ARG(0)) + 5), ARG(2));
		Frow_major_aref(ARG(1));
		COPY(INDIRECT(GET_FORM(ARG(0)) + 5), ARG(2));
		F1plus(ARG(2));
		COPY(ARG(2), INDIRECT(GET_FORM(ARG(0)) + 5));
		COPY(ARG(1), ARG(0));
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
