/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void set_syntax_from_char1(CL_FORM *base)
{
	LOAD_NIL(ARG(4));
	LOAD_NIL(SYMVAL(Slisp, 447));	/* *READTABLE-UNCHANGED* */
	COPY(ARG(2), ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(6));	/* READTABLE */
	rt_struct_typep(ARG(5));
	if(CL_TRUEP(ARG(5)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 0 + 1), ARG(5));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(5));	/* NO_STRUCT */
		COPY(ARG(2), ARG(6));
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(7));	/* READTABLE */
		Ferror(ARG(5), 3);
	}
	if(CL_CHARP(ARG(0)))
	{
		COPY(ARG(0), ARG(6));
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(6));	/* WRONG_TYPE */
		COPY(ARG(0), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(8));	/* CHARACTER */
		Ferror(ARG(6), 3);
	}
	rt_char_code(ARG(6));
	COPY(ARG(3), ARG(7));
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(8));	/* READTABLE */
	rt_struct_typep(ARG(7));
	if(CL_TRUEP(ARG(7)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 0 + 1), ARG(7));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(7));	/* NO_STRUCT */
		COPY(ARG(3), ARG(8));
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(9));	/* READTABLE */
		Ferror(ARG(7), 3);
	}
	if(CL_CHARP(ARG(1)))
	{
		COPY(ARG(1), ARG(8));
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(8));	/* WRONG_TYPE */
		COPY(ARG(1), ARG(9));
		LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(10));	/* CHARACTER */
		Ferror(ARG(8), 3);
	}
	rt_char_code(ARG(8));
	LOAD_BOOL(CL_SMVECP(ARG(7)), ARG(9));
	if(CL_TRUEP(ARG(9)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(7), ARG(10));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(11));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(10));
	}
	if(CL_TRUEP(ARG(10)))
	{
		THEN1:;
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(9));	/* WRONG_TYPE */
		COPY(ARG(7), ARG(10));
		LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(11));	/* VECTOR */
		Ferror(ARG(9), 3);
	}
	Frow_major_aref(ARG(7));
	COPY(ARG(7), ARG(8));
	COPY(ARG(5), ARG(9));
	COPY(ARG(6), ARG(10));
	rt_set_vref(ARG(8));
	COPY(ARG(0), ARG(5));
	COPY(ARG(2), ARG(6));
	COPY(ARG(6), ARG(7));
	LOAD_SMALLFIXNUM(1, ARG(8));
	COPY(ARG(7), ARG(9));
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(10));	/* READTABLE */
	rt_struct_typep(ARG(9));
	if(CL_TRUEP(ARG(9)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(7))), GET_FIXNUM(ARG(8)) + 1), ARG(6));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(6));	/* NO_STRUCT */
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(8));	/* READTABLE */
		Ferror(ARG(6), 3);
	}
	COPY(ARG(5), ARG(4));
	COPY(ARG(6), ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	LOAD_NIL(ARG(8));
	assoc1(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		if(CL_CONSP(ARG(4)))
		{
			LOAD_NIL(ARG(6));
			COPY(ARG(6), GET_CAR(ARG(4)));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[229], ARG(5));	/* ~a is not a cons */
			COPY(ARG(4), ARG(6));
			Ferror(ARG(5), 2);
		}
		if(CL_CONSP(ARG(4)))
		{
			LOAD_NIL(ARG(6));
			COPY(ARG(6), GET_CDR(ARG(4)));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[231], ARG(5));	/* ~a is not a cons */
			COPY(ARG(4), ARG(6));
			Ferror(ARG(5), 2);
		}
	}
	COPY(ARG(1), ARG(5));
	COPY(ARG(3), ARG(6));
	COPY(ARG(6), ARG(7));
	LOAD_SMALLFIXNUM(1, ARG(8));
	COPY(ARG(7), ARG(9));
	LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(10));	/* READTABLE */
	rt_struct_typep(ARG(9));
	if(CL_TRUEP(ARG(9)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(7))), GET_FIXNUM(ARG(8)) + 1), ARG(6));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(6));	/* NO_STRUCT */
		LOAD_SYMBOL(SYMBOL(Slisp, 410), ARG(8));	/* READTABLE */
		Ferror(ARG(6), 3);
	}
	COPY(ARG(5), ARG(4));
	COPY(ARG(6), ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	LOAD_NIL(ARG(8));
	assoc1(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(ARG(4), ARG(5));
		COPY(ARG(3), ARG(6));
		COPY(ARG(2), ARG(7));
		copy_dispatch_macro_character(ARG(5));
	}
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
}
