/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void rt_typep_class(CL_FORM *base)
{
	if(CL_INSTANCEP(ARG(0)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), -1 + 1), ARG(3));
		if(EQ(ARG(1), ARG(3)))
		{
		}
		else
		{
			COPY(ARG(1), ARG(2));
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), -1 + 1), ARG(3));
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 1 + 1), ARG(3));
			M1_1:;
			if(CL_TRUEP(ARG(3)))
			{
				if(CL_CONSP(ARG(3)))
				{
					COPY(GET_CAR(ARG(3)), ARG(5));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(5));	/* ~a is not a list */
					COPY(ARG(3), ARG(6));
					Ferror(ARG(5), 2);
				}
				if(EQ(ARG(2), ARG(5)))
				{
					COPY(ARG(2), ARG(0));
				}
				else
				{
					if(CL_CONSP(ARG(3)))
					{
						COPY(GET_CDR(ARG(3)), ARG(4));
					}
					else
					{
						LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(4));	/* ~a is not a list */
						COPY(ARG(3), ARG(5));
						Ferror(ARG(4), 2);
					}
					COPY(ARG(4), ARG(3));
					goto M1_1;
				}
			}
			else
			{
				LOAD_NIL(ARG(0));
			}
			goto RETURN1;
			RETURN1:;
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
