/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Cfeature_minus_reader, feature_minus_reader, 3);

void feature_minus_reader(CL_FORM *base)
{
	if(CL_TRUEP(ARG(2)))
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[208], ARG(3));	/* extra argument for #~S */
		LOAD_CHAR(ARG(4), '-', ARG(4));
		Ferror(ARG(3), 2);
	}
	COPY(SYMVAL(Slisp, 380), ARG(3));	/* *KEYWORD-PACKAGE* */
	BIND_SPECIAL(SYMBOL(Slisp, 343), ARG(3));	/* *PACKAGE* */
	COPY(ARG(0), ARG(3));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(4));	/* T */
	LOAD_NIL(ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(6));	/* T */
	read1(ARG(3));
	RESTORE_SPECIAL;
	COPY(ARG(3), ARG(4));
	eval_feature(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(4));	/* T */
		BIND_SPECIAL(SYMBOL(Slisp, 408), ARG(4));	/* *READ-SUPPRESS* */
		COPY(ARG(0), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(6));	/* T */
		LOAD_NIL(ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(8));	/* T */
		internal_read(ARG(5));
		LOAD_NIL(ARG(0));
		mv_count = 0;
		RESTORE_SPECIAL;
	}
	else
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(1));	/* T */
		LOAD_NIL(ARG(2));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(3));	/* T */
		internal_read(ARG(0));
	}
}
