/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void rt_do_symbols_iterator(CL_FORM *base)
{
	COPY(ARG(1), ARG(2));
	Ppackage_external(ARG(2));
	COPY(SYMVAL(Slisp, 372), ARG(3));	/* PACKAGE-HASHTAB-SIZE */
	LOAD_SMALLFIXNUM(0, ARG(4));
	M1_1:;
	COPY(ARG(4), ARG(5));
	COPY(ARG(3), ARG(6));
	Fge(ARG(5), 2);
	if(CL_TRUEP(ARG(5)))
	{
		goto RETURN1;
	}
	LOAD_NIL(ARG(5));
	COPY(ARG(2), ARG(6));
	COPY(ARG(4), ARG(7));
	Fsvref(ARG(6));
	M2_1:;
	if(CL_ATOMP(ARG(6)))
	{
		LOAD_NIL(ARG(5));
		goto RETURN2;
	}
	COPY(ARG(6), ARG(7));
	COPY(GET_CAR(ARG(7)), ARG(5));
	COPY(ARG(0), ARG(7));
	COPY(ARG(5), ARG(8));
	Ffuncall(ARG(7), 2);
	mv_count = 1;
	COPY(ARG(6), ARG(7));
	COPY(GET_CDR(ARG(7)), ARG(6));
	goto M2_1;
	RETURN2:;
	F1plus(ARG(4));
	goto M1_1;
	RETURN1:;
	COPY(ARG(1), ARG(2));
	Ppackage_internal(ARG(2));
	COPY(SYMVAL(Slisp, 372), ARG(3));	/* PACKAGE-HASHTAB-SIZE */
	LOAD_SMALLFIXNUM(0, ARG(4));
	M3_1:;
	COPY(ARG(4), ARG(5));
	COPY(ARG(3), ARG(6));
	Fge(ARG(5), 2);
	if(CL_TRUEP(ARG(5)))
	{
		goto RETURN3;
	}
	LOAD_NIL(ARG(5));
	COPY(ARG(2), ARG(6));
	COPY(ARG(4), ARG(7));
	Fsvref(ARG(6));
	M4_1:;
	if(CL_ATOMP(ARG(6)))
	{
		LOAD_NIL(ARG(5));
		goto RETURN4;
	}
	COPY(ARG(6), ARG(7));
	COPY(GET_CAR(ARG(7)), ARG(5));
	COPY(ARG(0), ARG(7));
	COPY(ARG(5), ARG(8));
	Ffuncall(ARG(7), 2);
	mv_count = 1;
	COPY(ARG(6), ARG(7));
	COPY(GET_CDR(ARG(7)), ARG(6));
	goto M4_1;
	RETURN4:;
	F1plus(ARG(4));
	goto M3_1;
	RETURN3:;
	LOAD_NIL(ARG(3));
	COPY(ARG(1), ARG(4));
	Ppackage_use_list(ARG(4));
	M5_1:;
	if(CL_ATOMP(ARG(4)))
	{
		LOAD_NIL(ARG(3));
		COPY(ARG(3), ARG(0));
		goto RETURN5;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CAR(ARG(5)), ARG(3));
	COPY(ARG(3), ARG(5));
	Ppackage_internal(ARG(5));
	COPY(ARG(5), ARG(2));
	COPY(SYMVAL(Slisp, 372), ARG(5));	/* PACKAGE-HASHTAB-SIZE */
	LOAD_SMALLFIXNUM(0, ARG(6));
	M6_1:;
	COPY(ARG(6), ARG(7));
	COPY(ARG(5), ARG(8));
	Fge(ARG(7), 2);
	if(CL_TRUEP(ARG(7)))
	{
		goto RETURN6;
	}
	LOAD_NIL(ARG(7));
	COPY(ARG(2), ARG(8));
	COPY(ARG(6), ARG(9));
	Fsvref(ARG(8));
	M7_1:;
	if(CL_ATOMP(ARG(8)))
	{
		LOAD_NIL(ARG(7));
		goto RETURN7;
	}
	COPY(ARG(8), ARG(9));
	COPY(GET_CAR(ARG(9)), ARG(7));
	COPY(ARG(0), ARG(9));
	COPY(ARG(7), ARG(10));
	Ffuncall(ARG(9), 2);
	mv_count = 1;
	COPY(ARG(8), ARG(9));
	COPY(GET_CDR(ARG(9)), ARG(8));
	goto M7_1;
	RETURN7:;
	F1plus(ARG(6));
	goto M6_1;
	RETURN6:;
	COPY(ARG(4), ARG(5));
	COPY(GET_CDR(ARG(5)), ARG(4));
	goto M5_1;
	RETURN5:;
}
