/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void check_array_internal(CL_FORM *base)
{
	LOAD_BOOL(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 49), ARG(3));	/* * */
	if(CL_TRUEP(ARG(3)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(0), ARG(4));
		array_element_type_internal(ARG(4));
		to_element_type(ARG(4));
		COPY(ARG(1), ARG(5));
		Fupgraded_array_element_type(ARG(5));
	}
	if(EQL(ARG(4), ARG(5)))
	{
		THEN1:;
		LOAD_BOOL(CL_SYMBOLP(ARG(2)) && GET_SYMBOL(ARG(2)) == SYMBOL(Slisp, 49), ARG(3));	/* * */
		if(CL_TRUEP(ARG(3)))
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
		}
		else
		{
			if(CL_ATOMP(ARG(2)))
			{
				COPY(ARG(0), ARG(4));
				Farray_rank(ARG(4));
				COPY(ARG(2), ARG(5));
				Fnumeql(ARG(4), 2);
				COPY(ARG(4), ARG(0));
			}
			else
			{
				COPY(ARG(0), ARG(4));
				Farray_rank(ARG(4));
				COPY(ARG(2), ARG(5));
				Flength(ARG(5));
				Fnumeql(ARG(4), 2);
				if(CL_TRUEP(ARG(4)))
				{
					LOAD_NIL(ARG(4));
					COPY(ARG(2), ARG(5));
					Flength(ARG(5));
					LOAD_SMALLFIXNUM(0, ARG(6));
					M1_1:;
					COPY(ARG(6), ARG(7));
					COPY(ARG(5), ARG(8));
					Fge(ARG(7), 2);
					if(CL_TRUEP(ARG(7)))
					{
						LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
						goto RETURN1;
					}
					COPY(ARG(2), ARG(7));
					COPY(ARG(7), ARG(8));
					if(CL_CONSP(ARG(8)))
					{
						COPY(GET_CAR(ARG(8)), ARG(7));
					}
					else
					{
						if(CL_TRUEP(ARG(8)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(7));	/* ~a is not a list */
							Ferror(ARG(7), 2);
						}
						else
						{
							LOAD_NIL(ARG(7));
						}
					}
					COPY(ARG(2), ARG(8));
					COPY(ARG(8), ARG(9));
					if(CL_CONSP(ARG(9)))
					{
						COPY(GET_CDR(ARG(9)), ARG(2));
					}
					else
					{
						if(CL_TRUEP(ARG(9)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(10));	/* ~a is not a list */
							COPY(ARG(9), ARG(11));
							Ferror(ARG(10), 2);
						}
						else
						{
							LOAD_NIL(ARG(2));
						}
					}
					COPY(ARG(7), ARG(4));
					LOAD_BOOL(CL_SYMBOLP(ARG(4)) && GET_SYMBOL(ARG(4)) == SYMBOL(Slisp, 49), ARG(7));	/* * */
					if(CL_TRUEP(ARG(7)))
					{
						goto THEN2;
					}
					else
					{
						COPY(ARG(0), ARG(8));
						COPY(ARG(6), ARG(9));
						Farray_dimension(ARG(8));
						COPY(ARG(4), ARG(9));
						Fnumeql(ARG(8), 2);
					}
					if(CL_TRUEP(ARG(8)))
					{
						THEN2:;
					}
					else
					{
						LOAD_NIL(ARG(0));
						goto RETURN1;
					}
					F1plus(ARG(6));
					goto M1_1;
					RETURN1:;
				}
				else
				{
					LOAD_NIL(ARG(0));
				}
			}
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
