/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fset_macro_character(CL_FORM *base, int nargs)
{
	switch(nargs)
	{
		case 2:
		LOAD_NIL(ARG(2));
		case 3:
		COPY(SYMVAL(Slisp, 449), ARG(3));	/* *READTABLE* */
		case 4:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	set_macro_character1(ARG(0));
}
