/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fmake_hash_table(CL_FORM *base, int nargs)
{
	BOOL supl_flags[4];
	static CL_FORM * keylist[] =
	{
		SYMBOL(Slisp, 272),	/* TEST */
		SYMBOL(Slisp, 397),	/* SIZE */
		SYMBOL(Slisp, 398),	/* REHASH-SIZE */
		SYMBOL(Slisp, 399),	/* REHASH-THRESHOLD */
	};
	keysort(ARG(0), nargs - 0, 4, keylist, supl_flags, FALSE);
	if(NOT(supl_flags[0]))
	{
		GEN_STATIC_GLOBAL_FUNARG(extern_closure, Feql, 2);
		LOAD_GLOBFUN(&extern_closure, ARG(0));
	}
	if(NOT(supl_flags[1]))
	{
		LOAD_SMALLFIXNUM(53, ARG(1));
	}
	if(NOT(supl_flags[2]))
	{
		GEN_FLOAT(ARG(4), 1.5, ARG(2));
	}
	if(NOT(supl_flags[3]))
	{
		GEN_FLOAT(ARG(4), 0.7, ARG(3));
	}
	make_hash_table1(ARG(0));
}
