/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void Fset_fill_pointer(CL_FORM *base)
{
	set_complex_vector_fillptr(ARG(0));
}
