/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

static void Z32_lambda(CL_FORM *base);

void nsubstitute_if_not1(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(1), ARG(8));
	COPY(ARG(0), ARG(8));
	LOAD_NIL(ARG(9));
	COPY(ARG(2), ARG(10));
	COPY(ARG(3), ARG(11));
	{
		GEN_CLOSURE(array, ARG(12), 4, Z32_lambda, 2);
		COPY(ARG(1), &array[3]);
		LOAD_CLOSURE(array, ARG(12));
	}
	COPY(ARG(12), ARG(12));
	LOAD_NIL(ARG(13));
	COPY(ARG(4), ARG(14));
	COPY(ARG(5), ARG(15));
	COPY(ARG(6), ARG(16));
	COPY(ARG(7), ARG(17));
	nsubstitute1(ARG(8));
	COPY(ARG(8), ARG(0));
}

static void Z32_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(3));
	COPY(ARG(2), ARG(4));
	Ffuncall(ARG(3), 2);
	mv_count = 1;
	if(CL_TRUEP(ARG(3)))
	{
		LOAD_NIL(ARG(0));
	}
	else
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
	}
}
