/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void list_subseq(CL_FORM *base)
{
	LOAD_NIL(ARG(3));
	LOAD_NIL(ARG(4));
	ALLOC_CONS(ARG(5), ARG(3), ARG(4), ARG(3));
	COPY(ARG(1), ARG(4));
	COPY(ARG(0), ARG(5));
	Fnthcdr(ARG(4));
	COPY(ARG(4), ARG(0));
	COPY(ARG(2), ARG(4));
	COPY(ARG(1), ARG(5));
	Fminus(ARG(4), 2);
	COPY(ARG(4), ARG(2));
	LOAD_SMALLFIXNUM(0, ARG(4));
	M1_1:;
	COPY(ARG(4), ARG(5));
	COPY(ARG(2), ARG(6));
	Fge(ARG(5), 2);
	if(CL_TRUEP(ARG(5)))
	{
		goto RETURN1;
	}
	if(CL_TRUEP(ARG(0)))
	{
		if(CL_CONSP(ARG(0)))
		{
			goto ELSE1;
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[233], ARG(5));	/* ~a is not a list */
			COPY(ARG(0), ARG(6));
			Ferror(ARG(5), 2);
		}
	}
	else
	{
		goto THEN2;
	}
	{
		THEN2:;
		goto RETURN1;
	}
	ELSE1:;
	if(CL_CONSP(ARG(0)))
	{
		COPY(GET_CAR(ARG(0)), ARG(5));
	}
	else
	{
		if(CL_TRUEP(ARG(0)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(5));	/* ~a is not a list */
			COPY(ARG(0), ARG(6));
			Ferror(ARG(5), 2);
		}
		else
		{
			COPY(ARG(0), ARG(5));
		}
	}
	COPY(ARG(0), ARG(6));
	COPY(ARG(6), ARG(7));
	if(CL_CONSP(ARG(7)))
	{
		COPY(GET_CDR(ARG(7)), ARG(0));
	}
	else
	{
		if(CL_TRUEP(ARG(7)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(8));	/* ~a is not a list */
			COPY(ARG(7), ARG(9));
			Ferror(ARG(8), 2);
		}
		else
		{
			LOAD_NIL(ARG(0));
		}
	}
	COPY(ARG(3), ARG(6));
	add_q(ARG(5));
	F1plus(ARG(4));
	goto M1_1;
	RETURN1:;
	COPY(GET_CAR(ARG(3)), ARG(0));
}
