/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void make_stream1(CL_FORM *base)
{
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(10));	/* STREAM */
	COPY(ARG(0), ARG(11));
	COPY(ARG(1), ARG(12));
	COPY(ARG(2), ARG(13));
	COPY(ARG(3), ARG(14));
	COPY(ARG(4), ARG(15));
	COPY(ARG(5), ARG(16));
	COPY(ARG(6), ARG(17));
	COPY(ARG(7), ARG(18));
	COPY(ARG(8), ARG(19));
	COPY(ARG(9), ARG(20));
	rt_make_struct(ARG(10), 11);
	COPY(ARG(10), ARG(0));
}
