/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void member_if1(CL_FORM *base)
{
	COPY(ARG(1), ARG(3));
	M1_1:;
	if(CL_TRUEP(ARG(3)))
	{
		COPY(ARG(0), ARG(4));
		if(CL_TRUEP(ARG(2)))
		{
			COPY(ARG(2), ARG(5));
			if(CL_CONSP(ARG(3)))
			{
				COPY(GET_CAR(ARG(3)), ARG(6));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(6));	/* ~a is not a list */
				COPY(ARG(3), ARG(7));
				Ferror(ARG(6), 2);
			}
			Ffuncall(ARG(5), 2);
			mv_count = 1;
		}
		else
		{
			if(CL_CONSP(ARG(3)))
			{
				COPY(GET_CAR(ARG(3)), ARG(5));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(5));	/* ~a is not a list */
				COPY(ARG(3), ARG(6));
				Ferror(ARG(5), 2);
			}
		}
		Ffuncall(ARG(4), 2);
		mv_count = 1;
		if(CL_TRUEP(ARG(4)))
		{
			COPY(ARG(3), ARG(0));
		}
		else
		{
			if(CL_CONSP(ARG(3)))
			{
				COPY(GET_CDR(ARG(3)), ARG(4));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(4));	/* ~a is not a list */
				COPY(ARG(3), ARG(5));
				Ferror(ARG(4), 2);
			}
			COPY(ARG(4), ARG(3));
			goto M1_1;
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
	goto RETURN1;
	RETURN1:;
}
