/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Cnil_fun, nil_fun, 0);

void nil_fun(CL_FORM *base)
{
	LOAD_NIL(ARG(0));
}
