/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

static void Z121_lambda(CL_FORM *base);
GEN_STATIC_GLOBAL_FUNARG(CZ121_lambda, Z121_lambda, 2);

void patternE(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	pattern_pieces(ARG(2));
	COPY(ARG(1), ARG(3));
	pattern_pieces(ARG(3));
	COPY(ARG(2), ARG(4));
	Flength(ARG(4));
	COPY(ARG(3), ARG(5));
	Flength(ARG(5));
	Fnumeql(ARG(4), 2);
	if(CL_TRUEP(ARG(4)))
	{
		LOAD_GLOBFUN(&CZ121_lambda, ARG(4));
		COPY(ARG(2), ARG(5));
		COPY(ARG(3), ARG(6));
		Fevery(ARG(4), 3);
		COPY(ARG(4), ARG(0));
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}

static void Z121_lambda(CL_FORM *base)
{
	if(CL_SMSTRP(ARG(0)))
	{
		if(CL_SMSTRP(ARG(1)))
		{
			LOAD_SMALLFIXNUM(0, ARG(2));
			LOAD_NIL(ARG(3));
			LOAD_SMALLFIXNUM(0, ARG(4));
			LOAD_NIL(ARG(5));
			stringE1(ARG(0));
		}
		else
		{
			LOAD_NIL(ARG(0));
		}
	}
	else
	{
		if(CL_CONSP(ARG(0)))
		{
			if(CL_CONSP(ARG(1)))
			{
				COPY(GET_CAR(ARG(0)), ARG(2));
				COPY(GET_CAR(ARG(1)), ARG(3));
				if(EQ(ARG(2), ARG(3)))
				{
					COPY(GET_CDR(ARG(0)), ARG(2));
					COPY(GET_CDR(ARG(1)), ARG(3));
					LOAD_SMALLFIXNUM(0, ARG(4));
					LOAD_SMALLFIXNUM(0, ARG(5));
					COPY(ARG(2), ARG(0));
					COPY(ARG(3), ARG(1));
					COPY(ARG(4), ARG(2));
					LOAD_NIL(ARG(3));
					COPY(ARG(5), ARG(4));
					LOAD_NIL(ARG(5));
					stringE1(ARG(0));
				}
				else
				{
					LOAD_NIL(ARG(0));
				}
			}
			else
			{
				LOAD_NIL(ARG(0));
			}
		}
		else
		{
			LOAD_BOOL(EQ(ARG(0), ARG(1)), ARG(0));
		}
	}
}
