/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void position1(CL_FORM *base)
{
	if(CL_LISTP(ARG(1)))
	{
		list_position(ARG(0));
	}
	else
	{
		vector_position(ARG(0));
	}
}
