/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void pprint1(CL_FORM *base)
{
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(2));	/* T */
	BIND_SPECIAL(SYMBOL(Slisp, 472), ARG(2));	/* *PRINT-ESCAPE* */
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(3));	/* T */
	BIND_SPECIAL(SYMBOL(Slisp, 476), ARG(3));	/* *PRINT-PRETTY* */
	if(CL_TRUEP(ARG(1)))
	{
		if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 48))	/* T */
		{
			COPY(SYMVAL(Slisp, 59), ARG(1));	/* *TERMINAL-IO* */
		}
	}
	else
	{
		COPY(SYMVAL(Slisp, 61), ARG(1));	/* *STANDARD-OUTPUT* */
	}
	COPY(ARG(1), ARG(4));
	terpri1(ARG(4));
	COPY(ARG(0), ARG(4));
	COPY(ARG(1), ARG(5));
	write2(ARG(4));
	LOAD_NIL(ARG(0));
	mv_count = 0;
	RESTORE_SPECIAL;
	RESTORE_SPECIAL;
}
