/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

static void Z148_f(CL_FORM *base, CL_FORM *display[]);

void print_integer(CL_FORM *base)
{
	CL_FORM *display[1];
	LOAD_SMALLFIXNUM(0, ARG(2));
	if(EQL(ARG(2), ARG(0)))
	{
		LOAD_CHAR(ARG(0), '0', ARG(0));
		write_char1(ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(2));
		Fminusp(ARG(2));
		if(CL_TRUEP(ARG(2)))
		{
			LOAD_CHAR(ARG(2), '-', ARG(2));
			COPY(ARG(1), ARG(3));
			write_char1(ARG(2));
			mv_count = 1;
			COPY(ARG(0), ARG(2));
			COPY(SYMVAL(Slisp, 469), ARG(3));	/* *PRINT-BASE* */
			LOAD_SMALLFIXNUM(2, ARG(4));
			rt_convert_to_int(ARG(2));
			mv_count = 1;
			Fminus(ARG(2), 1);
			display[0] = ARG(0);
			Z148_f(ARG(2), display);
			mv_count = 1;
			COPY(ARG(0), ARG(2));
			COPY(SYMVAL(Slisp, 469), ARG(3));	/* *PRINT-BASE* */
			LOAD_SMALLFIXNUM(2, ARG(4));
			rt_convert_to_int(ARG(2));
			COPY(&mv_buf[0], ARG(3));
			mv_count = 1;
			{
				COPY(ARG(3), ARG(2));
			}
			Fminus(ARG(2), 1);
			LOAD_SMALLFIXNUM(10, ARG(3));
			digit_char1(ARG(2));
			COPY(ARG(1), ARG(3));
			write_char1(ARG(2));
			COPY(ARG(2), ARG(0));
		}
		else
		{
			COPY(ARG(0), ARG(2));
			display[0] = ARG(0);
			Z148_f(ARG(2), display);
			COPY(ARG(2), ARG(0));
		}
	}
}

static void Z148_f(CL_FORM *base, CL_FORM *display[])
{
	LOAD_SMALLFIXNUM(0, ARG(1));
	if(EQL(ARG(1), ARG(0)))
	{
		LOAD_NIL(ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(1));
		COPY(SYMVAL(Slisp, 469), ARG(2));	/* *PRINT-BASE* */
		LOAD_SMALLFIXNUM(2, ARG(3));
		rt_convert_to_int(ARG(1));
		mv_count = 1;
		Z148_f(ARG(1), display);
		mv_count = 1;
		COPY(ARG(0), ARG(1));
		COPY(SYMVAL(Slisp, 469), ARG(2));	/* *PRINT-BASE* */
		LOAD_SMALLFIXNUM(2, ARG(3));
		rt_convert_to_int(ARG(1));
		COPY(&mv_buf[0], ARG(2));
		mv_count = 1;
		{
			COPY(ARG(2), ARG(1));
		}
		LOAD_SMALLFIXNUM(10, ARG(2));
		digit_char1(ARG(1));
		COPY(&display[0][1], ARG(2));
		write_char1(ARG(1));
		COPY(ARG(1), ARG(0));
	}
}
