/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Cprint_stream, print_stream, 3);

extern CL_INIT XIprint_stream[];
extern CL_INIT XFprint_stream[];
CL_INIT Kprint_stream[] =
{
	MAKE_STRING(2, "#<"),	/* 0 */
	MAKE_STRING(7, "-STREAM"),	/* 2 */
	MAKE_CONS,	/* 4 CONS(4) */
	MAKE_SYMREF(SYMBOL(Slisp, 90)),	/* FILE-INPUT */
	MAKE_CONSREF(&Kprint_stream[7]),
	MAKE_CONS,	/* CONS(7) */
	MAKE_SYMREF(SYMBOL(Slisp, 91)),	/* FILE-OUTPUT */
	MAKE_CONSREF(&Kprint_stream[10]),
	MAKE_CONS,	/* CONS(10) */
	MAKE_SYMREF(SYMBOL(Slisp, 92)),	/* FILE-IO */
	MAKE_NIL,
};

void print_stream(CL_FORM *base)
{
	LOAD_SMSTR((CL_FORM *)&Kprint_stream[0], ARG(3));	/* #< */
	COPY(ARG(3), ARG(4));
	COPY(ARG(1), ARG(5));
	LOAD_SMALLFIXNUM(0, ARG(6));
	COPY(ARG(3), ARG(7));
	Flength(ARG(7));
	write_string1(ARG(4));
	COPY(ARG(0), ARG(3));
	stream_type(ARG(3));
	COPY(ARG(1), ARG(4));
	princ1(ARG(3));
	LOAD_SMSTR((CL_FORM *)&Kprint_stream[2], ARG(3));	/* -STREAM */
	COPY(ARG(3), ARG(4));
	COPY(ARG(1), ARG(5));
	LOAD_SMALLFIXNUM(0, ARG(6));
	COPY(ARG(3), ARG(7));
	Flength(ARG(7));
	write_string1(ARG(4));
	COPY(ARG(0), ARG(3));
	stream_type(ARG(3));
	LOAD_CONS((CL_FORM *)&Kprint_stream[4], ARG(4));
	LOAD_NIL(ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	member1(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		LOAD_CHAR(ARG(3), ' ', ARG(3));
		COPY(ARG(1), ARG(4));
		write_char1(ARG(3));
		mv_count = 1;
		COPY(ARG(0), ARG(3));
		stream_extra(ARG(3));
		COPY(ARG(3), ARG(4));
		COPY(ARG(1), ARG(5));
		LOAD_SMALLFIXNUM(0, ARG(6));
		COPY(ARG(3), ARG(7));
		Flength(ARG(7));
		write_string1(ARG(4));
	}
	LOAD_CHAR(ARG(0), '>', ARG(0));
	write_char1(ARG(0));
}
