/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XIread_line1[];
extern CL_INIT XFread_line1[];
CL_INIT Kread_line1[] =
{
	MAKE_STRING(22, "unexpected end of file"),	/* 0 */
};

void read_line1(CL_FORM *base)
{
	if(CL_TRUEP(ARG(0)))
	{
		if(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 48))	/* T */
		{
			COPY(SYMVAL(Slisp, 59), ARG(0));	/* *TERMINAL-IO* */
		}
	}
	else
	{
		COPY(SYMVAL(Slisp, 60), ARG(0));	/* *STANDARD-INPUT* */
	}
	COPY(ARG(0), ARG(4));
	LOAD_NIL(ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	read_char1(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		LOAD_SMALLFIXNUM(0, SYMVAL(Slisp, 440));	/* *FILL-POINTER* */
		M1_1:;
		if(CL_CHARP(ARG(4)) && GET_CHAR(ARG(4)) == '\n')
		{
			get_token_string(ARG(0));
			LOAD_NIL(ARG(1));
			COPY(ARG(1), &mv_buf[0]);
			mv_count = 2;
			goto RETURN1;
		}
		COPY(ARG(4), ARG(5));
		token_push_extend(ARG(5));
		COPY(ARG(0), ARG(5));
		COPY(ARG(5), ARG(4));
		LOAD_NIL(ARG(5));
		LOAD_NIL(ARG(6));
		LOAD_NIL(ARG(7));
		read_char1(ARG(4));
		if(CL_TRUEP(ARG(4)))
		{
		}
		else
		{
			get_token_string(ARG(0));
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(1));	/* T */
			COPY(ARG(1), &mv_buf[0]);
			mv_count = 2;
			goto RETURN1;
		}
		goto M1_1;
		RETURN1:;
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			LOAD_SMSTR((CL_FORM *)&Kread_line1[0], ARG(5));	/* unexpected end of file */
			Ferror(ARG(5), 1);
		}
		COPY(ARG(2), ARG(0));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(1));	/* T */
		COPY(ARG(1), &mv_buf[0]);
		mv_count = 2;
	}
}
