/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void reduce1(CL_FORM *base)
{
	COPY(ARG(1), ARG(7));
	Flength(ARG(7));
	COPY(ARG(4), ARG(8));
	COPY(ARG(7), ARG(9));
	Fgt(ARG(8), 2);
	if(CL_TRUEP(ARG(8)))
	{
		COPY(ARG(7), ARG(4));
	}
	COPY(ARG(7), ARG(8));
	Fzerop(ARG(8));
	if(CL_TRUEP(ARG(8)))
	{
		if(CL_TRUEP(ARG(6)))
		{
			COPY(ARG(5), ARG(0));
		}
		else
		{
			Ffuncall(ARG(0), 1);
		}
	}
	else
	{
		COPY(ARG(7), ARG(8));
		LOAD_SMALLFIXNUM(1, ARG(9));
		Fnumeql(ARG(8), 2);
		if(CL_TRUEP(ARG(8)))
		{
			if(CL_TRUEP(ARG(6)))
			{
				goto ELSE1;
			}
			else
			{
				goto THEN2;
			}
		}
		else
		{
			goto ELSE1;
		}
		{
			THEN2:;
			LOAD_SMALLFIXNUM(0, ARG(8));
			if(CL_LISTP(ARG(1)))
			{
				COPY(ARG(8), ARG(9));
				COPY(ARG(1), ARG(10));
				Fnthcdr(ARG(9));
				if(CL_CONSP(ARG(9)))
				{
					COPY(GET_CAR(ARG(9)), ARG(0));
				}
				else
				{
					if(CL_TRUEP(ARG(9)))
					{
						LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(0));	/* ~a is not a list */
						COPY(ARG(9), ARG(1));
						Ferror(ARG(0), 2);
					}
					else
					{
						LOAD_NIL(ARG(0));
					}
				}
			}
			else
			{
				COPY(ARG(1), ARG(0));
				COPY(ARG(8), ARG(1));
				Frow_major_aref(ARG(0));
			}
		}
		goto ENDIF3;
		{
			ELSE1:;
			if(CL_TRUEP(ARG(2)))
			{
				COPY(ARG(4), ARG(8));
				F1minus(ARG(8));
				COPY(ARG(8), ARG(4));
				if(CL_TRUEP(ARG(6)))
				{
				}
				else
				{
					COPY(ARG(1), ARG(8));
					COPY(ARG(4), ARG(9));
					if(CL_LISTP(ARG(8)))
					{
						COPY(ARG(9), ARG(10));
						COPY(ARG(8), ARG(11));
						COPY(ARG(10), ARG(12));
						COPY(ARG(11), ARG(13));
						Fnthcdr(ARG(12));
						if(CL_CONSP(ARG(12)))
						{
							COPY(GET_CAR(ARG(12)), ARG(5));
						}
						else
						{
							if(CL_TRUEP(ARG(12)))
							{
								LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(13));	/* ~a is not a list */
								COPY(ARG(12), ARG(14));
								Ferror(ARG(13), 2);
							}
							else
							{
								LOAD_NIL(ARG(5));
							}
						}
					}
					else
					{
						COPY(ARG(8), ARG(10));
						COPY(ARG(9), ARG(11));
						Frow_major_aref(ARG(10));
						COPY(ARG(10), ARG(5));
					}
					COPY(ARG(4), ARG(8));
					F1minus(ARG(8));
					COPY(ARG(8), ARG(4));
				}
				COPY(ARG(5), ARG(8));
				M1_1:;
				COPY(ARG(3), ARG(9));
				COPY(ARG(4), ARG(10));
				Fge(ARG(9), 2);
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(8), ARG(0));
					goto RETURN1;
				}
				COPY(ARG(0), ARG(9));
				COPY(ARG(1), ARG(10));
				COPY(ARG(4), ARG(11));
				if(CL_LISTP(ARG(10)))
				{
					COPY(ARG(11), ARG(12));
					COPY(ARG(10), ARG(13));
					COPY(ARG(12), ARG(14));
					COPY(ARG(13), ARG(15));
					Fnthcdr(ARG(14));
					if(CL_CONSP(ARG(14)))
					{
						COPY(GET_CAR(ARG(14)), ARG(10));
					}
					else
					{
						if(CL_TRUEP(ARG(14)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(10));	/* ~a is not a list */
							COPY(ARG(14), ARG(11));
							Ferror(ARG(10), 2);
						}
						else
						{
							LOAD_NIL(ARG(10));
						}
					}
				}
				else
				{
					Frow_major_aref(ARG(10));
				}
				COPY(ARG(8), ARG(11));
				Ffuncall(ARG(9), 3);
				mv_count = 1;
				COPY(ARG(9), ARG(8));
				COPY(ARG(4), ARG(9));
				F1minus(ARG(9));
				COPY(ARG(9), ARG(4));
				goto M1_1;
				RETURN1:;
			}
			else
			{
				if(CL_TRUEP(ARG(6)))
				{
				}
				else
				{
					COPY(ARG(1), ARG(8));
					COPY(ARG(3), ARG(9));
					if(CL_LISTP(ARG(8)))
					{
						COPY(ARG(9), ARG(10));
						COPY(ARG(8), ARG(11));
						COPY(ARG(10), ARG(12));
						COPY(ARG(11), ARG(13));
						Fnthcdr(ARG(12));
						if(CL_CONSP(ARG(12)))
						{
							COPY(GET_CAR(ARG(12)), ARG(5));
						}
						else
						{
							if(CL_TRUEP(ARG(12)))
							{
								LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(13));	/* ~a is not a list */
								COPY(ARG(12), ARG(14));
								Ferror(ARG(13), 2);
							}
							else
							{
								LOAD_NIL(ARG(5));
							}
						}
					}
					else
					{
						COPY(ARG(8), ARG(10));
						COPY(ARG(9), ARG(11));
						Frow_major_aref(ARG(10));
						COPY(ARG(10), ARG(5));
					}
					COPY(ARG(3), ARG(8));
					F1plus(ARG(8));
					COPY(ARG(8), ARG(3));
				}
				COPY(ARG(5), ARG(8));
				M2_1:;
				COPY(ARG(3), ARG(9));
				COPY(ARG(4), ARG(10));
				Fge(ARG(9), 2);
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(8), ARG(0));
					goto RETURN2;
				}
				COPY(ARG(0), ARG(9));
				COPY(ARG(8), ARG(10));
				COPY(ARG(1), ARG(11));
				COPY(ARG(3), ARG(12));
				if(CL_LISTP(ARG(11)))
				{
					COPY(ARG(12), ARG(13));
					COPY(ARG(11), ARG(14));
					COPY(ARG(13), ARG(15));
					COPY(ARG(14), ARG(16));
					Fnthcdr(ARG(15));
					if(CL_CONSP(ARG(15)))
					{
						COPY(GET_CAR(ARG(15)), ARG(11));
					}
					else
					{
						if(CL_TRUEP(ARG(15)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(11));	/* ~a is not a list */
							COPY(ARG(15), ARG(12));
							Ferror(ARG(11), 2);
						}
						else
						{
							LOAD_NIL(ARG(11));
						}
					}
				}
				else
				{
					Frow_major_aref(ARG(11));
				}
				Ffuncall(ARG(9), 3);
				mv_count = 1;
				COPY(ARG(9), ARG(8));
				COPY(ARG(3), ARG(9));
				F1plus(ARG(9));
				COPY(ARG(9), ARG(3));
				goto M2_1;
				RETURN2:;
			}
		}
		ENDIF3:;
	}
}
