/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void replace1(CL_FORM *base)
{
	COPY(ARG(0), ARG(6));
	Flength(ARG(6));
	COPY(ARG(3), ARG(7));
	COPY(ARG(6), ARG(8));
	Fgt(ARG(7), 2);
	if(CL_TRUEP(ARG(7)))
	{
		COPY(ARG(6), ARG(3));
	}
	COPY(ARG(1), ARG(6));
	Flength(ARG(6));
	COPY(ARG(5), ARG(7));
	COPY(ARG(6), ARG(8));
	Fgt(ARG(7), 2);
	if(CL_TRUEP(ARG(7)))
	{
		COPY(ARG(6), ARG(5));
	}
	COPY(ARG(3), ARG(6));
	COPY(ARG(2), ARG(7));
	Fminus(ARG(6), 2);
	COPY(ARG(5), ARG(7));
	COPY(ARG(4), ARG(8));
	Fminus(ARG(7), 2);
	Fmin(ARG(6), 2);
	if(EQ(ARG(0), ARG(1)))
	{
		COPY(ARG(2), ARG(7));
		COPY(ARG(4), ARG(8));
		Fgt(ARG(7), 2);
	}
	else
	{
		goto ELSE1;
	}
	if(CL_TRUEP(ARG(7)))
	{
		LOAD_SMALLFIXNUM(0, ARG(7));
		COPY(ARG(2), ARG(8));
		COPY(ARG(6), ARG(9));
		F1minus(ARG(9));
		Fplus(ARG(8), 2);
		COPY(ARG(4), ARG(9));
		COPY(ARG(6), ARG(10));
		F1minus(ARG(10));
		Fplus(ARG(9), 2);
		M1_1:;
		COPY(ARG(7), ARG(10));
		COPY(ARG(6), ARG(11));
		Fge(ARG(10), 2);
		if(CL_TRUEP(ARG(10)))
		{
			goto RETURN1;
		}
		if(CL_LISTP(ARG(1)))
		{
			COPY(ARG(9), ARG(10));
			COPY(ARG(1), ARG(11));
			Fnthcdr(ARG(10));
			if(CL_CONSP(ARG(10)))
			{
				COPY(GET_CAR(ARG(10)), ARG(10));
			}
			else
			{
				if(CL_TRUEP(ARG(10)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(11));	/* ~a is not a list */
					COPY(ARG(10), ARG(12));
					Ferror(ARG(11), 2);
				}
				else
				{
					LOAD_NIL(ARG(10));
				}
			}
		}
		else
		{
			COPY(ARG(1), ARG(10));
			COPY(ARG(9), ARG(11));
			Frow_major_aref(ARG(10));
		}
		COPY(ARG(10), ARG(11));
		COPY(ARG(0), ARG(12));
		COPY(ARG(8), ARG(13));
		Fset_elt(ARG(11));
		COPY(ARG(7), ARG(10));
		F1plus(ARG(10));
		COPY(ARG(8), ARG(11));
		F1minus(ARG(11));
		COPY(ARG(9), ARG(12));
		F1minus(ARG(12));
		COPY(ARG(12), ARG(9));
		COPY(ARG(11), ARG(8));
		COPY(ARG(10), ARG(7));
		goto M1_1;
		RETURN1:;
	}
	else
	{
		ELSE1:;
		LOAD_SMALLFIXNUM(0, ARG(7));
		COPY(ARG(2), ARG(8));
		COPY(ARG(4), ARG(9));
		M2_1:;
		COPY(ARG(7), ARG(10));
		COPY(ARG(6), ARG(11));
		Fge(ARG(10), 2);
		if(CL_TRUEP(ARG(10)))
		{
			goto RETURN2;
		}
		if(CL_LISTP(ARG(1)))
		{
			COPY(ARG(9), ARG(10));
			COPY(ARG(1), ARG(11));
			Fnthcdr(ARG(10));
			if(CL_CONSP(ARG(10)))
			{
				COPY(GET_CAR(ARG(10)), ARG(10));
			}
			else
			{
				if(CL_TRUEP(ARG(10)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(11));	/* ~a is not a list */
					COPY(ARG(10), ARG(12));
					Ferror(ARG(11), 2);
				}
				else
				{
					LOAD_NIL(ARG(10));
				}
			}
		}
		else
		{
			COPY(ARG(1), ARG(10));
			COPY(ARG(9), ARG(11));
			Frow_major_aref(ARG(10));
		}
		COPY(ARG(10), ARG(11));
		COPY(ARG(0), ARG(12));
		COPY(ARG(8), ARG(13));
		Fset_elt(ARG(11));
		COPY(ARG(7), ARG(10));
		F1plus(ARG(10));
		COPY(ARG(8), ARG(11));
		F1plus(ARG(11));
		COPY(ARG(9), ARG(12));
		F1plus(ARG(12));
		COPY(ARG(12), ARG(9));
		COPY(ARG(11), ARG(8));
		COPY(ARG(10), ARG(7));
		goto M2_1;
		RETURN2:;
	}
}
