/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void rt_charG(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	Fchar_code(ARG(2));
	COPY(ARG(1), ARG(3));
	Fchar_code(ARG(3));
	Fgt(ARG(2), 2);
	COPY(ARG(2), ARG(0));
}
