/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void rt_struct_ref(CL_FORM *base)
{
	COPY(ARG(0), ARG(3));
	COPY(ARG(2), ARG(4));
	rt_struct_typep(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(0))), GET_FIXNUM(ARG(1)) + 1), ARG(0));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(3));	/* NO_STRUCT */
		COPY(ARG(0), ARG(4));
		COPY(ARG(2), ARG(5));
		Ferror(ARG(3), 3);
	}
}
