/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void search1(CL_FORM *base)
{
	if(CL_TRUEP(ARG(6)))
	{
	}
	else
	{
		COPY(ARG(0), ARG(10));
		Flength(ARG(10));
		COPY(ARG(10), ARG(6));
	}
	if(CL_TRUEP(ARG(8)))
	{
	}
	else
	{
		COPY(ARG(1), ARG(10));
		Flength(ARG(10));
		COPY(ARG(10), ARG(8));
	}
	if(CL_LISTP(ARG(1)))
	{
		COPY(ARG(7), ARG(10));
		COPY(ARG(1), ARG(11));
		Fnthcdr(ARG(10));
		COPY(ARG(7), ARG(11));
		COPY(ARG(8), ARG(12));
		COPY(ARG(6), ARG(13));
		COPY(ARG(5), ARG(14));
		Fminus(ARG(13), 2);
		Fminus(ARG(12), 2);
		LOAD_NIL(ARG(13));
		M1_1:;
		COPY(ARG(11), ARG(14));
		COPY(ARG(12), ARG(15));
		Fgt(ARG(14), 2);
		if(CL_TRUEP(ARG(14)))
		{
			COPY(ARG(13), ARG(0));
			goto RETURN1;
		}
		if(CL_LISTP(ARG(0)))
		{
			COPY(ARG(10), ARG(14));
			COPY(ARG(5), ARG(15));
			COPY(ARG(5), ARG(16));
			COPY(ARG(0), ARG(17));
			Fnthcdr(ARG(16));
			M2_1:;
			if(CL_TRUEP(ARG(14)))
			{
				LOAD_NIL(ARG(17));
			}
			else
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(17));	/* T */
			}
			if(CL_TRUEP(ARG(17)))
			{
				goto THEN1;
			}
			else
			{
				if(CL_TRUEP(ARG(16)))
				{
					LOAD_NIL(ARG(18));
				}
				else
				{
					LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(18));	/* T */
				}
				if(CL_TRUEP(ARG(18)))
				{
					goto THEN1;
				}
				else
				{
					COPY(ARG(6), ARG(19));
					COPY(ARG(15), ARG(20));
					Fnumeql(ARG(19), 2);
				}
			}
			if(CL_TRUEP(ARG(19)))
			{
				THEN1:;
				bool_result = TRUE;
				goto RETURN2;
			}
			if(CL_TRUEP(ARG(4)))
			{
				COPY(ARG(4), ARG(17));
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(18));
					if(CL_CONSP(ARG(14)))
					{
						COPY(GET_CAR(ARG(14)), ARG(19));
					}
					else
					{
						if(CL_TRUEP(ARG(14)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(19));	/* ~a is not a list */
							COPY(ARG(14), ARG(20));
							Ferror(ARG(19), 2);
						}
						else
						{
							COPY(ARG(14), ARG(19));
						}
					}
					Ffuncall(ARG(18), 2);
					mv_count = 1;
				}
				else
				{
					if(CL_CONSP(ARG(14)))
					{
						COPY(GET_CAR(ARG(14)), ARG(18));
					}
					else
					{
						if(CL_TRUEP(ARG(14)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(18));	/* ~a is not a list */
							COPY(ARG(14), ARG(19));
							Ferror(ARG(18), 2);
						}
						else
						{
							COPY(ARG(14), ARG(18));
						}
					}
				}
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(19));
					if(CL_CONSP(ARG(16)))
					{
						COPY(GET_CAR(ARG(16)), ARG(20));
					}
					else
					{
						if(CL_TRUEP(ARG(16)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(20));	/* ~a is not a list */
							COPY(ARG(16), ARG(21));
							Ferror(ARG(20), 2);
						}
						else
						{
							COPY(ARG(16), ARG(20));
						}
					}
					Ffuncall(ARG(19), 2);
					mv_count = 1;
				}
				else
				{
					if(CL_CONSP(ARG(16)))
					{
						COPY(GET_CAR(ARG(16)), ARG(19));
					}
					else
					{
						if(CL_TRUEP(ARG(16)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(19));	/* ~a is not a list */
							COPY(ARG(16), ARG(20));
							Ferror(ARG(19), 2);
						}
						else
						{
							COPY(ARG(16), ARG(19));
						}
					}
				}
				Ffuncall(ARG(17), 3);
				mv_count = 1;
				if(CL_TRUEP(ARG(17)))
				{
					bool_result = FALSE;
					goto RETURN2;
				}
			}
			else
			{
				COPY(ARG(3), ARG(17));
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(18));
					if(CL_CONSP(ARG(14)))
					{
						COPY(GET_CAR(ARG(14)), ARG(19));
					}
					else
					{
						if(CL_TRUEP(ARG(14)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(19));	/* ~a is not a list */
							COPY(ARG(14), ARG(20));
							Ferror(ARG(19), 2);
						}
						else
						{
							COPY(ARG(14), ARG(19));
						}
					}
					Ffuncall(ARG(18), 2);
					mv_count = 1;
				}
				else
				{
					if(CL_CONSP(ARG(14)))
					{
						COPY(GET_CAR(ARG(14)), ARG(18));
					}
					else
					{
						if(CL_TRUEP(ARG(14)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(18));	/* ~a is not a list */
							COPY(ARG(14), ARG(19));
							Ferror(ARG(18), 2);
						}
						else
						{
							COPY(ARG(14), ARG(18));
						}
					}
				}
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(19));
					if(CL_CONSP(ARG(16)))
					{
						COPY(GET_CAR(ARG(16)), ARG(20));
					}
					else
					{
						if(CL_TRUEP(ARG(16)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(20));	/* ~a is not a list */
							COPY(ARG(16), ARG(21));
							Ferror(ARG(20), 2);
						}
						else
						{
							COPY(ARG(16), ARG(20));
						}
					}
					Ffuncall(ARG(19), 2);
					mv_count = 1;
				}
				else
				{
					if(CL_CONSP(ARG(16)))
					{
						COPY(GET_CAR(ARG(16)), ARG(19));
					}
					else
					{
						if(CL_TRUEP(ARG(16)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(19));	/* ~a is not a list */
							COPY(ARG(16), ARG(20));
							Ferror(ARG(19), 2);
						}
						else
						{
							COPY(ARG(16), ARG(19));
						}
					}
				}
				Ffuncall(ARG(17), 3);
				mv_count = 1;
				if(CL_TRUEP(ARG(17)))
				{
				}
				else
				{
					bool_result = FALSE;
					goto RETURN2;
				}
			}
			COPY(ARG(14), ARG(17));
			if(CL_CONSP(ARG(17)))
			{
				COPY(GET_CDR(ARG(17)), ARG(17));
			}
			else
			{
				if(CL_TRUEP(ARG(17)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(18));	/* ~a is not a list */
					COPY(ARG(17), ARG(19));
					Ferror(ARG(18), 2);
				}
				else
				{
					LOAD_NIL(ARG(17));
				}
			}
			COPY(ARG(15), ARG(18));
			F1plus(ARG(18));
			COPY(ARG(16), ARG(19));
			if(CL_CONSP(ARG(19)))
			{
				COPY(GET_CDR(ARG(19)), ARG(16));
			}
			else
			{
				if(CL_TRUEP(ARG(19)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(20));	/* ~a is not a list */
					COPY(ARG(19), ARG(21));
					Ferror(ARG(20), 2);
				}
				else
				{
					LOAD_NIL(ARG(16));
				}
			}
			COPY(ARG(18), ARG(15));
			COPY(ARG(17), ARG(14));
			goto M2_1;
			RETURN2:;
		}
		else
		{
			COPY(ARG(10), ARG(14));
			COPY(ARG(5), ARG(15));
			M3_1:;
			if(CL_TRUEP(ARG(14)))
			{
				LOAD_NIL(ARG(16));
			}
			else
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(16));	/* T */
			}
			if(CL_TRUEP(ARG(16)))
			{
				goto THEN2;
			}
			else
			{
				COPY(ARG(15), ARG(17));
				COPY(ARG(6), ARG(18));
				Fnumeql(ARG(17), 2);
			}
			if(CL_TRUEP(ARG(17)))
			{
				THEN2:;
				bool_result = TRUE;
				goto RETURN3;
			}
			if(CL_TRUEP(ARG(4)))
			{
				COPY(ARG(4), ARG(16));
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(17));
					if(CL_CONSP(ARG(14)))
					{
						COPY(GET_CAR(ARG(14)), ARG(18));
					}
					else
					{
						if(CL_TRUEP(ARG(14)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(18));	/* ~a is not a list */
							COPY(ARG(14), ARG(19));
							Ferror(ARG(18), 2);
						}
						else
						{
							COPY(ARG(14), ARG(18));
						}
					}
					Ffuncall(ARG(17), 2);
					mv_count = 1;
				}
				else
				{
					if(CL_CONSP(ARG(14)))
					{
						COPY(GET_CAR(ARG(14)), ARG(17));
					}
					else
					{
						if(CL_TRUEP(ARG(14)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(17));	/* ~a is not a list */
							COPY(ARG(14), ARG(18));
							Ferror(ARG(17), 2);
						}
						else
						{
							COPY(ARG(14), ARG(17));
						}
					}
				}
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(18));
					LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(19));
					if(CL_TRUEP(ARG(19)))
					{
						goto THEN3;
					}
					else
					{
						COPY(ARG(0), ARG(20));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(21));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(20));
					}
					if(CL_TRUEP(ARG(20)))
					{
						THEN3:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(19));	/* WRONG_TYPE */
						COPY(ARG(0), ARG(20));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(21));	/* VECTOR */
						Ferror(ARG(19), 3);
					}
					COPY(ARG(0), ARG(19));
					COPY(ARG(15), ARG(20));
					Frow_major_aref(ARG(19));
					Ffuncall(ARG(18), 2);
					mv_count = 1;
				}
				else
				{
					LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(18));
					if(CL_TRUEP(ARG(18)))
					{
						goto THEN4;
					}
					else
					{
						COPY(ARG(0), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(20));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(19));
					}
					if(CL_TRUEP(ARG(19)))
					{
						THEN4:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(18));	/* WRONG_TYPE */
						COPY(ARG(0), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(20));	/* VECTOR */
						Ferror(ARG(18), 3);
					}
					COPY(ARG(0), ARG(18));
					COPY(ARG(15), ARG(19));
					Frow_major_aref(ARG(18));
				}
				Ffuncall(ARG(16), 3);
				mv_count = 1;
				if(CL_TRUEP(ARG(16)))
				{
					bool_result = FALSE;
					goto RETURN3;
				}
			}
			else
			{
				COPY(ARG(3), ARG(16));
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(17));
					if(CL_CONSP(ARG(14)))
					{
						COPY(GET_CAR(ARG(14)), ARG(18));
					}
					else
					{
						if(CL_TRUEP(ARG(14)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(18));	/* ~a is not a list */
							COPY(ARG(14), ARG(19));
							Ferror(ARG(18), 2);
						}
						else
						{
							COPY(ARG(14), ARG(18));
						}
					}
					Ffuncall(ARG(17), 2);
					mv_count = 1;
				}
				else
				{
					if(CL_CONSP(ARG(14)))
					{
						COPY(GET_CAR(ARG(14)), ARG(17));
					}
					else
					{
						if(CL_TRUEP(ARG(14)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(17));	/* ~a is not a list */
							COPY(ARG(14), ARG(18));
							Ferror(ARG(17), 2);
						}
						else
						{
							COPY(ARG(14), ARG(17));
						}
					}
				}
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(18));
					LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(19));
					if(CL_TRUEP(ARG(19)))
					{
						goto THEN5;
					}
					else
					{
						COPY(ARG(0), ARG(20));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(21));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(20));
					}
					if(CL_TRUEP(ARG(20)))
					{
						THEN5:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(19));	/* WRONG_TYPE */
						COPY(ARG(0), ARG(20));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(21));	/* VECTOR */
						Ferror(ARG(19), 3);
					}
					COPY(ARG(0), ARG(19));
					COPY(ARG(15), ARG(20));
					Frow_major_aref(ARG(19));
					Ffuncall(ARG(18), 2);
					mv_count = 1;
				}
				else
				{
					LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(18));
					if(CL_TRUEP(ARG(18)))
					{
						goto THEN6;
					}
					else
					{
						COPY(ARG(0), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(20));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(19));
					}
					if(CL_TRUEP(ARG(19)))
					{
						THEN6:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(18));	/* WRONG_TYPE */
						COPY(ARG(0), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(20));	/* VECTOR */
						Ferror(ARG(18), 3);
					}
					COPY(ARG(0), ARG(18));
					COPY(ARG(15), ARG(19));
					Frow_major_aref(ARG(18));
				}
				Ffuncall(ARG(16), 3);
				mv_count = 1;
				if(CL_TRUEP(ARG(16)))
				{
				}
				else
				{
					bool_result = FALSE;
					goto RETURN3;
				}
			}
			COPY(ARG(14), ARG(16));
			if(CL_CONSP(ARG(16)))
			{
				COPY(GET_CDR(ARG(16)), ARG(16));
			}
			else
			{
				if(CL_TRUEP(ARG(16)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(17));	/* ~a is not a list */
					COPY(ARG(16), ARG(18));
					Ferror(ARG(17), 2);
				}
				else
				{
					LOAD_NIL(ARG(16));
				}
			}
			COPY(ARG(15), ARG(17));
			F1plus(ARG(17));
			COPY(ARG(17), ARG(15));
			COPY(ARG(16), ARG(14));
			goto M3_1;
			RETURN3:;
		}
		if(bool_result)
		{
			if(CL_TRUEP(ARG(2)))
			{
				COPY(ARG(11), ARG(13));
			}
			else
			{
				COPY(ARG(11), ARG(0));
				goto RETURN1;
			}
		}
		COPY(ARG(10), ARG(14));
		if(CL_CONSP(ARG(14)))
		{
			COPY(GET_CDR(ARG(14)), ARG(14));
		}
		else
		{
			if(CL_TRUEP(ARG(14)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(15));	/* ~a is not a list */
				COPY(ARG(14), ARG(16));
				Ferror(ARG(15), 2);
			}
			else
			{
				LOAD_NIL(ARG(14));
			}
		}
		COPY(ARG(11), ARG(15));
		F1plus(ARG(15));
		COPY(ARG(15), ARG(11));
		COPY(ARG(14), ARG(10));
		goto M1_1;
		RETURN1:;
	}
	else
	{
		COPY(ARG(7), ARG(10));
		COPY(ARG(8), ARG(11));
		COPY(ARG(6), ARG(12));
		COPY(ARG(5), ARG(13));
		Fminus(ARG(12), 2);
		Fminus(ARG(11), 2);
		LOAD_NIL(ARG(12));
		M4_1:;
		COPY(ARG(10), ARG(13));
		COPY(ARG(11), ARG(14));
		Fgt(ARG(13), 2);
		if(CL_TRUEP(ARG(13)))
		{
			COPY(ARG(12), ARG(0));
			goto RETURN4;
		}
		if(CL_LISTP(ARG(0)))
		{
			COPY(ARG(5), ARG(13));
			COPY(ARG(0), ARG(14));
			Fnthcdr(ARG(13));
			COPY(ARG(5), ARG(14));
			COPY(ARG(10), ARG(15));
			M5_1:;
			COPY(ARG(6), ARG(16));
			COPY(ARG(14), ARG(17));
			Fnumeql(ARG(16), 2);
			if(CL_TRUEP(ARG(16)))
			{
				goto THEN7;
			}
			else
			{
				if(CL_TRUEP(ARG(13)))
				{
					goto ELSE8;
				}
				else
				{
					goto THEN7;
				}
			}
			{
				THEN7:;
				bool_result = TRUE;
				goto RETURN5;
			}
			ELSE8:;
			if(CL_TRUEP(ARG(4)))
			{
				COPY(ARG(4), ARG(16));
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(17));
					LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(18));
					if(CL_TRUEP(ARG(18)))
					{
						goto THEN9;
					}
					else
					{
						COPY(ARG(1), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(20));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(19));
					}
					if(CL_TRUEP(ARG(19)))
					{
						THEN9:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(18));	/* WRONG_TYPE */
						COPY(ARG(1), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(20));	/* VECTOR */
						Ferror(ARG(18), 3);
					}
					COPY(ARG(1), ARG(18));
					COPY(ARG(15), ARG(19));
					Frow_major_aref(ARG(18));
					Ffuncall(ARG(17), 2);
					mv_count = 1;
				}
				else
				{
					LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(17));
					if(CL_TRUEP(ARG(17)))
					{
						goto THEN10;
					}
					else
					{
						COPY(ARG(1), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(19));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(18));
					}
					if(CL_TRUEP(ARG(18)))
					{
						THEN10:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(17));	/* WRONG_TYPE */
						COPY(ARG(1), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(19));	/* VECTOR */
						Ferror(ARG(17), 3);
					}
					COPY(ARG(1), ARG(17));
					COPY(ARG(15), ARG(18));
					Frow_major_aref(ARG(17));
				}
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(18));
					if(CL_CONSP(ARG(13)))
					{
						COPY(GET_CAR(ARG(13)), ARG(19));
					}
					else
					{
						if(CL_TRUEP(ARG(13)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(19));	/* ~a is not a list */
							COPY(ARG(13), ARG(20));
							Ferror(ARG(19), 2);
						}
						else
						{
							COPY(ARG(13), ARG(19));
						}
					}
					Ffuncall(ARG(18), 2);
					mv_count = 1;
				}
				else
				{
					if(CL_CONSP(ARG(13)))
					{
						COPY(GET_CAR(ARG(13)), ARG(18));
					}
					else
					{
						if(CL_TRUEP(ARG(13)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(18));	/* ~a is not a list */
							COPY(ARG(13), ARG(19));
							Ferror(ARG(18), 2);
						}
						else
						{
							COPY(ARG(13), ARG(18));
						}
					}
				}
				Ffuncall(ARG(16), 3);
				mv_count = 1;
				if(CL_TRUEP(ARG(16)))
				{
					bool_result = FALSE;
					goto RETURN5;
				}
			}
			else
			{
				COPY(ARG(3), ARG(16));
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(17));
					LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(18));
					if(CL_TRUEP(ARG(18)))
					{
						goto THEN11;
					}
					else
					{
						COPY(ARG(1), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(20));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(19));
					}
					if(CL_TRUEP(ARG(19)))
					{
						THEN11:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(18));	/* WRONG_TYPE */
						COPY(ARG(1), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(20));	/* VECTOR */
						Ferror(ARG(18), 3);
					}
					COPY(ARG(1), ARG(18));
					COPY(ARG(15), ARG(19));
					Frow_major_aref(ARG(18));
					Ffuncall(ARG(17), 2);
					mv_count = 1;
				}
				else
				{
					LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(17));
					if(CL_TRUEP(ARG(17)))
					{
						goto THEN12;
					}
					else
					{
						COPY(ARG(1), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(19));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(18));
					}
					if(CL_TRUEP(ARG(18)))
					{
						THEN12:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(17));	/* WRONG_TYPE */
						COPY(ARG(1), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(19));	/* VECTOR */
						Ferror(ARG(17), 3);
					}
					COPY(ARG(1), ARG(17));
					COPY(ARG(15), ARG(18));
					Frow_major_aref(ARG(17));
				}
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(18));
					if(CL_CONSP(ARG(13)))
					{
						COPY(GET_CAR(ARG(13)), ARG(19));
					}
					else
					{
						if(CL_TRUEP(ARG(13)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(19));	/* ~a is not a list */
							COPY(ARG(13), ARG(20));
							Ferror(ARG(19), 2);
						}
						else
						{
							COPY(ARG(13), ARG(19));
						}
					}
					Ffuncall(ARG(18), 2);
					mv_count = 1;
				}
				else
				{
					if(CL_CONSP(ARG(13)))
					{
						COPY(GET_CAR(ARG(13)), ARG(18));
					}
					else
					{
						if(CL_TRUEP(ARG(13)))
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(18));	/* ~a is not a list */
							COPY(ARG(13), ARG(19));
							Ferror(ARG(18), 2);
						}
						else
						{
							COPY(ARG(13), ARG(18));
						}
					}
				}
				Ffuncall(ARG(16), 3);
				mv_count = 1;
				if(CL_TRUEP(ARG(16)))
				{
				}
				else
				{
					bool_result = FALSE;
					goto RETURN5;
				}
			}
			COPY(ARG(13), ARG(16));
			if(CL_CONSP(ARG(16)))
			{
				COPY(GET_CDR(ARG(16)), ARG(16));
			}
			else
			{
				if(CL_TRUEP(ARG(16)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(17));	/* ~a is not a list */
					COPY(ARG(16), ARG(18));
					Ferror(ARG(17), 2);
				}
				else
				{
					LOAD_NIL(ARG(16));
				}
			}
			COPY(ARG(14), ARG(17));
			F1plus(ARG(17));
			COPY(ARG(15), ARG(18));
			F1plus(ARG(18));
			COPY(ARG(18), ARG(15));
			COPY(ARG(17), ARG(14));
			COPY(ARG(16), ARG(13));
			goto M5_1;
			RETURN5:;
		}
		else
		{
			COPY(ARG(10), ARG(13));
			COPY(ARG(5), ARG(14));
			M6_1:;
			COPY(ARG(14), ARG(15));
			COPY(ARG(6), ARG(16));
			Fnumeql(ARG(15), 2);
			if(CL_TRUEP(ARG(15)))
			{
				bool_result = TRUE;
				goto RETURN6;
			}
			if(CL_TRUEP(ARG(4)))
			{
				COPY(ARG(4), ARG(15));
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(16));
					LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(17));
					if(CL_TRUEP(ARG(17)))
					{
						goto THEN13;
					}
					else
					{
						COPY(ARG(1), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(19));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(18));
					}
					if(CL_TRUEP(ARG(18)))
					{
						THEN13:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(17));	/* WRONG_TYPE */
						COPY(ARG(1), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(19));	/* VECTOR */
						Ferror(ARG(17), 3);
					}
					COPY(ARG(1), ARG(17));
					COPY(ARG(13), ARG(18));
					Frow_major_aref(ARG(17));
					Ffuncall(ARG(16), 2);
					mv_count = 1;
				}
				else
				{
					LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(16));
					if(CL_TRUEP(ARG(16)))
					{
						goto THEN14;
					}
					else
					{
						COPY(ARG(1), ARG(17));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(18));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(17));
					}
					if(CL_TRUEP(ARG(17)))
					{
						THEN14:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(16));	/* WRONG_TYPE */
						COPY(ARG(1), ARG(17));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(18));	/* VECTOR */
						Ferror(ARG(16), 3);
					}
					COPY(ARG(1), ARG(16));
					COPY(ARG(13), ARG(17));
					Frow_major_aref(ARG(16));
				}
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(17));
					LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(18));
					if(CL_TRUEP(ARG(18)))
					{
						goto THEN15;
					}
					else
					{
						COPY(ARG(0), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(20));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(19));
					}
					if(CL_TRUEP(ARG(19)))
					{
						THEN15:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(18));	/* WRONG_TYPE */
						COPY(ARG(0), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(20));	/* VECTOR */
						Ferror(ARG(18), 3);
					}
					COPY(ARG(0), ARG(18));
					COPY(ARG(14), ARG(19));
					Frow_major_aref(ARG(18));
					Ffuncall(ARG(17), 2);
					mv_count = 1;
				}
				else
				{
					LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(17));
					if(CL_TRUEP(ARG(17)))
					{
						goto THEN16;
					}
					else
					{
						COPY(ARG(0), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(19));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(18));
					}
					if(CL_TRUEP(ARG(18)))
					{
						THEN16:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(17));	/* WRONG_TYPE */
						COPY(ARG(0), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(19));	/* VECTOR */
						Ferror(ARG(17), 3);
					}
					COPY(ARG(0), ARG(17));
					COPY(ARG(14), ARG(18));
					Frow_major_aref(ARG(17));
				}
				Ffuncall(ARG(15), 3);
				mv_count = 1;
				if(CL_TRUEP(ARG(15)))
				{
					bool_result = FALSE;
					goto RETURN6;
				}
			}
			else
			{
				COPY(ARG(3), ARG(15));
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(16));
					LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(17));
					if(CL_TRUEP(ARG(17)))
					{
						goto THEN17;
					}
					else
					{
						COPY(ARG(1), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(19));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(18));
					}
					if(CL_TRUEP(ARG(18)))
					{
						THEN17:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(17));	/* WRONG_TYPE */
						COPY(ARG(1), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(19));	/* VECTOR */
						Ferror(ARG(17), 3);
					}
					COPY(ARG(1), ARG(17));
					COPY(ARG(13), ARG(18));
					Frow_major_aref(ARG(17));
					Ffuncall(ARG(16), 2);
					mv_count = 1;
				}
				else
				{
					LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(16));
					if(CL_TRUEP(ARG(16)))
					{
						goto THEN18;
					}
					else
					{
						COPY(ARG(1), ARG(17));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(18));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(17));
					}
					if(CL_TRUEP(ARG(17)))
					{
						THEN18:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(16));	/* WRONG_TYPE */
						COPY(ARG(1), ARG(17));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(18));	/* VECTOR */
						Ferror(ARG(16), 3);
					}
					COPY(ARG(1), ARG(16));
					COPY(ARG(13), ARG(17));
					Frow_major_aref(ARG(16));
				}
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(9), ARG(17));
					LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(18));
					if(CL_TRUEP(ARG(18)))
					{
						goto THEN19;
					}
					else
					{
						COPY(ARG(0), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(20));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(19));
					}
					if(CL_TRUEP(ARG(19)))
					{
						THEN19:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(18));	/* WRONG_TYPE */
						COPY(ARG(0), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(20));	/* VECTOR */
						Ferror(ARG(18), 3);
					}
					COPY(ARG(0), ARG(18));
					COPY(ARG(14), ARG(19));
					Frow_major_aref(ARG(18));
					Ffuncall(ARG(17), 2);
					mv_count = 1;
				}
				else
				{
					LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(17));
					if(CL_TRUEP(ARG(17)))
					{
						goto THEN20;
					}
					else
					{
						COPY(ARG(0), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(19));	/* COMPLEX-VECTOR */
						rt_struct_typep(ARG(18));
					}
					if(CL_TRUEP(ARG(18)))
					{
						THEN20:;
					}
					else
					{
						COPY(SYMVAL(Slisp, 58), ARG(17));	/* WRONG_TYPE */
						COPY(ARG(0), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(19));	/* VECTOR */
						Ferror(ARG(17), 3);
					}
					COPY(ARG(0), ARG(17));
					COPY(ARG(14), ARG(18));
					Frow_major_aref(ARG(17));
				}
				Ffuncall(ARG(15), 3);
				mv_count = 1;
				if(CL_TRUEP(ARG(15)))
				{
				}
				else
				{
					bool_result = FALSE;
					goto RETURN6;
				}
			}
			COPY(ARG(13), ARG(15));
			F1plus(ARG(15));
			COPY(ARG(14), ARG(16));
			F1plus(ARG(16));
			COPY(ARG(16), ARG(14));
			COPY(ARG(15), ARG(13));
			goto M6_1;
			RETURN6:;
		}
		if(bool_result)
		{
			if(CL_TRUEP(ARG(2)))
			{
				COPY(ARG(10), ARG(12));
			}
			else
			{
				COPY(ARG(10), ARG(0));
				goto RETURN4;
			}
		}
		COPY(ARG(10), ARG(13));
		F1plus(ARG(13));
		COPY(ARG(13), ARG(10));
		goto M4_1;
		RETURN4:;
	}
}
