/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

extern CL_INIT XIset_pvref[];
extern CL_INIT XFset_pvref[];
CL_INIT Kset_pvref[] =
{
	MAKE_STRING(40, "ecase: the value ~a is not a legal value"),	/* 0 */
	MAKE_STRING(37, "Can\'t store ~A in a vector of type ~A"),	/* 2 */
};

void set_pvref(CL_FORM *base)
{
	if(CL_FIXNUMP(ARG(2)))
	{
		LOAD_SMALLFIXNUM(0, ARG(3));
		COPY(ARG(2), ARG(4));
		LOAD_FIXNUM(ARG(6), AR_SIZE(GET_FORM(ARG(1))), ARG(5));
		F1minus(ARG(5));
		Fle(ARG(3), 3);
	}
	else
	{
		goto ELSE1;
	}
	if(CL_TRUEP(ARG(3)))
	{
	}
	else
	{
		ELSE1:;
		COPY(SYMVAL(Slisp, 151), ARG(3));	/* OUT_OF_RANGE */
		COPY(ARG(2), ARG(4));
		LOAD_FIXNUM(ARG(6), AR_SIZE(GET_FORM(ARG(1))), ARG(5));
		Ferror(ARG(3), 3);
	}
	COPY(ARG(1), ARG(3));
	rt_plain_vector_element_code(ARG(3));
	LOAD_SMALLFIXNUM(0, ARG(5));
	if(EQL(ARG(3), ARG(5)))
	{
		goto THEN2;
	}
	else
	{
		LOAD_SMALLFIXNUM(1, ARG(5));
		if(EQL(ARG(3), ARG(5)))
		{
			bool_result = CL_FIXNUMP(ARG(0));
		}
		else
		{
			LOAD_SMALLFIXNUM(2, ARG(5));
			if(EQL(ARG(3), ARG(5)))
			{
				bool_result = CL_FLOATP(ARG(0));
			}
			else
			{
				LOAD_SMALLFIXNUM(3, ARG(5));
				if(EQL(ARG(3), ARG(5)))
				{
					bool_result = CL_CHARP(ARG(0));
				}
				else
				{
					LOAD_SMALLFIXNUM(4, ARG(5));
					if(EQL(ARG(3), ARG(5)))
					{
						if(CL_FIXNUMP(ARG(0)))
						{
							LOAD_SMALLFIXNUM(0, ARG(4));
							COPY(ARG(0), ARG(5));
							LOAD_SMALLFIXNUM(1, ARG(6));
							Fle(ARG(4), 3);
						}
						else
						{
							goto ELSE3;
						}
						bool_result = CL_TRUEP(ARG(4));
					}
					else
					{
						LOAD_SMSTR((CL_FORM *)&Kset_pvref[0], ARG(4));	/* ecase: the value ~a is not a legal value */
						COPY(ARG(3), ARG(5));
						Ferror(ARG(4), 2);
					}
				}
			}
		}
	}
	if(bool_result)
	{
		THEN2:;
	}
	else
	{
		ELSE3:;
		LOAD_SMSTR((CL_FORM *)&Kset_pvref[2], ARG(3));	/* Can't store ~A in a vector of type ~A */
		COPY(ARG(0), ARG(4));
		COPY(ARG(1), ARG(5));
		rt_plain_vector_element_code(ARG(5));
		Ferror(ARG(3), 3);
	}
	rt_set_pvref(ARG(0));
}
