/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

static void Z59_lambda(CL_FORM *base);

void set_gethash1(CL_FORM *base)
{
	COPY(ARG(2), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(5));	/* HASH-TABLE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 0 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(4));	/* NO_STRUCT */
		COPY(ARG(2), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(6));	/* HASH-TABLE */
		Ferror(ARG(4), 3);
	}
	COPY(ARG(1), ARG(5));
	LOAD_SMALLFIXNUM(0, ARG(6));
	internal_sxhash(ARG(5));
	mv_count = 1;
	COPY(ARG(5), ARG(6));
	COPY(ARG(4), ARG(7));
	LOAD_SMALLFIXNUM(0, ARG(8));
	rt_convert_to_int(ARG(6));
	COPY(&mv_buf[0], ARG(7));
	mv_count = 1;
	{
		COPY(ARG(7), ARG(5));
	}
	COPY(ARG(2), ARG(6));
	LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(7));	/* HASH-TABLE */
	rt_struct_typep(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 5 + 1), ARG(6));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(6));	/* NO_STRUCT */
		COPY(ARG(2), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(8));	/* HASH-TABLE */
		Ferror(ARG(6), 3);
	}
	LOAD_BOOL(CL_SMVECP(ARG(6)), ARG(7));
	if(CL_TRUEP(ARG(7)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(6), ARG(8));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(9));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(8));
	}
	if(CL_TRUEP(ARG(8)))
	{
		THEN1:;
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(7));	/* WRONG_TYPE */
		COPY(ARG(6), ARG(8));
		LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(9));	/* VECTOR */
		Ferror(ARG(7), 3);
	}
	COPY(ARG(5), ARG(7));
	Frow_major_aref(ARG(6));
	COPY(ARG(2), ARG(7));
	LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(8));	/* HASH-TABLE */
	rt_struct_typep(ARG(7));
	if(CL_TRUEP(ARG(7)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 4 + 1), ARG(7));
	}
	else
	{
		COPY(SYMVAL(Slisp, 342), ARG(7));	/* NO_STRUCT */
		COPY(ARG(2), ARG(8));
		LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(9));	/* HASH-TABLE */
		Ferror(ARG(7), 3);
	}
	LOAD_GLOBFUN(&CFcar, ARG(8));
	LOAD_NIL(ARG(9));
	LOAD_NIL(ARG(10));
	LOAD_SMALLFIXNUM(0, ARG(11));
	COPY(SYMVAL(Slisp, 0), ARG(12));	/* MOST-POSITIVE-FIXNUM */
	if(CL_LISTP(ARG(6)))
	{
		COPY(ARG(1), ARG(13));
		COPY(ARG(6), ARG(14));
		LOAD_NIL(ARG(15));
		COPY(ARG(7), ARG(16));
		LOAD_NIL(ARG(17));
		COPY(ARG(11), ARG(18));
		COPY(ARG(12), ARG(19));
		LOAD_GLOBFUN(&CFcar, ARG(20));
		list_find(ARG(13));
		COPY(ARG(13), ARG(6));
	}
	else
	{
		COPY(ARG(1), ARG(13));
		COPY(ARG(6), ARG(14));
		LOAD_NIL(ARG(15));
		COPY(ARG(7), ARG(16));
		LOAD_NIL(ARG(17));
		COPY(ARG(11), ARG(18));
		COPY(ARG(12), ARG(19));
		LOAD_GLOBFUN(&CFcar, ARG(20));
		vector_find(ARG(13));
		COPY(ARG(13), ARG(6));
	}
	if(CL_TRUEP(ARG(6)))
	{
		if(CL_CONSP(ARG(6)))
		{
			COPY(ARG(0), GET_CDR(ARG(6)));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[231], ARG(0));	/* ~a is not a cons */
			COPY(ARG(6), ARG(1));
			Ferror(ARG(0), 2);
		}
	}
	else
	{
		COPY(ARG(2), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(8));	/* HASH-TABLE */
		rt_struct_typep(ARG(7));
		if(CL_TRUEP(ARG(7)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 1 + 1), ARG(7));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(7));	/* NO_STRUCT */
			COPY(ARG(2), ARG(8));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(9));	/* HASH-TABLE */
			Ferror(ARG(7), 3);
		}
		F1plus(ARG(7));
		COPY(ARG(4), ARG(8));
		Fdiv(ARG(7), 2);
		COPY(ARG(2), ARG(8));
		LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(9));	/* HASH-TABLE */
		rt_struct_typep(ARG(8));
		if(CL_TRUEP(ARG(8)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 3 + 1), ARG(8));
		}
		else
		{
			COPY(SYMVAL(Slisp, 342), ARG(8));	/* NO_STRUCT */
			COPY(ARG(2), ARG(9));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(10));	/* HASH-TABLE */
			Ferror(ARG(8), 3);
		}
		Fgt(ARG(7), 2);
		if(CL_TRUEP(ARG(7)))
		{
			COPY(ARG(2), ARG(7));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(8));	/* HASH-TABLE */
			rt_struct_typep(ARG(7));
			if(CL_TRUEP(ARG(7)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 2 + 1), ARG(7));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(7));	/* NO_STRUCT */
				COPY(ARG(2), ARG(8));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(9));	/* HASH-TABLE */
				Ferror(ARG(7), 3);
			}
			if(CL_FIXNUMP(ARG(7)))
			{
				COPY(ARG(4), ARG(8));
				COPY(ARG(7), ARG(9));
				Fplus(ARG(8), 2);
			}
			else
			{
				COPY(ARG(4), ARG(8));
				COPY(ARG(7), ARG(9));
				Fmult(ARG(8), 2);
				LOAD_SMALLFIXNUM(1, ARG(9));
				LOAD_SMALLFIXNUM(1, ARG(10));
				rt_convert_to_int(ARG(8));
				mv_count = 1;
			}
			COPY(ARG(2), ARG(9));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(10));	/* HASH-TABLE */
			rt_struct_typep(ARG(9));
			if(CL_TRUEP(ARG(9)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 4 + 1), ARG(9));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(9));	/* NO_STRUCT */
				COPY(ARG(2), ARG(10));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(11));	/* HASH-TABLE */
				Ferror(ARG(9), 3);
			}
			COPY(ARG(2), ARG(10));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(11));	/* HASH-TABLE */
			rt_struct_typep(ARG(10));
			if(CL_TRUEP(ARG(10)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 3 + 1), ARG(10));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(10));	/* NO_STRUCT */
				COPY(ARG(2), ARG(11));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(12));	/* HASH-TABLE */
				Ferror(ARG(10), 3);
			}
			GEN_FLOAT(ARG(11), 1.5, ARG(11));
			COPY(ARG(9), ARG(12));
			COPY(ARG(8), ARG(13));
			COPY(ARG(11), ARG(14));
			COPY(ARG(10), ARG(15));
			make_hash_table1(ARG(12));
			COPY(ARG(12), ARG(9));
			GEN_HEAPVAR(ARG(9), ARG(10));
			{
				GEN_CLOSURE(array, ARG(10), 4, Z59_lambda, 2);
				COPY(ARG(9), &array[3]);
				LOAD_CLOSURE(array, ARG(10));
			}
			COPY(ARG(10), ARG(10));
			COPY(ARG(2), ARG(11));
			Fmaphash(ARG(10));
			COPY(ARG(0), ARG(10));
			COPY(ARG(1), ARG(11));
			COPY(INDIRECT(ARG(9)), ARG(12));
			LOAD_NIL(ARG(13));
			set_gethash1(ARG(10));
			COPY(INDIRECT(ARG(9)), ARG(10));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(11));	/* HASH-TABLE */
			rt_struct_typep(ARG(10));
			if(CL_TRUEP(ARG(10)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(INDIRECT(ARG(9)))), 0 + 1), ARG(10));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(10));	/* NO_STRUCT */
				COPY(INDIRECT(ARG(9)), ARG(11));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(12));	/* HASH-TABLE */
				Ferror(ARG(10), 3);
			}
			LOAD_SMALLFIXNUM(0, ARG(11));
			COPY(ARG(2), ARG(12));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(13));	/* HASH-TABLE */
			rt_struct_typep(ARG(12));
			if(CL_TRUEP(ARG(12)))
			{
				COPY(ARG(10), OFFSET(AR_BASE(GET_FORM(ARG(2))), GET_FIXNUM(ARG(11)) + 1));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(12));	/* NO_STRUCT */
				COPY(ARG(2), ARG(13));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(14));	/* HASH-TABLE */
				Ferror(ARG(12), 3);
			}
			COPY(INDIRECT(ARG(9)), ARG(10));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(11));	/* HASH-TABLE */
			rt_struct_typep(ARG(10));
			if(CL_TRUEP(ARG(10)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(INDIRECT(ARG(9)))), 1 + 1), ARG(10));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(10));	/* NO_STRUCT */
				COPY(INDIRECT(ARG(9)), ARG(11));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(12));	/* HASH-TABLE */
				Ferror(ARG(10), 3);
			}
			LOAD_SMALLFIXNUM(1, ARG(11));
			COPY(ARG(2), ARG(12));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(13));	/* HASH-TABLE */
			rt_struct_typep(ARG(12));
			if(CL_TRUEP(ARG(12)))
			{
				COPY(ARG(10), OFFSET(AR_BASE(GET_FORM(ARG(2))), GET_FIXNUM(ARG(11)) + 1));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(12));	/* NO_STRUCT */
				COPY(ARG(2), ARG(13));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(14));	/* HASH-TABLE */
				Ferror(ARG(12), 3);
			}
			COPY(INDIRECT(ARG(9)), ARG(10));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(11));	/* HASH-TABLE */
			rt_struct_typep(ARG(10));
			if(CL_TRUEP(ARG(10)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(INDIRECT(ARG(9)))), 5 + 1), ARG(10));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(10));	/* NO_STRUCT */
				COPY(INDIRECT(ARG(9)), ARG(11));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(12));	/* HASH-TABLE */
				Ferror(ARG(10), 3);
			}
			LOAD_SMALLFIXNUM(5, ARG(11));
			COPY(ARG(2), ARG(12));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(13));	/* HASH-TABLE */
			rt_struct_typep(ARG(12));
			if(CL_TRUEP(ARG(12)))
			{
				COPY(ARG(10), OFFSET(AR_BASE(GET_FORM(ARG(2))), GET_FIXNUM(ARG(11)) + 1));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(12));	/* NO_STRUCT */
				COPY(ARG(2), ARG(13));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(14));	/* HASH-TABLE */
				Ferror(ARG(12), 3);
			}
		}
		else
		{
			COPY(ARG(2), ARG(7));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(8));	/* HASH-TABLE */
			rt_struct_typep(ARG(7));
			if(CL_TRUEP(ARG(7)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 1 + 1), ARG(7));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(7));	/* NO_STRUCT */
				COPY(ARG(2), ARG(8));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(9));	/* HASH-TABLE */
				Ferror(ARG(7), 3);
			}
			F1plus(ARG(7));
			LOAD_SMALLFIXNUM(1, ARG(8));
			COPY(ARG(2), ARG(9));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(10));	/* HASH-TABLE */
			rt_struct_typep(ARG(9));
			if(CL_TRUEP(ARG(9)))
			{
				COPY(ARG(7), OFFSET(AR_BASE(GET_FORM(ARG(2))), GET_FIXNUM(ARG(8)) + 1));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(9));	/* NO_STRUCT */
				COPY(ARG(2), ARG(10));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(11));	/* HASH-TABLE */
				Ferror(ARG(9), 3);
			}
			COPY(ARG(2), ARG(7));
			LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(8));	/* HASH-TABLE */
			rt_struct_typep(ARG(7));
			if(CL_TRUEP(ARG(7)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 5 + 1), ARG(7));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(7));	/* NO_STRUCT */
				COPY(ARG(2), ARG(8));
				LOAD_SYMBOL(SYMBOL(Slisp, 389), ARG(9));	/* HASH-TABLE */
				Ferror(ARG(7), 3);
			}
			ALLOC_CONS(ARG(10), ARG(1), ARG(0), ARG(8));
			LOAD_BOOL(CL_SMVECP(ARG(7)), ARG(9));
			if(CL_TRUEP(ARG(9)))
			{
				goto THEN2;
			}
			else
			{
				COPY(ARG(7), ARG(10));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(11));	/* COMPLEX-VECTOR */
				rt_struct_typep(ARG(10));
			}
			if(CL_TRUEP(ARG(10)))
			{
				THEN2:;
			}
			else
			{
				COPY(SYMVAL(Slisp, 58), ARG(9));	/* WRONG_TYPE */
				COPY(ARG(7), ARG(10));
				LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(11));	/* VECTOR */
				Ferror(ARG(9), 3);
			}
			COPY(ARG(7), ARG(9));
			COPY(ARG(5), ARG(10));
			Frow_major_aref(ARG(9));
			ALLOC_CONS(ARG(10), ARG(8), ARG(9), ARG(8));
			COPY(ARG(8), ARG(9));
			COPY(ARG(7), ARG(10));
			COPY(ARG(5), ARG(11));
			rt_set_vref(ARG(9));
		}
	}
}

static void Z59_lambda(CL_FORM *base)
{
	COPY(ARG(2), ARG(3));
	COPY(ARG(1), ARG(4));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(5));
	LOAD_NIL(ARG(6));
	set_gethash1(ARG(3));
	COPY(ARG(3), ARG(0));
}
