/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void shadow1(CL_FORM *base)
{
	COPY(ARG(1), ARG(2));
	if(CL_SYMBOLP(ARG(2)) || CL_NILP(ARG(2)))
	{
		COPY(ARG(2), ARG(3));
		if(CL_SYMBOLP(ARG(3)))
		{
			GET_SYM_NAME(ARG(5), ARG(3), ARG(2));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(2));	/* NIL */
		}
	}
	COPY(ARG(2), ARG(3));
	Fstringp(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		Ffind_package(ARG(2));
	}
	COPY(ARG(2), ARG(1));
	if(CL_LISTP(ARG(0)))
	{
	}
	else
	{
		COPY(ARG(0), ARG(2));
		Flist(ARG(2), 1);
		COPY(ARG(2), ARG(0));
	}
	LOAD_NIL(ARG(2));
	COPY(ARG(0), ARG(3));
	M1_1:;
	if(CL_ATOMP(ARG(3)))
	{
		LOAD_NIL(ARG(2));
		goto RETURN1;
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CAR(ARG(4)), ARG(2));
	if(CL_SYMBOLP(ARG(2)))
	{
		GET_SYM_NAME(ARG(5), ARG(2), ARG(4));
	}
	else
	{
		if(CL_TRUEP(ARG(2)))
		{
			COPY(SYMVAL(Slisp, 679), ARG(4));	/* SYM_EXPECTED */
			COPY(ARG(2), ARG(5));
			Ferror(ARG(4), 2);
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[243], ARG(4));	/* NIL */
		}
	}
	COPY(ARG(4), ARG(5));
	COPY(ARG(1), ARG(6));
	find_symbol1(ARG(5));
	COPY(&mv_buf[0], ARG(6));
	{
		int nargs;
		nargs = 2;
		mv_count = 1;
		{
			switch(nargs)
			{
				case 0:
				LOAD_NIL(ARG(5));
				case 1:
				LOAD_NIL(ARG(6));
				nargs = 2;
			}
			LOAD_BOOL(CL_SYMBOLP(ARG(6)) && GET_SYMBOL(ARG(6)) == SYMBOL(Slisp, 374), ARG(7));	/* INTERNAL */
			if(CL_TRUEP(ARG(7)))
			{
				goto THEN1;
			}
			else
			{
			}	/* EXTERNAL */
			if(CL_SYMBOLP(ARG(6)) && GET_SYMBOL(ARG(6)) == SYMBOL(Slisp, 375))
			{
				THEN1:;
			}
			else
			{
				COPY(ARG(4), ARG(7));
				Fmake_symbol(ARG(7));
				COPY(ARG(7), ARG(2));
				COPY(ARG(1), ARG(8));
				internal_import(ARG(7));
			}
			COPY(ARG(1), ARG(8));
			LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(9));	/* PACKAGE */
			rt_struct_typep(ARG(8));
			if(CL_TRUEP(ARG(8)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 4 + 1), ARG(8));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(8));	/* NO_STRUCT */
				COPY(ARG(1), ARG(9));
				LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(10));	/* PACKAGE */
				Ferror(ARG(8), 3);
			}
			ALLOC_CONS(ARG(9), ARG(2), ARG(8), ARG(7));
			LOAD_SMALLFIXNUM(4, ARG(8));
			COPY(ARG(1), ARG(9));
			LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(10));	/* PACKAGE */
			rt_struct_typep(ARG(9));
			if(CL_TRUEP(ARG(9)))
			{
				COPY(ARG(7), OFFSET(AR_BASE(GET_FORM(ARG(1))), GET_FIXNUM(ARG(8)) + 1));
			}
			else
			{
				COPY(SYMVAL(Slisp, 342), ARG(9));	/* NO_STRUCT */
				COPY(ARG(1), ARG(10));
				LOAD_SYMBOL(SYMBOL(Slisp, 344), ARG(11));	/* PACKAGE */
				Ferror(ARG(9), 3);
			}
		}
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CDR(ARG(4)), ARG(3));
	goto M1_1;
	RETURN1:;
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
}
