/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Cstruct_reader, struct_reader, 3);

extern CL_INIT XIstruct_reader[];
extern CL_INIT XFstruct_reader[];
CL_INIT Kstruct_reader[] =
{
	MAKE_STRING(30, "illegal value (~s) followed #S"),	/* 0 */
	MAKE_STRING(21, "~a is not a structure"),	/* 2 */
	MAKE_STRING(22, "unexpected end in #S~s"),	/* 4 */
};

void struct_reader(CL_FORM *base)
{
	if(CL_TRUEP(ARG(2)))
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[208], ARG(3));	/* extra argument for #~S */
		COPY(ARG(1), ARG(4));
		Ferror(ARG(3), 2);
	}
	COPY(ARG(0), ARG(3));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(4));	/* T */
	LOAD_NIL(ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(6));	/* T */
	read1(ARG(3));
	if(CL_TRUEP(SYMVAL(Slisp, 408)))	/* *READ-SUPPRESS* */
	{
		LOAD_NIL(ARG(0));
	}
	else
	{
		if(CL_ATOMP(ARG(3)))
		{
			LOAD_SMSTR((CL_FORM *)&Kstruct_reader[0], ARG(0));	/* illegal value (~s) followed #S */
			COPY(ARG(3), ARG(1));
			Ferror(ARG(0), 2);
		}
		else
		{
			COPY(GET_CAR(ARG(3)), ARG(4));
			LOAD_SYMBOL(SYMBOL(Slisp, 340), ARG(5));	/* STRUCT-CONSTRUCTOR */
			LOAD_NIL(ARG(6));
			get1(ARG(4));
			COPY(GET_CDR(ARG(3)), ARG(5));
			if(CL_TRUEP(ARG(4)))
			{
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&Kstruct_reader[2], ARG(6));	/* ~a is not a structure */
				COPY(GET_CAR(ARG(3)), ARG(7));
				Ferror(ARG(6), 2);
			}
			LOAD_NIL(ARG(6));
			M1_1:;
			if(CL_TRUEP(ARG(5)))
			{
				if(CL_CONSP(ARG(5)))
				{
					goto ELSE1;
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[233], ARG(7));	/* ~a is not a list */
					COPY(ARG(5), ARG(8));
					Ferror(ARG(7), 2);
				}
			}
			else
			{
				goto THEN2;
			}
			{
				THEN2:;
				COPY(ARG(4), ARG(7));
				if(CL_TRUEP(ARG(6)))
				{
					if(CL_CONSP(ARG(6)))
					{
						COPY(ARG(6), ARG(8));
						list_nreverse(ARG(8));
					}
					else
					{
						COPY(ARG(6), ARG(8));
						vector_nreverse(ARG(8));
					}
				}
				else
				{
					LOAD_NIL(ARG(8));
				}
				Fapply(ARG(7), 2);
				COPY(ARG(7), ARG(0));
				goto RETURN1;
			}
			ELSE1:;
			COPY(ARG(5), ARG(7));
			if(CL_CONSP(ARG(7)))
			{
				COPY(GET_CAR(ARG(7)), ARG(7));
			}
			else
			{
				if(CL_TRUEP(ARG(7)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(8));	/* ~a is not a list */
					COPY(ARG(7), ARG(9));
					Ferror(ARG(8), 2);
				}
				else
				{
					LOAD_NIL(ARG(7));
				}
			}
			Fstring(ARG(7));
			COPY(SYMVAL(Slisp, 380), ARG(8));	/* *KEYWORD-PACKAGE* */
			intern1(ARG(7));
			mv_count = 1;
			ALLOC_CONS(ARG(9), ARG(7), ARG(6), ARG(6));
			if(CL_CONSP(ARG(5)))
			{
			}
			else
			{
				if(CL_TRUEP(ARG(5)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(7));	/* ~a is not a list */
					COPY(ARG(5), ARG(8));
					Ferror(ARG(7), 2);
				}
				else
				{
				}
			}
			COPY(ARG(5), ARG(7));
			COPY(ARG(7), ARG(8));
			if(CL_CONSP(ARG(8)))
			{
				COPY(GET_CDR(ARG(8)), ARG(5));
			}
			else
			{
				if(CL_TRUEP(ARG(8)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(9));	/* ~a is not a list */
					COPY(ARG(8), ARG(10));
					Ferror(ARG(9), 2);
				}
				else
				{
					LOAD_NIL(ARG(5));
				}
			}
			if(CL_TRUEP(ARG(5)))
			{
				if(CL_CONSP(ARG(5)))
				{
					goto ELSE3;
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[233], ARG(7));	/* ~a is not a list */
					COPY(ARG(5), ARG(8));
					Ferror(ARG(7), 2);
				}
			}
			else
			{
				goto THEN4;
			}
			{
				THEN4:;
				LOAD_SMSTR((CL_FORM *)&Kstruct_reader[4], ARG(7));	/* unexpected end in #S~s */
				COPY(ARG(5), ARG(8));
				Ferror(ARG(7), 2);
			}
			ELSE3:;
			COPY(ARG(5), ARG(7));
			if(CL_CONSP(ARG(7)))
			{
				COPY(GET_CAR(ARG(7)), ARG(7));
			}
			else
			{
				if(CL_TRUEP(ARG(7)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(8));	/* ~a is not a list */
					COPY(ARG(7), ARG(9));
					Ferror(ARG(8), 2);
				}
				else
				{
					LOAD_NIL(ARG(7));
				}
			}
			ALLOC_CONS(ARG(9), ARG(7), ARG(6), ARG(6));
			if(CL_CONSP(ARG(5)))
			{
			}
			else
			{
				if(CL_TRUEP(ARG(5)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[239], ARG(7));	/* ~a is not a list */
					COPY(ARG(5), ARG(8));
					Ferror(ARG(7), 2);
				}
				else
				{
				}
			}
			COPY(ARG(5), ARG(7));
			COPY(ARG(7), ARG(8));
			if(CL_CONSP(ARG(8)))
			{
				COPY(GET_CDR(ARG(8)), ARG(5));
			}
			else
			{
				if(CL_TRUEP(ARG(8)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[241], ARG(9));	/* ~a is not a list */
					COPY(ARG(8), ARG(10));
					Ferror(ARG(9), 2);
				}
				else
				{
					LOAD_NIL(ARG(5));
				}
			}
			goto M1_1;
			RETURN1:;
		}
	}
}
