/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void subst_if_not1(CL_FORM *base)
{
	COPY(ARG(1), ARG(4));
	Fcomplement(ARG(4));
	COPY(ARG(4), ARG(1));
	subst_if1(ARG(0));
}
