/* This file was generated by CLiCC 0.6.5 [OBREP 2] */
#include <c_decl.h>
#if OBREP != 2
	#error "Wrong OBREP!"
#endif
#include "sys.h"
#include "lisp.h"

void to_type_code(CL_FORM *base)
{
	if(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 23))	/* FIXNUM */
	{
		LOAD_SMALLFIXNUM(1, ARG(0));
	}
	else
	{
		LOAD_BOOL(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 24), ARG(1));	/* FLOAT */
		if(CL_TRUEP(ARG(1)))
		{
			goto THEN1;
		}
		else
		{
			LOAD_BOOL(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 37), ARG(2));	/* SHORT-FLOAT */
			if(CL_TRUEP(ARG(2)))
			{
				goto THEN1;
			}
			else
			{
				LOAD_BOOL(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 42), ARG(3));	/* SINGLE-FLOAT */
				if(CL_TRUEP(ARG(3)))
				{
					goto THEN1;
				}
				else
				{
					LOAD_BOOL(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 22), ARG(4));	/* DOUBLE-FLOAT */
					if(CL_TRUEP(ARG(4)))
					{
						goto THEN1;
					}
					else
					{
					}	/* LONG-FLOAT */
				}
			}
		}
		if(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 29))
		{
			THEN1:;
			LOAD_SMALLFIXNUM(2, ARG(0));
		}
		else
		{
			LOAD_BOOL(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 43), ARG(1));	/* STANDARD-CHAR */
			if(CL_TRUEP(ARG(1)))
			{
				goto THEN2;
			}
			else
			{
			}	/* CHARACTER */
			if(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 18))
			{
				THEN2:;
				LOAD_SMALLFIXNUM(3, ARG(0));
			}
			else
			{
				if(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 16))	/* BIT */
				{
					LOAD_SMALLFIXNUM(4, ARG(0));
				}
				else
				{
					LOAD_SMALLFIXNUM(0, ARG(0));
				}
			}
		}
	}
}
